### ISSUE TITLE
Red output from "Local Npm module "grunt-browserify" not found" onwards.

### ISSUE THREAD

**Issue by jezmck** [Varying-Vagrant-Vagrants/VVV#670] opened 2015-06-18 08:23 UTC
I followed the instructions at https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/README.md#the-first-vagrant-up but at step 8 I got the following output which went red from 
`>> Local Npm module "grunt-browserify" not found. Is it installed?` onwards, even my `C:\` prompt is red, though there is one yellow line for the Warning re `uglify`.

This is my first time using VVV (but not Vagrant) so I'm unsure as to how serious this is.

![image](https://cloud.githubusercontent.com/assets/89996/8227106/2984e81c-159c-11e5-8b23-caf4022b0852.png)

```
...
==> default: Installing WordPress develop...
==> default: sh: 1:
==> default: /usr/local/rvm/bin/catchmail: not found
==> default: Running npm install for the first time, this may take several minutes...
==> default: Initializing grunt in WordPress develop... This may take a few moments.
==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?
==> default: >> Local Npm module "grunt-contrib-imagemin" not found. Is it installed?
==> default: >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
==> default: >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
==> default: >> Local Npm module "grunt-sass" not found. Is it installed?
==> default: Warning: Task "uglify:core" not found. Use --force to continue.
==> default: Aborted due to warnings.
==> default: Downloading phpMyAdmin 4.2.13.1...
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress-trunk.dev from /srv/www/vvv-hosts
==> default:  * Added src.wordpress-develop.dev from /srv/www/vvv-hosts
==> default:  * Added build.wordpress-develop.dev from /srv/www/vvv-hosts
==> default: -----------------------------
==> default: Provisioning complete in 1130 seconds
==> default: External network connection established, packages up to date.
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 21534
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.

C:\VMs\vagrant-local>
```

**Comment by franperezgomez** [comment] 2015-07-07 17:44
I get the same red output and i followed all the instructios. I installed Vagrant 1.7.2 VirtualBox 4.3.28 Git 1.9.5 (for SSH conection) & VVV develop at Windows 8

I can access to 192.168.50.4 and I get the links for the local WP sites; however, when I click on them it will not display the page.  I'm searching for a solution but with no result.

**Comment by syllie** [comment] 2015-07-23 22:13
I installed VVV for a first time today and I also ran into the reported issues with grunt on wordpress develop, my output however only showed the error messages in red (as expected).

I am using a Win 7 64 SP1 host, Vagrant 1.7.4 and Virtual Box 5.0.0
I used Git Bash as Administrator (elevated mode) as CLI
I looked at issue #290 but that did not provide further clues.

    ==> default: Installing WordPress develop...
    ==> default: Running npm install for the first time, this may take several minutes...
    ==> default: Initializing grunt in WordPress develop... This may take a few moments.
    ==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-imagemin" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-sass" not found. Is it installed?
    ==> default: Warning: Task "cssmin:core" not found. Use --force to continue.
    ==> default: Aborted due to warnings.
    ==> default: Downloading phpMyAdmin...

I tried to reprovision using `vagrant provision` which did not help

    ==> default: Initializing grunt in WordPress develop... This may take a few moments.
    ==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-imagemin" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
    ==> default: >> Local Npm module "grunt-sass" not found. Is it installed?
    ==> default: Warning: Task "cssmin:core" not found. Use --force to continue.
    ==> default: Aborted due to warnings.

**Comment by gajama** [comment] 2015-07-24 10:22
I was having this problem. A bit of googling produced the following:

https://harvsworld.com/2015/how-to-fix-npm-install-errors-on-vagrant-on-windows-because-the-paths-are-too-long/

Following the instructions to modify the line in the file and then running the provisioner a couple of times seems to have worked - the errors are gone. I didn't have to use the npm install --no-bin-links command.

BUT I did some further digging: the version of vagrant I've got installed in 1.7.2 and in 1.7.3 there was a different fix for just this issue; however it caused regressions and has been removed in the current release 1.7.4 (see https://github.com/mitchellh/vagrant/search?utf8=%E2%9C%93&q=gh-5933) so the fix outlined above may also cause issues.

I'm installing Vagrant 1.7.4 now and will report back whether this still has the same problem for me.

**Comment by joecue** [comment] 2015-08-18 13:25
I am experiencing this issue as well.  I've tried the above suggestions but I'm still having issues.  While trying to apply the fixes mentioned above or removing the comments from the line of code that is mentioned at https://github.com/mitchellh/vagrant/search?utf8=%E2%9C%93&q=gh-5933 Vagrant will not startup.

I'm running Windows 7 64bit with Vagrant 1.7.4 and VirtualBox 5 installed.  

I'm able to manually add  the 6 node modules back in after provisioning via the command line.  Once I got the VV Wizard running and was able to add an extra development site for a project, I lost the node modules for the WordPress-Development site and had to re-install via the command line again to get Grunt working over there. 

As long as I don't provision another site I'll be ok.

**Comment by mgratch** [comment] 2015-08-18 16:36
Same problem as the OP on VBox 4.3.30 r101610 vagrant 1.7.2 (though I have tried 1.7.3 and 1.7.4 with the same results, as well as VBox 5.) The even odder part is that I had been using VVV since October 2014, I have installed it in many places on different types of PC's and I never received this error until recently with a fresh install on the same laptop I had been using since the beginning.

I have even tried reverting back to the stable release with the same result.  I am baffled.

**Comment by gtamborero** [comment] 2016-05-08 17:31
Hi there! Same problem for me (==> default: >> Local Npm module "grunt-browserify" not found. Is it installed?). 

Maybe the fixes of vagrant wasn't so good as gajama said ;) I'm running vagrant 1.8.1 with virtualbox 5.0.16 over windows 7. Thanks!

**Comment by jeremyfelt** [comment] 2016-08-21 00:36
It would be helpful to track down steps to reproduce. I'm not sure at this point if there's anything we can do in VVV or if this is a Vagrant/VB issue.

There's also a chance that the recent changes to `wordpress-develop` provisioning helps this as the initial `npm install` is done in a temporary directory before it is moved to a mapped directory.

**Comment by tomjn** [comment] 2017-11-08 19:45
I'm going to close this one out, the grunt issue got fixed almost a year ago

**Closed by tomjn** 2017-11-08 19:45 UTC
Labels: bug, needs:reproduce
