### ISSUE TITLE
VVV backups (DBs, WWW files, and some configs) don't work well with latest commit in develop branch

### ISSUE THREAD

**Issue by guyromellemagayano** [Varying-Vagrant-Vagrants/VVV#1509] opened 2018-05-15 02:49 UTC
Hi @LoreleiAurora @tomjn . Another issue for today. Just few hours ago, I decided to reinstall VVV with the latest commit in the `develop` branch. Before doing so, I deleted the `/.vagrant.d` folder in my Mac's `/home` folder, delete the vagrant box `vvv` folder. So it was a total clean slate - for sure.

Then after cloning, provisioning and some troubleshooting, I decided to put all my previous files from the databases, to the web files and the original configs like the `vvv-custom.yml` and `init-custom.sql`.

After all the setups and some headaches along the way, everything seemed working like the link [http://vvv.test/](url) and its tools such as PHPMyAdmin, Memcached, and the rest. However when I tried to access all of my sites _(there are at least 8 of them)_, their links will redirect to the same [http://vvv.test/](url) link.

I'm really into solving these things because my current project relies on this setup. Thanks in advance.

**Comment by guyromellemagayano** [comment] 2018-05-15 02:52
[UPDATE] The mailcatcher does not load when I tried to access it via [http://vvv.test:1080/](url). I might need it in my next projects.

**Comment by tomjn** [comment] 2018-05-15 02:57
Nothing has been changed with mailcatcher in recent commits. We've had a
lot of reports of it being quite unreliable in functionality or just
installation over the last year. If you can take the time we'd love if
somebody can contribute to replacing it with mailhog

**Comment by guyromellemagayano** [comment] 2018-05-15 03:14
Will try to send a PR if I have the time to work on it. But on the other hand, what can you say about my main issue about reinstalling all my previous sites to the latest version of VVV? Is there something I missed or misconfigured or both? I can't access all my sites as of right now.

**Comment by tomjn** [comment] 2018-05-15 13:26
As an aside:

> Before doing so, I deleted the /.vagrant.d folder in my Mac's /home folder, delete the vagrant box vvv folder. So it was a total clean slate - for sure.

I've never had to delete that folder, if anything it's Virtualbox that needs the cleanup to destroy the VM sometimes

**Comment by tomjn** [comment] 2018-05-15 13:27
> their links will redirect to the same http://vvv.test/ link.

Provisioning failed somewhere, `vvv.test` is the default site, this is probably caused by the issue being worked on in #1510 and fixed by #1512

**Closed** 2018-05-16 10:10 UTC
Labels: support
