### ISSUE TITLE
VVV performance

### ISSUE THREAD

**Issue by irishetcher** [Varying-Vagrant-Vagrants/VVV#2046] opened 2020-01-15 20:45 UTC
Hi, 

I have been using VVV for about a year ago and when I set it up WordPress ran really fast. Now I notice that it takes ages between page loads and often WordPress reports that things have gone offline. 

Is there any troubleshooting steps I should take?

**Comment by Mte90** [comment] 2020-01-15 22:23
Uhm this can depends from a lot of factor. Like the virtualbox are you using, the VVV version too, the php version you are using in the website and so on.

**Comment by tomjn** [comment] 2020-01-15 22:33
> I have been using VVV for about a year ago and when I set it up WordPress ran really fast. Now I notice that it takes ages between page loads

A fresh WP install will always be faster than what you currently have regardless of wether it's a VVV install or a server in a data centre, the fundamental problem here is that performance is ane extremely vague and nebulous term. It could be that your site is doing far too many things on each page load, or that your template makes extremely expensive queries, such as `NOT IN` style queries, retrieving unlimited posts, searching for posts via their post meta values, etc

So, you need to identify what is slow, e.g. your site has 100 queries on a page load, or a brand new WP install with default themes and plugins takes 30 seconds to load, measurable things.

There's also the real possibility that your computer is just getting slower. Antivirus, disk space, available RAM, etc

Identifying what's making a WP install slow shouldn't require VVV specific knowledge, and requires all the same tools that you would use to test the speed of a site on Siteground, or in MAMP or XAMP. Personally, I'd recommend using the Query Monitor plugin

>  and often WordPress reports that things have gone offline.

This is different than performance, can  you get as much details and information as you can about this? What exactly went offline? Error messages? White screens of death? PHP error logs? Did it timeout? This could be anything from your browser trying to load a VVV site when the OS shutdown the VM because your battery went under 5%, or something seriously wrong happening

I also noticed that you deleted the questions in the issue template rather than filling them out. For  all we know you're using VVV 1.x from 2014 on Windows 2000.

As performance is a very vague term, I'm going to close this out. We've had issues opened in the past by 2 people, for which nobody was able to reproduce the issues, and they were unable to identify what was slow, and made comparisons to the same sites hosted in data centres sharing high end Intel Xeons that are rarely found in consumer hardware.

If you encounter an issue where something has gone offline, gather details as to what went offline, and open an issue ( with all the important information asked for in the issue template )

If you encounter a specific issue, such as database queries running very slowly, file access times being super slow, etc, open an issue with the details, timings and instructions on how to reproduce would be super helpful.

I'd also recommend upgrading VirtualBox, and Vagrant, as well as updating VVV itself ( always update VVV! )

**Closed by tomjn** 2020-01-15 22:33 UTC
Labels: question, support

**Comment by irishetcher** [comment] 2020-01-16 07:58
Ok, That all makes sense, I will provision a base install of wordpress and see if it behaves the same or better.
