### ISSUE TITLE
Can't access http://vvv.test even after running vagrant up and installing plugins

### ISSUE THREAD

**Issue by Dillweed5446** [Varying-Vagrant-Vagrants/VVV#1977] opened 2019-10-19 23:33 UTC
Hi, I've installed vagrant, run the vagrant up setup, and installed the necessary plugin (hostsupdater plugin).  Even after doing all of this, I'm unable to access http://vvv.test.  I'm getting the error "vvv.test’s server IP address could not be found" from my browser when I try to open the page.  This is my first time running this program.

**Comment by tomjn** [comment] 2019-10-19 23:38
Hey! The issue template asks some important questions such as which operating system you're using, can you tell us about your system? Which operating system are you using? Is it a Mac, Windows, or other? Which version? What kind of terminal/command prompt did you run it in?

**Comment by Dillweed5446** [comment] 2019-10-19 23:45
Yes, I apologize.  I'm using the Windows 10 pro operating system version 1903. I'm running "vagrant up" in the windows command prompt that came with the system.  I have downloaded the most recent version of Oracle VM VirtualBox as well because the instructions from WordPress.org suggested that I needed both VirtualBox and Vagrant.

**Comment by tomjn** [comment] 2019-10-19 23:47
When you ran the command prompt, did you run it, or did you run it as an administrator? It **must** be an administrator elevated priviledges command prompt, if it's an ordinary command prompt there'll be no way for it to modify the hosts file

**Comment by Dillweed5446** [comment] 2019-10-20 00:26
Ok, I hadn't run it in the administrator elevated privileged command prompt previously, but even after doing so, I'm having the same issue.  I've seen elsewhere that people had issue with the host file not being updated after running the install (#1458), so maybe the host file isn't being updated?

**Comment by tomjn** [comment] 2019-10-20 00:29
I couldn’t say if that’s the cause, my understanding was that that was a
while ago and the bug was reported to the hosts updated people.

If this is still an issue then you need to update the issue over at
hostsupdater that was tracking that as it isn’t a VVV issue.

But in the mean time, can you share the output from your command prompt?
It’ll take a lot of the guess work out to see thef ull output a vagrant
halt and a vagrant up.

**Comment by Dillweed5446** [comment] 2019-10-20 00:32
C:\WINDOWS\system32>vagrant init
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

C:\WINDOWS\system32>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file C:/WINDOWS/system32/base

C:\WINDOWS\system32>vagrant init -f hashicorp/bionic64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

C:\WINDOWS\system32>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Setting the name of the VM: System32_default_1571529194351_89773
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Mounting shared folders...
    default: /vagrant => C:/Windows/System32

C:\WINDOWS\system32>vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (1.1.1.160)'!

**Comment by tomjn** [comment] 2019-10-20 00:52
Oh my, what you're doing there has nothing to do with VVV

1. You need to be in the folder you downloaded VVV to, but you're in the `C:\WINDOWS\system32`, you shouldn't be running any commands in that folder, use `cd` to change into the directory you downloaded VVV into
2. `vagrant init` is not in any of the VVV docs, you should never be running this command if your goal is to set up VVV.  [vagrant init is for starting a new vagrantfile from scratch](https://www.vagrantup.com/docs/cli/init.html), it's an advanced vagrant command. You would only use this if you decided to create a rival to VVV from scratch
3. You can't visit `vvv.test` because you're not running `vagrant up` on a VVV Virtual Machine, but rather you're running it on a blank vagrant file with a default virtual machine. There are no host names or WordPress sites to provision, hence why vvv.test doesn't work in the browser. It's not that it doesn't work, it's that it isn't there to begin with.

I'm quite alarmed that you ran `vagrant init`, can you indicate where you were told to do this? I'd like to chase it up and make sure it doesn't happen again

So:

1. install virtualbox - _this creates and runs virtual machines_
2. install vagrant - _this automates installing a virtual machine, running install scripts, etc_
3. download VVV and put it in a folder - _this is a vagrant project that sets up webservers and WordPress_
4. open a command prompt with admin priviledges
5. `cd` into that folder in the command prompt and run `vagrant up`
6. wait until it finishes

VVV puts a great big VVV logo at the beginning and end of the commands, for example, running `vagrant up` with VVV should give you something like this:

<img width="554" alt="Screenshot 2019-10-20 at 01 46 59" src="https://user-images.githubusercontent.com/58855/67153105-8e429a80-f2db-11e9-9562-b16a7f0cc6ca.png">

With a teddy bear and a VVV logo at the end:

<img width="763" alt="Screenshot 2019-10-20 at 01 47 30" src="https://user-images.githubusercontent.com/58855/67153111-9bf82000-f2db-11e9-9047-707b05e7b801.png">

You might not get the colours on Windows though.

Once you have that, all you have to do to turn it on is go to the VVV folder in an admin command prompt and run `vagrant up`

---

Before you do this though, I'd suggest cleaning up from your first attempt:

1. in `C:\WINDOWS\system32` you'll want to run `vagrant destroy` to get rid of the empty generic linux VM you created
2. Remove `vagrantfile` from that folder
3. Double check in the VirtualBox GUI if there are any other stray VMs you created

**Comment by Dillweed5446** [comment] 2019-10-20 01:39
Ok, thank you.  I was really feeling my way through fairly blindly today.  The command prompt recommended that I run vagrant init, and the example that I sent to you was from "https://www.vagrantup.com/docs/cli/init.html" which i actually did a little later. 

install virtualbox - this creates and runs virtual machines - Done
install vagrant - this automates installing a virtual machine, running install scripts, etc - Done
download VVV and put it in a folder - this is a vagrant project that sets up webservers and WordPress - done
open a command prompt with admin priviledges - done
cd into that folder in the command prompt and run vagrant up - I've tried to input the file path but it doesn't seem to be working.  
-side note:  I just noticed that it is coming up in virtualbox now, but I am getting a prompt for a username and password.  Should I just ignore this and continue in the windows command prompt?

**Comment by tomjn** [comment] 2019-10-20 10:59
Hmm it’s a little difficult to imagine what’s happening at your end

When you open a command prompt it will always be in the same place, but an
easy way to move to a folder is to type “cd “ then drag and drop the folder
on to the command prompt.

I’m not sure what’s prompting you for a username and password though, we’re
you trying to start VVV or where you trying to cleanup previous efforts?

**Comment by Dillweed5446** [comment] 2019-10-20 19:23
I've used "cd\" to go to the top directory (takes me to "C:\>"), and "cd.." to go up one directory (takes me to "C:\Windows>").  Neither one will allow me to drag and drop or copy and paste the file into the command prompt.

I was prompted for a username and password by Virtualbox.  Not sure exactly when it happened, but it was at some point during my other efforts.  Virtualbox hadn't had anything loaded into it at all to begin with, then after all of my failed efforts in the command prompt, I noticed that virtualbox had a file loaded into it and was asking for the username and password.  I don't know if it's at all related to my other efforts or not.

**Comment by tomjn** [comment] 2019-10-20 20:14
I don't know why VirtualBox would ask you for a username or password, you don't need VirtualBox open during this. Also, can you be more specific about what you were doing when it asked for a user/pass, and how it asked you? E.g. is it asking you on the command prompt? What did you do? Be as specific as possible, and include full output so we can see what you did to get those results

**Comment by Mte90** [comment] 2019-10-21 13:21
VVV need a command `vagrant up` executed inside the terminal from the folder when VVV is available or will not work.
You need to do `cd C:/Documents/whatever/is/the/folder` and later run vagrant up.

Maybe virtualbox has issue because is executed but don't know what to do and maybe also because you are executing in a system folder (system32) that shouldn't be touched.

**Comment by tomjn** [comment] 2019-12-05 12:31
It's been a while so I'm closing this out, feel free to reopen it if you get the chance to look into it again

**Closed by tomjn** 2019-12-05 12:31 UTC
Labels: question, support
