### ISSUE TITLE
Do not (only) create machine name from folder name

### ISSUE THREAD

**Issue by kraftner** [Varying-Vagrant-Vagrants/VVV#865] opened 2016-04-05 12:13 UTC
I have issues with the change in https://github.com/Varying-Vagrant-Vagrants/VVV/commit/7fa397656b9118bc4f8028c26bd6263e3100ce8f
I always have the vagrant machine in a folder with the same name for all projects. So now Virtual Box complains that the machine already exists and refuses to `vagrant up`.

For now I fixed it by putting this in my `Customfile`

```
config.vm.provider :virtualbox do |v|
  v.name = "project name"
end

```

But couldn't we append something like a hash of the full path or alike to the name?

**Comment by grappler** [comment] 2017-01-08 20:55
Strange my vvv install is always named `default` instead of the folder name.

**Comment by jeremyfelt** [comment] 2017-03-05 01:27
Thanks for opening this issue, I'm going to close it as a duplicate of #848 which is just slightly older. :)

**Closed by jeremyfelt** 2017-03-05 01:27 UTC
