### ISSUE TITLE
Cannot load the dashboard 

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2564] opened 2021-12-21 14:58 UTC
I can no longer load `vvv.test`  _vvv.test took too long to respond._
I tried restarting my laptop and switching browsers. 
Windows 10 pro 64 bit

But all my sites load properly.  I need the dashboard in order to access phpmyadmin. 

I followed the _fresh start_ instructions: https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/  but still cannot load the dashboard. .

[This is the log](https://gist.github.com/shanebp/4791673f517456c5962a84f9af336549).

[This is the config.yml](https://gist.github.com/shanebp/fb5493aa50a139f4dc5bfe39a532f115)

**Comment by tomjn** [comment] 2021-12-21 15:08
```
==> default: [vagrant-hostsupdater] Checking for host entries
```

Please eliminate this vagrant plugin with extreme prejudice. Apply the fire of a thousand suns, eradicate it.

Do not keep it just in case, do not leave it installed to avoid breaking things, get rid of it. Never use it again

**Comment by tomjn** [comment] 2021-12-21 15:13
the log suggests that because you have 2 hosts plugins installed (one of which is known to have major reliability issues on Windows), both are adding the hosts to the hosts file.

Purge all traces of the hostsupdater plugin. Be ruthless about it. Excise it from all your documentation, treat it with utter contempt.

**Comment by tomjn** [comment] 2021-12-21 15:14
When you're done, reprovision. It may be necessary to manually open the hosts file and remove the offending lines, VVV will re-add what it needs on reprovision.

**Comment by shanebp** [comment] 2021-12-21 15:47
Still cannot load dashboard.

```
c:\vagrant-local>vagrant plugin uninstall vagrant-hostsupdater
Uninstalling the 'vagrant-hostsupdater' plugin...
Successfully uninstalled vagrant-hostsupdater-1.2.4

c:\vagrant-local>vagrant plugin list
vagrant-goodhosts (1.1.1, global)
  - Version Constraint: > 0
```

You said there were 2 hostsupdater plugins installed. Perhaps I've only deleted one? If so, how to delete the other one. 

The hosts file:  
```
127.0.0.1 localhost
::1 localhost
```

[New provision log](https://gist.github.com/shanebp/4791673f517456c5962a84f9af336549)

**Comment by tomjn** [comment] 2021-12-21 21:15
Can you re-run with the `--local` flag:

```sh
vagrant plugin list --local
```

> You said there were 2 hostsupdater plugins installed. Perhaps I've only deleted one? If so, how to delete the other one.

You should have goodhosts installed, which the output shows

> The hosts file:

There should be entries for vvv.test etc but if that is your entire hosts file then this explains the issue. Either goodhosts is failing to add the entries or something is undoing the change and putting the hosts file back to how it was.

**Comment by tomjn** [comment] 2021-12-21 21:19
I noticed a webgrind install issue that's unrelated to this in your log output (composer 2 compatibility), I've made a commit to fix that

**Comment by shanebp** [comment] 2021-12-21 21:31
c:\vagrant-local>vagrant plugin list --local
vagrant-goodhosts (1.0.15, local)

That was all the hosts file content. 
If I manually add vvv.test to the hosts file, what is the syntax?

**Comment by tomjn** [comment] 2021-12-21 21:45
Oooph, 1.0.15 could be updated, can you `vagrant plugin update --local`?

> If I manually add vvv.test to the hosts file, what is the syntax?

same as any other hosts file, start a line with an IP then list the domain names afterwards.

Of note, if you've ever installed iTunes or a zeroconf client, `vvv.local` will be available. Try updated goodhosts first though then reprovision with `vagrant up --provision`, the latest is v1.1.1/1.1.2

**Comment by shanebp** [comment] 2021-12-21 22:00
Does not seem to update goodhosts
```
c:\vagrant-local>vagrant plugin list --local
vagrant-goodhosts (1.0.15, local)

c:\vagrant-local>vagrant plugin update --local
Updating installed plugins...
Fetching os-1.1.4.gem
Fetching vagrant-goodhosts-1.1.1.gem
Successfully uninstalled os-1.1.4
Successfully uninstalled vagrant-goodhosts-1.1.1
All plugins are up to date.

c:\vagrant-local>vagrant plugin list --local
vagrant-goodhosts (1.0.15, local)
```

**Comment by shanebp** [comment] 2021-12-21 22:41
The dashboard ( and phpmyadmin ) loads if I manually edit the hosts file:

```
127.0.0.1 localhost
::1 localhost
192.168.56.4 vvv.test
```

There are no entries for all my sites - but they load anyway.

**Comment by tomjn** [comment] 2021-12-21 23:59
can you remove goodhosts complete both with `--local` and without it, then re-add it?

```sh
vagrant plugin remove vagrant-goodhosts
vagrant plugin remove vagrant-goodhosts --local
vagrant plugin install --local
```

**Comment by shanebp** [comment] 2021-12-22 01:51
Thanks for those commands.  Goodhosts 1.1.1 is now installed. 
```
c:\vagrant-local>vagrant plugin uninstall vagrant-goodhosts
Uninstalling the 'vagrant-goodhosts' plugin...

c:\vagrant-local>vagrant plugin uninstall vagrant-goodhosts --local
Uninstalling the 'vagrant-goodhosts' plugin...

c:\vagrant-local>vagrant plugin install --local
Vagrant will now install the following plugins to the local project
which have been defined in current Vagrantfile:

  vagrant-goodhosts (> 0)

Press ctrl-c to cancel...
Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Fetching os-1.1.4.gem
Fetching vagrant-goodhosts-1.1.1.gem
Installed the plugin 'vagrant-goodhosts (1.1.1)'!
```
But I still need to manually add vvv.test to the hosts file. 

Even without manually adding it, the entry is found on shutdown, 
```
==> default: Attempting graceful shutdown of VM...
==> default: [vagrant-goodhosts] - found entry for: 192.168.56.4 vvv.test
```

**Comment by tomjn** [comment] 2021-12-22 02:43
@shanebp then there is nothing more that can be done from the VVV end, it's clear that VVV has told the plugin what to do from the log.

At this point, you should open an issue on the goodhosts plugin github, however it's very likely that this is an issue with your system.

In the past people have reported issues like this that mysteriously vanished when their VPN was disabled, or were using overbearing antivirus/firewall security software. One person had a tool open such as gasmask. Others opened the terminal normally instead of using administrative prompts.

I'm closing this out as there is nothing more to do and it is clear that the issue is not with VVV itself

**Closed by tomjn** 2021-12-22 02:43 UTC
Labels: type:question, type:support
