### ISSUE TITLE
Upgrade ubuntu to 16.04 LTS

### ISSUE THREAD

**Issue by halvardos** [Varying-Vagrant-Vagrants/VVV#954] opened 2016-08-11 09:11 UTC
Hi,

Thank you for creating VVV, it has saved me tremendous amounts of work!

Is there a reason why upgrading the base image for ubuntu to 16.04 has not been discussed?
Would it make the upgrading of other packages easier to maintain to bump the core system version?

**Comment by LoreleiAurora** [comment] 2016-08-11 21:32
I would love this to happen but when trying to do this `vagrant up` fails at creating network interfaces as sudo fails.

Sudo fails because of [this issue](https://bugs.launchpad.net/cloud-images/+bug/1561250) filed in launchpad. As the hostname is not set sudo gives the wrong exit status so Vagrant assumes the command failed even when it succeeded.

Therefore until this issue is fixed the official Ubuntu Xenial Vagrant box cannot be used.

**Comment by Jeger** [comment] 2016-08-12 09:08
aaah, that makes sense.

Thank you for the quick answer.
I started using the provisioning files from this project as a base for a docker container to get in line with the rest of our organisation but still keep my development environment the same.

And they use a more recent distro as base, so thats why I'm asking :)

If anyone else is interested i could share my docker implementation, it has some limitations atm. but generally works the same.

**Comment by ivankruchkoff** [comment] 2016-09-01 04:42
Both issues have a confirmed fix in place.

**Comment by LoreleiAurora** [comment] 2016-09-08 14:34
As the issues were changed from Fix Commited to Fix released on 2016-09-06 and was included in box release `20160907` i will start working on this at the weekend.

**Comment by LoreleiAurora** [comment] 2016-09-13 15:01
There is yet another bug to get in our way 😢
[xenial64 image (20160907.1.0) has a broken (empty) /etc/resolv.conf](https://bugs.launchpad.net/ubuntu/xenial/+source/livecd-rootfs/+bug/1621393)
The fix is committed but not yet in release.

**Comment by jeremyfelt** [comment] 2016-12-13 06:32
Chatted with @LoreleiAurora a bit about this today. Let's keep an eye on the Xenial image over the next 6 months. Trusty is doing fine with the configuration that we have, and moving to a new box will definitely be a breaking change, so let's be sure it's working well with VirtualBox, VMWare Fusion, Parallels, etc.. before upgrading.

**Comment by wturrell** [comment] 2017-03-08 11:51
It *is* possible to update your existing box manually if you want/need 16.04.

Briefly, the approach I took was:
- take a snapshot for backup
- upgrade Ubuntu using `do-release-upgrade`
- machine then hung on reboot, [eventually figured out](http://askubuntu.com/questions/890558/upgraded-ubuntu-from-14-04-to-16-04-hangs-on-boot-can-use-recovery-mode-but-un) the Grub fix I needed
- needed to upgrade one or two things e.g. mysql client/server. I was already using the ondrej-php packages to get PHP 7.1. Also took opportunity to clear out packages I no longer needed.  Didn't need to reconfigure any sites, the shared directories etc.

**Comment by half2me** [comment] 2017-04-11 14:59
Any update on this?

**Comment by DArcMattr** [comment] 2017-06-08 23:34
I have a WIP fork for a base box upgrade to Ubuntu 16.04. The official Ubuntu box is not acceptable in its current form, as it doesn't have a default 'vagrant' user, so I had to go with an alternative. 

I changed external apt sources where appropriate, and the box comes up with some wonkiness: the first `vagrant up` appeared to stall on the Grunt-CLI installation step, and rvm produced some errors; it finished in time, and a second go at running the provision steps on the box I already had ran without a snag. I'm not sure if it's due to network issues, or something else I haven't accounted for. 

https://github.com/DArcMattr/VVV/tree/current_lts

**Comment by smcjones** [comment] 2017-07-11 21:16
As far as I can tell, Ubuntu seems incredibly resistant to ever producing something that will be vagrant ready because it doesn't match Ubuntu's self-imposed standardization requirements. 

At some point before 14.04 EOL, VVV will hopefully make an upgrade. Ideally it would be to the official box, but bento/ubuntu16.04 is a user-driven and very stable build. I use it in other vagrant boxes I have and it works well.

https://app.vagrantup.com/bento/boxes/ubuntu-16.04

**Comment by dingo-d** [comment] 2017-12-11 08:44
I tried upgrading to 16.04.3 LTS with `do-release-upgrade` within the vagrant ssh, and it broke the vagrant. So you should probably add some kind of warning not to do that :D 

On the bright side I reordered my folders nicely this time, so at least there is something gained xD

**Comment by dingo-d** [comment] 2017-12-11 19:14
I had the backup of the databases and config files, and all the client work is on repositories, so nothing lost ;) 

As for upgrading, I didn't think of changing the ubuntu in `Vagrantfile` (tbh not sure what to change it from `ubuntu/trusty64` to ... ?).

**Comment by tomjn** [comment] 2017-12-11 19:16
https://app.vagrantup.com/ubuntu/boxes/xenial64

**Comment by DArcMattr** [comment] 2018-02-15 17:28
Ubuntu consistently produces vagrant boxes that are not ready to use in a vagrant environment. Other users have had to step forward to pack their own boxes for general use. 

And where we are, 2 months away from the next scheduled LTS release, and the VVV project has not yet updated to the current one. I get that project stability is important, but also being able to use the most recent set of tools available, something an ancient LTS distro has to be finagled into supporting.

**Comment by tomjn** [comment] 2018-02-15 18:05
@DArcMattr if it was that simple VVV would have updated a long time ago.

E.g. I could go and change the box needed today.. then have a lot of people complaining about lost MySQL databases tomorrow

If you can provide a way to update the base box automatically without destroying existing users setups let us know. Or if you know a way to do it but only for new users so it happens automatically when `vagrant destroy;vagrant up --provision` happens that also works

**Comment by DArcMattr** [comment] 2018-02-15 19:10
The last time there was a transition to new LTS versions, a destroy & re-provision were necessary, but back then, the MySQL DB file was stored outside the vagrant box.

**Comment by tomjn** [comment] 2018-02-16 00:20
Do you know if it's possible to check the current box used in the vagrant file?

**Comment by tomjn** [comment] 2018-05-08 18:40
#1469 should make this ticket obsolete by pre-building VVV boxes, VVV updates would be:

```
git pull
vagrant box update
```

**Closed** 2018-05-08 21:07 UTC
Labels: feature, needs:patch, needs:testing
