### ISSUE TITLE
/etc/postfix/main.cf: No such file or directory

### ISSUE THREAD

**Issue by fabianhenzler** [Varying-Vagrant-Vagrants/VVV#683] opened 2015-07-02 12:28 UTC
`==> default: /tmp/vagrant-shell: line 143: /etc/postfix/main.cf: No such file or directory`

[Screenshot](https://db.tt/fbFcShn0)

**Comment by vohof** [comment] 2015-07-17 23:25
```
default: /tmp/vagrant-shell: line 138: /etc/postfix/main.cf: No such file or directory
```

**Comment by soumojitghosh** [comment] 2015-07-22 08:39
Hey, try this:
cd /etc/postfix/
ls 
** If main.cf is not present, you need to reinstall postfix
Its better if you remove the earlier installation and do a,
sudo apt-get install postfix

This will resolve your problem.

**Comment by jeremyfelt** [comment] 2015-07-22 15:49
I've been seeing this error during provisioning as well, but haven't had a chance to look at it. Is postfix actually broken or is this an install error?

**Comment by soumojitghosh** [comment] 2015-07-22 17:57
Hey, actually I was hitting the same error. Initially I installed the whole package mailutils, then I found out that this main.cf is not present. Then I reinstalled postfix alone and the file was present where it ought to be.

Try re-installing once and let me know.

**Comment by ntwb** [comment] 2016-04-22 05:31
It looks like its part of the Postfix install: 
• https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L205
```sh
==> default:  * g++ [not installed]
==> default:  * nodejs [not installed]
==> default:  * libsqlite3-dev [not installed]
==> default: /tmp/vagrant-shell: line 205: /etc/postfix/main.cf: No such file or directory
==> default: Linked custom apt sources
==> default: Applying Nginx signing key...
==> default: OK
```

**Comment by jeremyfelt** [comment] 2016-08-16 18:19
I'm going to close this as a duplicate of #628.

**Closed by jeremyfelt** 2016-08-16 18:19 UTC
