### ISSUE TITLE
Could not connect to ppa.launchpad.net:80

### ISSUE THREAD

**Issue by cueqzapper** [Varying-Vagrant-Vagrants/VVV#2297] opened 2020-11-08 15:54 UTC
On vagrant up I get the following error:

```
default: Err:97 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.1-msgpack amd64 2.1.1+0.5.7-2+ubuntu18.04.1+deb.sury.org+4
    default:   Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out [IP: 91.189.95.83 80]
    default: Err:98 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.1-memcached amd64 3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:99 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-igbinary amd64 3.1.6+2.0.8-2+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:100 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-msgpack amd64 2.1.1+0.5.7-2+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:101 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-memcached amd64 3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:102 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-igbinary amd64 3.1.6+2.0.8-2+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:103 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-msgpack amd64 2.1.1+0.5.7-2+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:104 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-memcached amd64 3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:105 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-memcached amd64 3.1.5+2.2.0-4+ubuntu18.04.1+deb.sury.org+4
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:106 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php8.0-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:107 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.4-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:108 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.3-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:109 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:110 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.1-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:111 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:112 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:113 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-xdebug amd64 2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:114 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php8.0-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:115 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.4-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:116 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.3-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:117 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:118 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.1-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:119 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:120 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:121 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-yaml amd64 2.2.0~b2+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:122 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.4-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:123 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.3-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:124 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:125 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.1-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:126 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.0-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:127 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php5.6-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:128 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-ssh2 amd64 1.2+0.13-3+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:129 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libgd3 amd64 2.3.0-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:130 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libargon2-1 amd64 0~20190702-0.1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:131 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libpcre16-3 amd64 2:8.44-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:132 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libpcre32-3 amd64 2:8.44-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:133 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libpcrecpp0v5 amd64 2:8.44-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:134 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libpcre3-dev amd64 2:8.44-2+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:135 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libsodium23 amd64 1.0.18-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:136 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libssl-dev amd64 1.1.1g-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:137 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libzip4 amd64 1.7.3-1+ubuntu18.04.1+deb.sury.org+2
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:138 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-common amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:139 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-json amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:140 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-opcache amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:141 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-readline amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:142 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-cli amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:143 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-xml amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:144 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php-pear all 1:1.10.12+submodules+notgz-1+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:145 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-bcmath amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:146 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-curl amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:147 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-dev amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:148 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-fpm amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:149 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-gd amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:150 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-imap amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:151 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-mbstring amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:152 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-mysql amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:153 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-soap amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
    default: Err:154 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-zip amd64 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
    default:   Unable to connect to ppa.launchpad.net:http: [IP: 91.189.95.83 80]
```
I tried it a dozen times. I always get the error above. My VVV version:

(HEAD -> stable, tag: 3.4.1, origin/stable, origin/master)

**Comment by tomjn** [comment] 2020-11-08 16:00
Are you able to load that domain? VVV needs to be able to connect to that
domain.

At this point it isn’t a provisioning issue but a generic network issue. It
may be that you have a truly awful internet provider, that someone on your
WiFi is downloading large amounts of data at the same time, that someone at
the launchpad data centre tripped on a network cable, etc

Eitherway the problem is not at our end and there is nothing I can do from
my end that will magically fix this.

Try retrying after a period of time, or switching to a different internet
connection

**Comment by cueqzapper** [comment] 2020-11-08 16:09
I am trying it the whole day. When I ping the domain I get an anwer. I am using vvv since 2 years, and it always worked and I haven't changed a thing. So there seems to be something going on that is more specific. I tried it for like 10 times, even with different internet connections, but it always fails with the files I mentioned above.

**Comment by cueqzapper** [comment] 2020-11-08 16:24
When I ping ppa.launchpad.net from within the vagrant vm I get an answer 100% of the time.

**Comment by cueqzapper** [comment] 2020-11-08 16:28
Can you give me the exact command that fails, so that I can try recreating the issue from within the VM?

**Comment by cueqzapper** [comment] 2020-11-08 16:54
I tried vagrant up on yet another computer, and I have the same exact error. Did you try to make a fresh vagrant installation? Pretty sure you will have the same problem.

**Comment by cueqzapper** [comment] 2020-11-08 20:38
After trying 50x it worked. Nice...

**Comment by tomjn** [comment] 2020-11-08 21:24
A ping isn't quite the same as downloading a file. We have no control over `ppa.launchpad.net`, and we don't maintain it, we just use it, just like we don't run/maintain GitHub. You would likely get the same issues trying to install those packages in Ubuntu after a DVD install, or any other method, it isn't a VVV specific issue.

Consider running standard network tests between your machine and `ppa.launchpad.net` to confirm there are no bottlenecks or issues on the path between the two.

> Can you give me the exact command that fails, so that I can try recreating the issue from within the VM?

`apt-get install`, it's just a generic `apt` command. We add parameters too try and make it less prone to failure, such as telling it not to run in interactive mode so it doesn't wait for user input, to install missing or broken packages etc

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/f9e04da83083a815f14f0cf3991e37c994fcb105/provision/provision-helpers.sh#L293

Recreating it inside the VM should be as simple as:

```shell
sudo apt-get update
sudo apt-get install ..........packagenames.......
```

**Comment by tomjn** [comment] 2020-11-08 21:26
> Pretty sure you will have the same problem.

As an aside, if this issue was worldwide, the fix would not be at the VVV end. We don't run or maintain launchpad, you would need to take it up with them. If that where the case though then this would be a major worldwide outage, the kind that would appear in tech news outlets.

**Comment by cueqzapper** [comment] 2020-11-09 08:45
I tried installing about 10 of the failing packages from inside the VM and it always worked. 

sudo apt-get install php7.2
sudo apt-get install php7.3
sudo apt-get install php7.4
sudo apt-get install php-ssh2
sudo apt-get install php-yaml
etc..

So it seems like this is not a network issue. I tried it on different computers, with different networks and this issue always persisted, except once, where it run through and I managed to vagrant up on one of my computers. All the others failed like 80x now..

Most likely you are right and it's just an issue with a library that can't get downloaded and I just haven't figured out which one it is. And it's not obvious from the error.

**Comment by tomjn** [comment] 2020-11-09 18:06
**I guarantee you, it is a networking issue** the very description of the error says so. A connection timeout is by definition a networking issue.

I re-provisioned several times and could not reproduce this, but then I have a 1Gbit fibre connection. I also checked launchpad and could not find any reports of downtime. You are the only person I am aware of currently reporting this.

Given that networks are not static things, you can't try it once, have it fail, then try it again an hour later and say it worked that time therefore it isn't.

That would be like saying:

> I tried to drive to town during rush hour but the roads were jammed and I didn't make it within the 30minute time I allowed myself, however, if I drive in to town at 11pm I succeed, therefore it is not a traffic issue, it's an issue with the car you sold me.

Have you tried using a different network? Networking issues don't go away if you use a different computer on the same network. If it can't establish a successful and reliable connection between your computer and `ppa.launchpad.net` then you need to try another route or get in touch with your network provider.

This could be as simple as your network being routed through a proxy or VPN, or misconfigured firewall rules.

In the meantime, there is literally nothing that can be done from the VVV end about this. If you have a practical suggestion I'm all ears, otherwise I can only suggest that you try the `develop` branch, but I very much doubt it will make any difference.

My next steps would be:

 - try again but on a different network, ideally one with a different internet provider
 - confirm that no unwanted network software such as VPNs WAF's Antivirus or proxies are messing with the VM

---

I would also note you have not shared all of the information that was requested in the issue template, such as which operating system and which provider you were using. For all I know you're using an ancient version of MacOS with an old VMWare to run your virtual machine.

You also did not provide a full provisioner log. This issue may not be that actual problem, just the one you managed to identify. This may just be a symptom of an earlier problem that is unknown because you tried to be helpful and share only the part you thought was relevant.

**Comment by cueqzapper** [comment] 2020-11-10 07:35
[provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5515511/provisioner-main.log)

OS: Windows 10 Version 2004 (OS Build 19041.572)
ISP: Salt Mobile SA
Virtual Box: 6.1.10 r138449 (Qt5.6.2)

This is the configuration of the PC where it never worked until now. On the second PC which has almost the same configuration it worked after redoing it for a lot of times. I got the same errors all the time. Because of corona it's not easy for me to find another network where I can connect, since I work from home. But I tried it over VPN and connected to another Salt Mobile Account. Nothing worked.

**Comment by tomjn** [comment] 2020-11-10 09:47
hmmm then there's very little you can do about this other than talking to Salt Mobile-SA or switching provider, and there's a very high chance you'll want to demonstrate it's their fault by using a different ISP to show it's specific to theirs. The irony is if the issue is with a common provider both would show the issue.

Either way you're going to have to try this with another ISP if you want to diagnose this further

**Comment by cueqzapper** [comment] 2020-11-14 07:05
The issue can get revolved through trying multiple times.

**Comment by unfulvio-godaddy** [comment] 2021-04-29 15:45
I have had this issue since VVV introduced this check. I end up editing the provisioner helper file to skip the check. Provisioning the machine never fails, only the check does. It detects false issues too easily. You can edit the `provision/provision-helpers.sh` to skip all the check. It's the only way for me it works consistently unfortunately.

**Comment by Mte90** [comment] 2021-04-29 15:56
So we can think to add a flag to disable the connectivity check in the config file in case. What do you think @tomjn?

**Comment by tomjn** [comment] 2021-04-29 16:02
I'm closing this, as the OP solved the problem by retrying. **This issue is not and has never been about the network checks in `provision-helpers.sh`** This issue was about `apt` failing to retrieve files from the ondrej PPA.

@unfulvio-godaddy we do that check because very shortly after the check we install packages that are on that domain. If the domain is unreachable then the packages can't be installed.

@Mte90 the check is there for a reason, if the check has false positives we should investigate and fix the check. Turning off the check is not an option, I will reject any PR that attempts to do so. We don't fix bugs by _skipping_ steps, we fix them by fixing them.

**Closed by tomjn** 2021-04-29 16:02 UTC

**Comment by unfulvio-godaddy** [comment] 2021-04-29 16:12
@tomjn but the provisioner works normally, so the domain isn't really unreachable and the package _can_ be installed 

wouldn't the error be obvious anyway after the provisioner started configuring the machine?

Otherwise, could we at least introduce an .env or override from `Customfile`? that way at least I don't have to stash/unstash changes to fetch updates from upstream every time

thanks

**Comment by tomjn** [comment] 2021-04-30 11:38
> wouldn't the error be obvious anyway after the provisioner started configuring the machine?

Not quite, in the past it would fail during `apt` but it wouldn't always be obvious to the people involved, and it would be super annoying to have the error half way up the terminal output, especially if provisioning took a while only to fail because a package was missing

Do you know which network test failed? Does the command used succeed when ran manually on the guest and on the host?

If the check is broken we should fix it instead of adding options to disable it, any information you can provide about which checks fail, and the output of manual runs would be helpful

**Comment by tomjn** [comment] 2021-04-30 12:29
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-helpers.sh#L75

```
  if [[ "$(wget --tries=3 --timeout=10 "${url}" -O /dev/null 2>&1 | grep 'connected')" ]]; then
```

@unfulvio-godaddy  The timeout got bumped up to 10s from 5 in the past, but I'd be curious what the output and exit code of `wget --tries=3 --timeout=10 "URL"` is for the hosts that fail for you

**Comment by tomjn** [comment] 2021-04-30 12:33
In previous versions of VVV we did use the https version of the launchpad PPA domain, which did not work, but this was fixed in the most recent versions. I also [made a change to adjust](https://github.com/Varying-Vagrant-Vagrants/VVV/commit/04a53737b9cb96fe44697094473202ba1722e0a3) the default argument values just now but this shouldn't cause the issues you're seeing, and you could tell by inspecting terminal output for the host name being checked

I would need more information to diagnose and mitigate the issue

**Comment by unfulvio-godaddy** [comment] 2021-05-03 07:41
If I try `wget --tries=3 --timeout=10 "ppa.launchpad.net:80" -O /dev/null` from a host machine CLI it will work, but I also I notice that the subdomain will redirect with `302 Found` to `https://launchpad.net` automatically, then will issue a new request and result in `200 OK`. I might be wrong here but I think testing the http response of that URL via wget isn't the same as using apt get. The apt get command will also point to the right ubuntu release within that subdomain, given by the machine context. 

I can only tell you that when the provisioning script runs, it will constantly fail when pinging ppa.launchpad.net using the script function. However, if I comment it out, then it will consistently succeed in provisioning. The same goes if I ssh into the machine and run apt get manually: never fails. How do you explain this?

The other domains it tests are fine, they never fail. 

I am wondering if it's possible instead to issue a command like `apt-cache search` before running apt get install to test if a known repository that should be in launchpad will work, rather than using wget and such. 

Thanks

**Comment by therealwebdude** [comment] 2022-02-05 10:19
Have the same issue - 28 files not downloaded from Ondrj because timeout - took the file list from the provisioner log, used it as a wget input file and wget downloaded all 28 files. Tried 4 times vagrant up --provision no luck.  it seems to be working now on the 5th run ... still going.... oh, looks good now. Yep. its done - so - keep trying, it should happen eventually.

**Comment by tomjn** [comment] 2022-02-05 12:53
There’s a PR for composer changes at the moment that refactors how network
checks are performed, can you try that?

**Comment by tomjn** [comment] 2022-02-05 12:54
Also network checks are a warning not an error in the latest version on
develop

**Comment by therealwebdude** [comment] 2022-02-17 10:36
had to reinstall macos and now have the issue again - on my 10th 'provision' run so far, no luck. I see a launchpad blogpost from the 16th - is that relevant for this issue? https://blog.launchpad.net/ppa/new-domain-names-for-ppas

**Comment by tomjn** [comment] 2022-02-17 11:51
@therealwebdude did you switch to the `develop` branch as I asked?

**Comment by tomjn** [comment] 2022-02-17 11:51
> The old names will carry on working indefinitely – we know they’re embedded in lots of configuration and scripts, and we have no inclination to break all of those – but we recommend moving to the new names where possible. ppa.launchpad.net will remain HTTP-only.

**Comment by tomjn** [comment] 2022-02-17 11:52
To reiterate, this issue has already been fixed on the `develop` branch, switch to the `develop` branch

**Comment by tomjn** [comment] 2022-02-17 11:56
As an aside, provider, operating system, and version of VVV/Vagrant/VirtualBox or whichever provider was chosen is super important for these kinds of issues. So is wether you are using a VPN or not.

**Comment by tomjn** [comment] 2022-02-17 11:57
I'm going to lock this now as the issue was closed. Anybody who has this will be forced to open a new issue with all the required information that wasn't shared here
