### ISSUE TITLE
Backups: Change Default Behaviour

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2197] opened 2020-06-18 13:02 UTC
We should change back ups to only run on `vagrant destroy` by default, and add options to `config/config.yml` to refine when backups should run.

**Comment by Mte90** [comment] 2021-03-16 11:15
It is a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2225

**Closed by Mte90** 2021-03-16 11:15 UTC
Labels: feature, help wanted, mariadb, provisioner:core
