### ISSUE TITLE
Trusty64 box not downloading

### ISSUE THREAD

**Issue by drawcard** [Varying-Vagrant-Vagrants/VVV#1222] opened 2017-06-16 06:35 UTC
## Expected Behavior
Running VVV for the first time, Trusty64 box should download from Hashicorp's servers.

## Current Behavior
It does not appear to be doing this.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
1. Follow [VVV installation instructions](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/docs/en-US/installation.md)
2. Run ```vagrant up```

Error message:
![image](https://user-images.githubusercontent.com/1435638/27214800-62bf758e-52ad-11e7-8b31-592d3d6ed244.png)

I can fetch other boxes from Hashicorp, and other VM's work fine eg Scotch Box and Trellis.
I have also tried this idea: https://github.com/mitchellh/vagrant/issues/7997 which deletes the broken curl package but still doesn't fix the problem.

## Your Environment

* VVV version: Latest from master branch
* Vagrant version: 1.9.5
* VM Provider name: Virtualbox
* VM Provider version: 5.0.x
* Operating System and version: macOS 10.12.1, 24GB disk space free

**Comment by drawcard** [comment] 2017-06-16 06:45
Have also tried:

* ```vagrant box add trusty64 ubuntu/trusty64```
* ```sudo rm -f /opt/vagrant/embedded/bin/curl```

**Comment by drawcard** [comment] 2017-06-17 10:16
For the time being I'm using another trusty64 box:

```sh
$ box add trusty64 https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

$ vagrant box list
...
trusty64            (virtualbox, 0)
```

Edit line 150 of Vagrantfile:
```
 config.vm.box = "trusty64"
```

```sh
vagrant up
```

**Comment by JJJ** [comment] 2017-07-04 16:45
I can't reproduce this on a fresh VVV setup, with latest Vagrant & VirtualBox versions.

FWIW, after installing all optional Vagrant plugins, my box ritual usually looks something like:

```
vagrant destroy
vagrant box update
vagrant box prune
vagrant up
```

**Comment by LoreleiAurora** [comment] 2017-07-04 16:48
@drawcard that is the same box just not downloaded through the hashicorp api.

**Comment by LoreleiAurora** [comment] 2017-07-04 16:52
That is the same box we use just not downloaded through the hashicorp api.

Your install appears to be using `bento/ubuntu-14.04` as opposed to `ubuntu/trusty64`.

Can you please tell me what commit you are on?

**Comment by drawcard** [comment] 2017-07-04 23:22
I am on commit 3b1106b4f0d667ecd258b6758973a000c922696f

**Comment by drawcard** [comment] 2017-07-04 23:23
The commit I'm using from master is 4d1fb6f89f3f982eec3ae72bd58cd48bb1aaa367

**Comment by tomjn** [comment] 2017-11-03 17:29
@drawcard does this still happen with Vagrant 2.0?

**Comment by tomjn** [comment] 2017-11-08 19:36
I'm going to close this for now, if this is still an issue with 2.1 and the latest vagrant+virtualbox feel free to reopen

**Closed by tomjn** 2017-11-08 19:36 UTC
Labels: bug, needs:reproduce
