### ISSUE TITLE
Webgrind doesn't support for filename and function name compression in cachegrind files

### ISSUE THREAD

**Issue by sh-guti** [Varying-Vagrant-Vagrants/VVV#764] opened 2015-10-12 14:16 UTC
And also you can't go to the files and lines.
Found that using the other Webgrind repo https://github.com/michaelschiller/webgrind instead of https://github.com/jokkedk/webgrind fixes the problem .

**Comment by jeremyfelt** [comment] 2015-10-12 22:27
Thanks @sh-guti! It looks like this is a duplicate of #760.

**Closed by jeremyfelt** 2015-10-12 22:27 UTC
