### ISSUE TITLE
Is there a way to access vagrant on mac from a mobile device ?

### ISSUE THREAD

**Issue by dwainm** [Varying-Vagrant-Vagrants/VVV#263] opened 2014-01-27 12:46 UTC
I would like to access Vagrant running on my mac from and iPhone or any other mobile device.

I have have managed to access the server general settings page by following the instructions below but how can local.wordpress.dev be accessed from a mobile device.

https://github.com/10up/varying-vagrant-vagrants/wiki/Configure-for-a-Public-Network

I could only access the page below using the instructions above and the ip address http://192.168.50.4/:

![image](https://f.cloud.github.com/assets/1713474/2008731/bf2af2b6-8750-11e3-8af2-fce8b8197770.png)

I have also tried the instructions here: http://docs.vagrantup.com/v2/networking/public_network.html

I hope I've given enough information here.

**Comment by salcode** [comment] 2015-02-07 20:44
There is a lot of information on Network Configurations at https://jeremyfelt.com/2015/01/31/various-networking-configurations-vvv/.

I've had trouble getting the __Public Network__ working (see #566) but I've had a lot of success with the __Port Forwarding__.

I have full write up about what I'm doing at http://salferrarello.com/vagrant-vvv-setup-wordpress/ but the short version is I've added a `Customfile` in the root vvv directory, which overrides some of the settings in the `Vagrantfile`.  I've copied my `Customfile` below.

## Requirements
- `pfctl` needs to be installed on your system.  It is included by default on a Mac.  I don't know if you can set it up on other OSes
- [vagrant-triggers](https://github.com/emyl/vagrant-triggers) needs to be installed.

## Customfile
```
  # set port forwarding from host 8080 to guest 80
  config.vm.network "forwarded_port", guest: 80, host: 8080


  if defined? VagrantPlugins::Triggers
    # port forwarding setup and removal for running on your host primary IP address
    config.trigger.after [:up, :reload, :provision], :stdout => true do
      system('echo "
rdr pass on lo0 inet proto tcp from any to self port 80 -> 127.0.0.1 port 8080
rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass on en1 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
" | sudo pfctl -ef - >/dev/null 2>&1; echo "Add Port Forwarding (80 => 8080)"')
    end
    config.trigger.after [:halt, :suspend, :destroy], :stdout => true do
      system('sudo pfctl -F all -f /etc/pf.conf >/dev/null 2>&1; echo "Removing Port Forwarding (80 => 8080)"')
    end
  end
```

## Result
My machine is running on `10.0.1.6` and I can access the sites at
- http://10.0.1.6/, the VVV page found at http://vvv.dev/
- http://local.wordpress.10.0.1.6.xip.io/, the site http://local.wordpress.dev/
- http://local.wordpress-trunk.10.0.1.6.xip.io/, the site http://local.wordpress-trunk.dev/
- http://src.wordpress-develop.10.0.1.6.xip.io/, the site http://src.wordpress-develop.dev/
- http://build.wordpress-develop.10.0.1.6.xip.io/, the site http://build.wordpress-develop.dev/

**Comment by lmomadmin** [comment] 2015-05-23 23:41
@westonruter ngrok worked for me to target a domainsite rather than the vvv default,.. by specifying the -host-header="mysite.dev" option. So Nginx answered with mysite.dev rather than the default even though I was using the randomised ngrok url. I didn't need to do 'vagrant share' to reach my site from my ipad. Too bad I can't do something like '%vagrant share -hostname=mysite.dev' so that clients accessing the randomish url get an automatic rewrite of the Host header :-)

**Comment by koppenhoefer** [comment] 2015-05-23 23:46
I'm late to the game,.. but just found that grok solves this problem for me...:

@westonruter ngrok worked for me to target a domainsite rather than the vvv default,.. by specifying the -host-header="mysite.dev" option. So Nginx answered with mysite.dev rather than the default even though I was using the randomised ngrok url. I didn't need to do 'vagrant share' to reach my site from my ipad. Too bad I can't do something like '%vagrant share -hostname=mysite.dev' so that clients accessing the randomish url get an automatic rewrite of the Host header :-)

@aronwp So with -host-header option, you don't really need a paid account.

**Comment by salcode** [comment] 2015-05-24 03:28
@koppenhoefer Can you post the ngrok command with parameters you're using? I'd love to try it out.

**Comment by koppenhoefer** [comment] 2015-05-24 11:09
@salcode Sure! Note that I have used `vv create` to create a separate wordpress site in my vvv... for a site 'tangolausanne.dev'.

`ngrok http tangolausanne.dev:80 -host-header=tangolausanne.dev`

**Comment by MickeyKay** [comment] 2015-08-14 17:30
Question - I've played with ngrok before for this very thing, however the free version doesn't allow for the standard VVV-generated subdomains, right? Example: `local.wordpress-trunk.dev`

Any workarounds for this issue, or do I just need to generate a new site that's got a non-sub domain?

**Comment by salcode** [comment] 2015-08-14 19:07
@MickeyKay 
I'd check out this article on using ngrok 2.0
http://zachwills.net/setting-up-ngrok-and-vvv-to-share-your-local-wordpress-environment-with-the-world/

**Comment by topdown** [comment] 2016-04-10 16:11
I found a solution using Grunt that does not require changing anything with the vagrant setup.
I have been using it to build themes and do full device testing and it has been working great.
It syncs browsers across the Wifi network and acts like Live Reload.
There is a Gist here https://gist.github.com/topdown/940a0af716fc386517ed2169fa7ffc4f
One setting must be set in the Gruntfile `var $proxy = 'vvv_domain.dev';`

NOTE: I have it stripped down for speed, Eg. I am only watching html,php and css
And using compass outside of this to watch my SASS files. Having grunt do this was to slow for me.

**Comment by dingo-d** [comment] 2017-06-02 10:23
Could you use webpack for this as well? Setting up `webpack-dev-server` maybe?

**Comment by dingo-d** [comment] 2017-07-04 08:23
I can confirm, the above works with webpack 3 :) Just follow the instructions on the link above. I used it with my custom `wordpress-test.dev` installation so the config in `webpack.config.js` looks like this:

~~~js
  const BrowserSyncPlugin = require('browser-sync-webpack-plugin');

  new BrowserSyncPlugin({
    host: 'localhost',
    port: 3000,
    proxy: 'wordpress-test.dev'
  },
  {
    reload: false
  })
~~~

**Comment by tomjn** [comment] 2017-11-03 17:53
At the moment VVV 2 doesn't provide this out of the box, but there is discussion and attempts to bring xip.io like services to the site provisioners elsewhere, so I'm going to close this particular ticket out in favour of those

**Closed by tomjn** 2017-11-03 17:53 UTC
Labels: documentation, enhancement, vvv.org
