### ISSUE TITLE
SimpleXML not loaded

### ISSUE THREAD

**Issue by pdewouters** [Varying-Vagrant-Vagrants/VVV#935] opened 2016-07-12 11:19 UTC
On branch `develop` ( assuming that's the correct stable branch as per readme?), I was experiencing this error: `PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /srv/www/site/htdocs/content/plugins/plugin/vendor/guzzlehttp/guzzle/src/Message/Response.php:162`

I found this [stackoverflow](http://stackoverflow.com/a/35614586) answer that solved the issue, but required me to install the packages manually inside the vagrant box.
`sudo add-apt-repository -y ppa:ondrej/php && sudo apt update && sudo apt install -y php7.0-mbstring php7.0-zip php7.0-xml`

**Comment by jeremyfelt** [comment] 2016-08-16 05:54
Looks like this is a duplicate of #893. We'll get this in 1.4.0. Thanks @pdewouters!

**Closed by jeremyfelt** 2016-08-16 05:54 UTC
Labels: bug, needs:patch
