### ISSUE TITLE
Php7.2-fpm service not starting

### ISSUE THREAD

**Issue by FredoNook** [Varying-Vagrant-Vagrants/VVV#2065] opened 2020-02-06 21:51 UTC
Hello friends!

## Expected Behavior
Run $vagrant up --provision
VM start
access to vvv.test and vvv.test work as expected

## Current Behavior
Run $vagrant up --provision
VM start
try access to vvv.test -> 502 bad request

## Possible Solution
fix php7.2-fpm service start 
i check nginx logs, the php7.2-fpm not create /var/run/php7.2-fpm.sock
and after sometime service php7.2-fpm stop with error - timeout

## Steps to Reproduce (for bugs)
1. I do nothing extraordinary. Just install 
2. I use official installation guide

error samples in nginx error.log
```
2020/02/06 18:48:38 [crit] 6643#6643: *1 connect() to unix:/var/run/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.50.1, server: vvv.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.2-fpm.sock:", host: "vvv.test"
2020/02/06 18:48:41 [crit] 6643#6643: *1 connect() to unix:/var/run/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.50.1, server: vvv.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.2-fpm.sock:", host: "vvv.test"
2020/02/06 18:48:59 [crit] 6642#6642: *5 connect() to unix:/var/run/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.50.1, server: vvv.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.2-fpm.sock:", host: "vvv.test"
2020/02/06 18:58:22 [crit] 6643#6643: *29 connect() to unix:/var/run/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: vvv.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.2-fpm.sock:", host: "localhost"
```

## Your Environment

Windows 10 PC 64-bit
Vagrant 2.2.7 and Virtualbox 6.0

## Logs

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::master

Platform: platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled , VVV Path: "C:/develop/vvv"
Vagrant: v2.2.7, VirtualBox: vN/A

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20200131.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20200131.0.0'. The latest is version
==> default: '20200206.0.0'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.8_KernelUbuntu r120774
    default: VirtualBox Version: 6.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 one.wordpress.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 two.wordpress.test
==> default: [vagrant-hostsupdater] Writing the following entries to (C:/Windows/system32/drivers/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.50.4  vvv.test  # VAGRANT: c8deef9ae4a3467fcc0aed28b32402b0 (default) / c7e5af40-aad4-4ed5-a56c-1810400f73f2
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /srv/www => C:/Develop/vvv/www
    default: /srv/config => C:/Develop/vvv/config
    default: /var/log/php => C:/Develop/vvv/log/php
    default: /srv/database => C:/Develop/vvv/database/sql
    default: /var/log/nginx => C:/Develop/vvv/log/nginx
    default: /srv/provision => C:/Develop/vvv/provision
    default: /srv/certificates => C:/Develop/vvv/certificates
    default: /var/log/memcached => C:/Develop/vvv/log/memcached
    default: /var/log/provisioners => C:/Develop/vvv/log/provisioners
==> default: Running provisioner: file...
    default: C:/develop/vvv/version => /home/vagrant/version
==> default: Running provisioner: default (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-1vqox4q.sh
    default:  * Beginning Main VVV Provisioner, if this is the first provision this may take a few minutes
    default:  * Testing network connection
    default:  * Succesful Network connection to ppa.launchpad.net detected...
    default: Bash profile setup and directories.
    default:  * Setting ownership of files in /home/vagrant to vagrant
    default:  * Copying /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copying /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copying /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copying /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copying /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default:  * Copying /srv/config/ssh_known_hosts to /etc/ssh/ssh_known_hosts
    default:  * Copying /srv/config/sshd_config to /etc/ssh/sshd_config
    default:  * Reloading SSH Daemon
    default:  * Testing network connection
    default:  * Succesful Network connection to ppa.launchpad.net detected...
    default:
    default:  * Main packages check and install.
    default:  * git-core/ppa already present, skipping
    default:
    default:  * Setting up MySQL configuration file links...
    default:  * mysql group exists
    default:  * mysql user present and has uid 9001
    default: uid=9001(mysql) gid=9001(mysql) groups=9001(mysql),115(vboxsf)
    default:  * Copying /srv/config/mysql-config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf
    default:  * Copying custom apt sources
    default:  * Checking Apt Keys
    default:  * Running apt-get update...
    default: Hit:1 http://nginx.org/packages/mainline/ubuntu bionic InRelease
    default: Hit:2 http://mirrors.coreix.net/mariadb/repo/10.3/ubuntu bionic InRelease
    default: Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
    default: Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
    default: Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    default: Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
    default: Hit:7 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic InRelease
    default: Hit:8 https://deb.nodesource.com/node_10.x bionic InRelease
    default: Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    default: Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [850 kB]
    default: Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [632 kB]
    default: Hit:10 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
    default: Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [297 kB]
    default: Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1048 kB]
    default: Get:15 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [207 kB]
    default: Get:16 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [643 kB]
    default: Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [324 kB]
    default: Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [216 kB]
    default: Fetched 4469 kB in 8s (578 kB/s)
    default: Reading package lists...
    default:  * Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: make is already the newest version (4.1-9.1ubuntu1).
    default: unzip is already the newest version (6.0-21ubuntu1).
    default: zip is already the newest version (3.0-11build1).
    default: colordiff is already the newest version (1.0.18-1).
    default: dos2unix is already the newest version (7.3.4-3).
    default: graphviz is already the newest version (2.40.1-2).
    default: ngrep is already the newest version (1.47+ds1-1).
    default: subversion is already the newest version (1.9.7-4ubuntu1).
    default: curl is already the newest version (7.58.0-2ubuntu3.8).
    default: g++ is already the newest version (4:7.4.0-1ubuntu2.3).
    default: gettext is already the newest version (0.19.8.1-6ubuntu0.3).
    default: git is already the newest version (1:2.17.1-1ubuntu0.5).
    default: imagemagick is already the newest version (8:6.9.7.4+dfsg-16ubuntu6.8).
    default: memcached is already the newest version (1.5.6-0ubuntu1.2).
    default: postfix is already the newest version (3.3.0-1ubuntu0.2).
    default: software-properties-common is already the newest version (0.96.24.32.12).
    default: vim is already the newest version (2:8.0.1453-1ubuntu1.1).
    default: git-svn is already the newest version (1:2.17.1-1ubuntu0.5).
    default: ntp is already the newest version (1:4.2.8p10+dfsg-5ubuntu7.1).
    default: python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
    default: nginx is already the newest version (1.17.8-1~bionic).
    default: php-imagick is already the newest version (3.4.4-1+ubuntu18.04.1+deb.sury.org+20191129).
    default: php-memcache is already the newest version (3.0.9~20170802.e702b5f-3+ubuntu18.04.1+deb.sury.org+20191129).
    default: php-memcached is already the newest version (3.1.4+2.2.0-1+ubuntu18.04.1+deb.sury.org+20191129).
    default: php-pear is already the newest version (1:1.10.8+submodules+notgz-1+ubuntu18.04.1+deb.sury.org+1).
    default: php-ssh2 is already the newest version (1.2+0.13-1+ubuntu18.04.1+deb.sury.org+1).
    default: php-xdebug is already the newest version (2.9.1+2.9.0+2.5.5-1+ubuntu18.04.1+deb.sury.org+1).
    default: php-yaml is already the newest version (2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+20191129).
    default: php7.2-bcmath is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-cli is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-common is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-curl is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-dev is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-fpm is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-gd is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-imap is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-json is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-mbstring is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-mysql is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-soap is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-xml is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: php7.2-zip is already the newest version (7.2.27-6+ubuntu18.04.1+deb.sury.org+1).
    default: mariadb-server is already the newest version (1:10.3.22+maria~bionic).
    default: nodejs is already the newest version (10.19.0-1nodesource1).
    default: git-lfs is already the newest version (2.10.0).
    default: 0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
    default:  * Removing unnecessary packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: 0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
    default:  * Cleaning apt caches...
    default:  * Running tools_install
    default: Disabling XDebug if it's present
    default: Enabling tideways_xhprof and xhgui if installed
    default: WARNING: Module tideways_xhprof ini file doesn't exist under /etc/php/7.2/mods-available
    default: WARNING: Module tideways_xhprof ini file doesn't exist under /etc/php/7.2/mods-available
    default: WARNING: Module xhgui ini file doesn't exist under /etc/php/7.2/mods-available
    default: WARNING: Module xhgui ini file doesn't exist under /etc/php/7.2/mods-available
    default: Restarting PHP FPM's
    default: Job for php7.2-fpm.service failed because a timeout was exceeded.
    default: See "systemctl status php7.2-fpm.service" and "journalctl -xe" for details.
    default: XDebug is turned off
    default:  * Checking for NVM
    default:  * Installing/updating npm...
    default: /usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
    default: /usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
    default: + npm@6.13.7
    default: updated 1 package in 7.586s
    default:  * Installing/updating npm-check-updates...
    default: /usr/bin/npm-check-updates -> /usr/lib/node_modules/npm-check-updates/bin/npm-check-updates
    default: /usr/bin/ncu -> /usr/lib/node_modules/npm-check-updates/bin/ncu
    default: + npm-check-updates@4.0.1
    default: updated 1 package in 14.429s
    default:  * ack-grep already installed
    default:  * Making sure the composer cache is not owned by root
    default:  * Checking for Composer
    default:  * Updating Composer...
    default: Changed current directory to /usr/local/src/composer
    default: You are already using composer version 1.9.3 (stable channel).
    default: Changed current directory to /usr/local/src/composer
    default: ./composer.json has been updated
    default: Changed current directory to /usr/local/src/composer
    default: Loading composer repositories with package information
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
    default: Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
    default: Generating autoload files
    default:  * Updating Grunt CLI
    default:  * Updated Grunt CLI
    default:  * Adding graphviz symlink for Webgrind...
    default:  * Installing Shyaml for bash provisioning..
    default: Requirement already satisfied: shyaml in /usr/local/lib/python2.7/dist-packages
    default: Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from shyaml)
    default:
    default:  * Setup configuration files...
    default:  * Copying /srv/config/init/vvv-start.conf               to /etc/init/vvv-start.conf
    default:  * Copying /srv/config/nginx-config/nginx.conf           to /etc/nginx/nginx.conf
    default:  * Copying /srv/config/nginx-config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf
    default:  * Copying /srv/config/nginx-config/php7.2-upstream.conf to /etc/nginx/upstreams/php72.conf
    default:  * Rsync'ing /srv/config/nginx-config/sites/             to /etc/nginx/custom-sites
    default: sending incremental file list
    default: deleting vvv-auto-wordpress-two-provision-b0bc8489c53c6b96847837cbb5a3ac4a.conf
    default: deleting vvv-auto-wordpress-one-provision-60730e707ede8a21f013860b6fc556e1.conf
    default: default.conf
    default: local-nginx-example.conf-sample
    default: sent 1.92K bytes  received 202 bytes  4.24K bytes/sec
    default: total size is 4.08K  speedup is 1.93
    default:  * Making sure the Nginx log files and folder exist
    default:  * Starting MailHog
    default:  * Copying /srv/config/php-config/php7.2-fpm.conf   to /etc/php/7.2/fpm/php-fpm.conf
    default:  * Copying /srv/config/php-config/php7.2-www.conf   to /etc/php/7.2/fpm/pool.d/www.conf
    default:  * Copying /srv/config/php-config/php7.2-custom.ini to /etc/php/7.2/fpm/conf.d/php-custom.ini
    default:  * Copying /srv/config/php-config/opcache.ini       to /etc/php/7.2/fpm/conf.d/opcache.ini
    default:  * Copying /srv/config/php-config/xdebug.ini        to /etc/php/7.2/mods-available/xdebug.ini
    default:  * Copying /srv/config/php-config/mailhog.ini       to /etc/php/7.2/mods-available/mailhog.ini
    default:  * Copying /srv/config/memcached-config/memcached.conf to /etc/memcached.conf and /etc/memcached_default.conf
    default:
    default:  * Restarting services...
    default: Job for php7.2-fpm.service failed because a timeout was exceeded.
    default: See "systemctl status php7.2-fpm.service" and "journalctl -xe" for details.
    default:
    default:  * Setup MySQL configuration file links...
    default:  * Copied /srv/config/mysql-config/my.cnf               to /etc/mysql/my.cnf
    default:  * Copied /srv/config/mysql-config/root-my.cnf          to /home/vagrant/.my.cnf
    default:  * service mysql restart
    default:
    default:  * No custom MySQL scripting found in database/init-custom.sql, skipping...
    default:  * Initial MySQL prep...
    default:
    default: Starting MariaDB Database Import
    default:  * Creating the wordpress-one table if it doesn't already exist, and granting the wp user access
    default:   * Skipped import of wordpress-one - tables exist
    default:  * Creating the wordpress-two table if it doesn't already exist, and granting the wp user access
    default:   * Skipped import of wordpress-two - tables exist
    default: Databases imported
    default:  * Testing network connection
    default:  * Succesful Network connection to ppa.launchpad.net detected...
    default:
    default:  * Installing/updating wp-cli and debugging tools
    default:
    default:  * Updating wp-cli...
    default: Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
    default: md5 hash verified: 7ed99a6b1e1bfc30b4f287c718f69a48
    default: New version works. Proceeding to replace.
    default: Success: Updated WP-CLI to the latest nightly release.
    default:
    default:  * Install/Update PHP_CodeSniffer (phpcs), see https://github.com/squizlabs/PHP_CodeSniffer
    default:
    default:  * Install/Update WordPress-Coding-Standards, sniffs for PHP_CodeSniffer, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    default: Loading composer repositories with package information
    default:
    default:
    default:
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
    default: Using config file: /srv/www/phpcs/CodeSniffer.conf
    default:
    default: Config value "installed_paths" updated successfully; old value was "./CodeSniffer/Standards/WordPress/,./CodeSniffer/Standards/VIP-Coding-Standards/,./CodeSniffer/Standards/PHPCompatibility/,./CodeSniffer/Standards/PHPCompatibilityParagonie/,./CodeSniffer/Standards/PHPCompatibilityWP/"
    default: Using config file: /srv/www/phpcs/CodeSniffer.conf
    default:
    default: Config value "default_standard" updated successfully; old value was "WordPress-Core"
    default: The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra, WordPress-VIP-Go, WordPressVIPMinimum, PHPCompatibility, PHPCompatibilityParagonieRandomCompat, PHPCompatibilityParagonieSodiumCompat and PHPCompatibilityWP
    default:  * Testing network connection
    default:  * Succesful Network connection to ppa.launchpad.net detected...
    default:
    default:  * Searching for SVN repositories that need upgrading
    default:
    default:  * Cleaning up Nginx configs
    default:  * Cleaning the virtual machine's /etc/hosts file...
    default:  -----------------------------
    default:  * Provisioning complete in 295 seconds
    default:  * For further setup instructions, visit http://vvv.test
==> default: Running provisioner: dashboard (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-s0afnf.sh
    default:
    default: Updating dashboard on the master branch...
==> default: Running provisioner: utility-source-core (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-1tb8jox.sh
    default:  * Updating the "core" utility on the "master" branch...
==> default: Running provisioner: utility-core-tls-ca (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-z6zlmr.sh
    default:  * Running utility provisioner for 'core/tls-ca'
    default:  * The 'core/tls-ca' provisioner completed in 2 seconds
==> default: Running provisioner: utility-core-phpmyadmin (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-1ono8mv.sh
    default:  * Running utility provisioner for 'core/phpmyadmin'
    default:  * The 'core/phpmyadmin' provisioner completed in 0 seconds
==> default: Running provisioner: site-wordpress-one (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-12rrtvt.sh
    default:  * Running provisioner for site wordpress-one
    default:  * Updating wordpress-one in /srv/www/wordpress-one...
    default:  * Searching for a site template provisioner, vvv-init.sh
    default:  * Found vvv-init.sh at /srv/www/wordpress-one/provision/vvv-init.sh
    default:  * Script output will be logged to: log/provisioners/20200206-213254/provisioner-site-wordpress-one.log
    default:  * Site provisioner script finished successfully
    default:  * Adding domains to the virtual machine's /etc/hosts file...
    default:  * Adding hosts from the VVV config entry
    default:    - Added one.wordpress.test from /vagrant/config.yml
    default:  * Reloading Nginx
    default:  * wordpress-one provisioning finished in 13 seconds
==> default: Running provisioner: site-wordpress-two (shell)...
    default: Running: C:/Users/fredo/AppData/Local/Temp/vagrant-shell20200207-1264-9diqm4.sh
    default:  * Running provisioner for site wordpress-two
    default:  * Updating wordpress-two in /srv/www/wordpress-two...
    default:  * Searching for a site template provisioner, vvv-init.sh
    default:  * Found vvv-init.sh at /srv/www/wordpress-two/provision/vvv-init.sh
    default:  * Script output will be logged to: log/provisioners/20200206-213254/provisioner-site-wordpress-two.log
    default: Warning: query-monitor: Plugin already installed.
    default: Warning: Plugin 'query-monitor' is already active.
    default:  * Site provisioner script finished successfully
    default:  * Adding domains to the virtual machine's /etc/hosts file...
    default:  * Adding hosts from the VVV config entry
    default:    - Added two.wordpress.test from /vagrant/config.yml
    default:  * Reloading Nginx
    default:  * wordpress-two provisioning finished in 14 seconds
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default: Post Vagrant up script
    default: Restarting Nginx and MySQL
    default:
    default:          yay
    default:    ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄                __ __ __ __
    default:    █▒▒░░░░░░░░░▒▒█    Thanks for  \ V\ V\ V /
    default:     █░░█░░░░░█░░█     using        \_/\_/\_/
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█ Vagrant Up has finished! Visit http://vvv.test
    default:
```

**Comment by mmccaff** [comment] 2020-02-06 21:58
We're seeing the same, using the master branch. The sites all work for a few minutes, and then stop working with 502s.

A ```vagrant up --no-provision``` will bring them back for a few minutes, then back to 502s again.

**Comment by tomjn** [comment] 2020-02-06 22:13
Duplicate of #2061, switch to the `develop` branchwhich contains the fix

**Closed by tomjn** 2020-02-06 22:13 UTC
Labels: bug
