### ISSUE TITLE
grunt watch doesn't detect changes when ran from guest machine

### ISSUE THREAD

**Issue by mnelson4** [Varying-Vagrant-Vagrants/VVV#1531] opened 2018-05-29 22:30 UTC
## Expected Behavior
Since WordPress' new build process was introduced (see https://make.wordpress.org/core/2018/05/16/preparing-wordpress-for-a-javascript-future-part-1-build-step-and-folder-reorganization/) we should be running `grunt watch` which should copy the changes made from the src directory into the build one.

## Current Behavior

However on a windows host machine with with VVV, when you make a change to a file (from your host machine or inside the VM) that's in a shared directory, grunt doesn't notice the change. 

## Possible Solution

This is probably because of https://www.virtualbox.org/ticket/10660 (so it's a Virtual box issue). BUt I'm reporting here in case someone else has this issue and is looking for a fix, and it's possible we might find some workaround for VVV. 

## Steps to Reproduce (for bugs)

1. Do git clone git://develop.git.wordpress.org/ from inside VVV's www shared folder
2. from inside there, run `npm install && grunt build`. Then `grunt watch`. Wait until it says it's "Watching..."
3. Edit a file from inside src
4. Notice that the grunt task doesn't acknowledge that change, nor update the corresponding file in build

## Context

I've been using the same WP develop checkout for both developing a few plugins, and for the occasional core contribution. So for developing plugins I will probably put my `wp-content` folder outside of the normal WP src folder, and use `define( 'WP_CONTENT_DIR', dirname( dirname(__FILE__) ) . '/content' ); define( 'WP_CONTENT_URL', 'http://dev.local/content' );`) so that I don't need to wait for grunt watch to copy all my changes from src to build everytime. But I'm currently a bit stuck for WP core contributions.

## Your Environment

* VVV version: 2.1.0
* VVV Git Branch: master (commit 710f08527730bbeea5b263cd6e6ff1614cb224ea)
* Vagrant version: 2.0.2
* VM Provider name: Virtual Box
* VM Provider version: 5.1.32
* Operating System and version: Windows 7

**Comment by mnelson4** [comment] 2018-05-29 22:36
created a duplicate of this issue inside WP trac, https://core.trac.wordpress.org/ticket/44271, in case the issue can be solved from that end (or in case someone else experiences it and is searching for it from there)

**Comment by tomjn** [comment] 2018-05-29 23:18
Eh the Trac ticket will get closed, this is a general vagrant issue. You can fix this at the cost of reduced performance, but it will never be as good as running it on the host

**Comment by mnelson4** [comment] 2018-07-06 17:57
Here's a hacky workaround: 

1. Cloned WordPress repo to somewhere in the guest machine that is NOT sync'd with host machine. Eg like anywhere in the vagrant user's home directory, like `~/www/wordpress-develop-repo`, 
2. create a symlink from this repo's build folder to the one in `srv/www`, eg `makedir /srv/www/wordpress-develop/public_html/build; ln -s /srv/www/wordpress-develop/public_html/build ~/www/wordpress-develop-repo/build;`
3. run `grunt watch --force` from  `~/www/wordpress-develop-repo`. `--force` is needed because grunt has trouble removing the entire `build` directory, because it's now actually a symlink. So files deleted in `src` will need to be manually deleted from `build`, but otherwise it works

So with this, `grunt watch` works, and the changes from `~/www/wordpress-develop-repo/src` get deployed to `srv/www/wordpress-develop/public_html/build`.

**Comment by tomjn** [comment] 2019-08-06 23:41
This may work better now that we're on a newer version of everything. We need to look into this again, even if performance isn't the greatest

**Comment by Mte90** [comment] 2019-10-24 10:53
I think that to avoid issue we can create a new command like `vagrant vvv wordpress-develop "grunt watch"`.

Where `wordpress-develop` is the sitename where will be executed the command, and the next parameter is the command itself to execute.

**Comment by tomjn** [comment] 2019-12-20 12:01
@Mte90 that won't help, the root cause of this is the way filesystem updates are handled via virtualbox, running the command isn't the issue. I'm going to remove the hacktoberfest label as this is a pretty big task, one that may require C, VirtualBox internals, and some pretty hardcore knowledge of Windows/Mac/Linux filesystems to fix

**Comment by Mte90** [comment] 2019-12-20 12:03
Well the pr that add vvv commands let's to execute commands internally the machine from the host without enter ssh, this simplify a lot the problem.

**Comment by tomjn** [comment] 2019-12-20 12:04
For more information, the root problem here is performance in shared/mounted folders, and how they're implemented. Docker solves this by brute forcing the problem, leading to very large CPU churn. Another way to resolve this is microcaches, but this introduces the problem the OP has. Without microcaches, disk performance speed nosedives.

Note that the characteristics of disk access vary significantly between providers as a result

> Well the pr that add vvv commands let's to execute commands internally the machine from the host without enter ssh, this simplify a lot the problem.

Running the command inside the VM is what the OP was doing in the first place. That isn't what the problem is. The problem is running `grunt watch` inside the VM on a shared folder isn't reliable

**Comment by Mte90** [comment] 2020-03-25 16:30
I am testing now with the latest custom-template-develop, using `npm run grunt watch` in the host machine as defined at https://make.wordpress.org/core/handbook/testing/patch/ and it is working.
The php files and the others are copied to the build folder with no issues and also webpack too.
As I can see is better in the host machine because webpack can consume a lot the machine memory in fact executed with VVV with 1gb of ram the script was killed.
There are any specific reasons why we need to run this inside the VM?

**Comment by tomjn** [comment] 2020-03-25 16:38
That's not the problem. The problem is that VirtualBox mounted folders don't propagate all filesystem change events, making filesystem watchers unreliable. There is no node/provisioner based fix for this

**Comment by tomjn** [comment] 2020-03-25 16:39
I'm going to mark this as closed as it's beyond the scope of this project, and not something VVV or WP can change or fix. The problem is several layers deeper down at the virtualisation layer

**Closed by tomjn** 2020-03-25 16:39 UTC
Labels: help wanted
