### ISSUE TITLE
VVV ubuntu version needs updating from Ubuntu v.14.04.5 LTS to v.16.04.2 LTS

### ISSUE THREAD

**Issue by faddah** [Varying-Vagrant-Vagrants/VVV#1229] opened 2017-07-04 07:16 UTC
## Expected Behavior

You should be able to upgrade to the latest version of Ubuntu LTS in the VVV environment, or it should come automatically with the latest Ubuntu LTS, v.16.04.2, Xenial Xerus.

## Current Behavior
This is, perhaps, related to previous issues in this repository - #1000 & #1003 .

When you `vagrant up` with the latest version of VVV, and after it is provisioned and you `vagrant ssh` in, you see the following —

```
$ vagrant ssh


  __     ___     ___     __  ____    
  \ \   / \ \   / \ \   / / |___ \   
   \ \ / / \ \ / / \ \ / /    __) |  
    \ V /   \ V /   \ V /    / __/   
     \_/     \_/     \_/    |_____|  

  Varying Vagrant Vagrants 2.0.0

  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv



Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-123-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue Jul  4 06:24:41 UTC 2017

  System load:  0.72              Processes:           90
  Usage of /:   6.3% of 39.34GB   Users logged in:     0
  Memory usage: 34%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.4

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

5 packages can be updated.
1 update is a security update.

New release '16.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Tue Jul  4 06:24:42 2017 from 10.0.2.2
vagrant@vvv:~$ 
```

If you try and do what the Ubuntu system message says, and upgrade to Ubuntu v.16.04.2, you have to monitor the upgrade all the way through, and give it info most users will have Zero idea how to answer, like giving it the appropriate Chef URL, etc. 

As a result, when the upgrade/install is done, and you `vagrant halt` and re-`vagrant up` to see the upgraded ubuntu v.16.04.2, you get all sorts of red text errors on trying to `vagrant up`  saying the VM cannot start due to network errors.

## Possible Solution
Either provide instructions in the README.md on how to properly upgrade the VM to Ubuntu v.16.04.2 so users don't encounter these errors, or have the Ubuntu VM in VVV all ready be the latest LTS, in this case v.16.04.2 Xenial Xerus.

## Steps to Reproduce (for bugs)
Set-up - tested this on a Mac Pro w/ 3.5 GHz 6-Core Intel Xeon E5, 16 GB of RAM, MacOS Sierra 10.12.5, Oracle VirtualBox Version 5.1.22 r115126 (Qt5.6.2), Vagrant 1.9.5, and VVV v.2.0.0.

1.  clone & download VVV v.2.0.0 to a local directory on the machine
2. `vagrant up` the VM
3. once the VM is provisioned and up & running, `vagrant ssh` into the VM from the command line 
4. you'll see the text about upgrading to Ubuntu v.16.04.2, listed above, when you `vagrant ssh` in.
5. Attempt to follow the instructions for `do-release-upgrade` to upgrade to Ubuntu v.16.04.2
6. You will have to sit and baby sit through the install process as it will ask several times for input info, like the appropriate Chef URL (which a lot of people won't know what to put in there).
7. After the upgrade/install, do `vagrant halt` and then `vagrant up` to restart and, hopefully, have the new Ubuntu v16.04.2 come up.
8. It won't come up, you'll get errors on trying to `vagrant up` about network errors.

## Context
Can't use the latest Ubuntu LTS, v.16.04.2, which has a lot of LTS upgrades and fixes in it.

## Your Environment

* VVV version: v.2.0.0
* Vagrant version: Vagrant v.1.9.5
* VM Provider name: VirtualBox v. 5.1.22 r115126 (Qt5.6.2)
* VM Provider version:  v.5.1.22 r115126 (Qt5.6.2)
* Operating System and version: MacOS Sierra v.10.12.5

**Comment by DArcMattr** [comment] 2017-07-26 17:24
This is a duplicate of #954, for which there is a candidate patch.

**Comment by jeremyfelt** [comment] 2017-11-08 04:22
Thanks for taking the time to document this, @faddah. I'm going to close this as a duplicate of #954 and it's open PR #1218.

Updating to the latest LTS release is something that we want to happen, but will likely require a breaking release of 3.x.x.

**Closed by jeremyfelt** 2017-11-08 04:22 UTC
