### ISSUE TITLE
xdebug not formatting var_dump() output

### ISSUE THREAD

**Issue by marcelo2605** [Varying-Vagrant-Vagrants/VVV#1563] opened 2018-06-27 14:21 UTC
After update to version 2.2.1, xdebug is not formatting debug output on screen. Before this update, I just run `xdebug_on` on SSH.

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: master
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.4 r119785 (Qt5.6.2)
* Operating System and version: Windows 10

**Comment by tomjn** [comment] 2018-06-27 14:28
Is `xdebug` turned on? It gets turned off during provisioning, otherwise provisions would take a veeerry long time

**Comment by tomjn** [comment] 2018-06-27 14:29
Additionally, can you try with `develop` just to confirm it's not already been fixed by something else?

**Comment by marcelo2605** [comment] 2018-06-27 15:19
Hi @tomjn 

Here is my terminal output:

> vagrant@vvv:~$ xdebug_on
> php7.0-fpm stop/waiting
> php7.0-fpm start/running, process 11241

But xdebug not appear in vvv.test/phpinfo

I need to run `vagrant reload --provision` after run this?

**Comment by tomjn** [comment] 2018-06-27 15:33
Reprovisioning shouldn't be necessary, in fact reprovisioning would call `xdebug_off`

However, I do see that it triggered `php7.0-fpm`, but the default is actually PHP 7.2.

So I suspect that it's working, but you're using a different PHP version

**Comment by tomjn** [comment] 2018-06-27 15:34
Can you update to the latest `develop` branch, reprovision, and try again? Additionally what's in your `vvv-custom.yml`?

**Comment by marcelo2605** [comment] 2018-06-27 15:37
OK, I will do this later and reply back.

Here is my vvv-custom.yml:

```
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  isk:
    hosts:
      - isk.test
      
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind

```

**Comment by tomjn** [comment] 2018-06-27 15:41
Thanks, you might want to add these to the utilities section:

```
    - trusted-hosts
    - tls-ca
```

I doubt it will impact your issue, but it will give you SSL certificates

**Comment by tomjn** [comment] 2018-06-27 18:04
Of note, no changes have been made recently to xdebug, and the `php-xdebug` package is still in the install list, and the xdebug script should still be present.

Here's the `xdebug_on` script:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/ee69135edc60e800c054ad1b358ac68ed8f8d76e/config/homebin/xdebug_on#L2

It would be helpful to run each command on its own and check for issues and report back

**Comment by tomjn** [comment] 2018-06-27 18:06
You can also check http://vvv.test/phpinfo

This is my phpinfo after running `xdebug_on` inside the VM on the latest `develop` commit:

<img width="1256" alt="screen shot 2018-06-27 at 19 05 21" src="https://user-images.githubusercontent.com/58855/41991374-1f6e7a74-7a3d-11e8-8624-7900bf56b8c5.png">

**Comment by tomjn** [comment] 2018-06-27 18:07
Keep in mind that if XDebug is turned off, it will not appear in the phpinfo, and XDebug is automatically turned off during a provision, and needs to be explicitly turned back on again using `xdebug_on` inside the VM

**Comment by joelworsham** [comment] 2018-06-27 18:11
Steps I just took:

1. Added these to my utilities section in `vvv-custom.yml`:
```
    - trusted-hosts
    - tls-ca
```
2. Ran `vagrant reload --provision` (provision finished with no errors)
3. SSH into server
4. Ran `xdebug_on`
5. Checked http://vvv.test/phpinfo/ and xdebug is not present
6. Ran `sudo phpenmod xdebug` in server
7. Repeated step 5 with same result, no xdebug

I know there's a million and one environmental variables, so it's crazy hard to find the issue... but do you have any other ideas? Been searching the internet desperately for 4 hours now and nothing. I even tried to use `apt-get` to install `php-xdebug`, but it says it's already installed (even though it doesn't show as a php module in the list I sent in the other issue)

**Comment by tomjn** [comment] 2018-06-27 18:11
Tested after running `xdebug_on` in the default PHP 7.2:

```php
$test = ['banana','test'];
var_dump( $test );
exit;
```

<img width="548" alt="screen shot 2018-06-27 at 19 10 45" src="https://user-images.githubusercontent.com/58855/41991583-d6b6fb98-7a3d-11e8-9f08-0c76b76723df.png">

**Comment by tomjn** [comment] 2018-06-27 18:13
@joelworsham which version of PHP does PHPInfo claim you're running? It should be 7.2

And at which point did it go from working to not working?

**Comment by tomjn** [comment] 2018-06-27 18:16
For refrence, I've a `20-xdebug.ini` in my `/etc/php/7.2/cli/conf.d/` folder, you should also have an `xdebug.ini` at `/etc/php/7.2/mods-available/`

**Comment by joelworsham** [comment] 2018-06-27 18:45
Version: `PHP 7.2.7-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jun 22 2018 09:13:37)`

It worked within the past few days. I believe I did pull a new version of VVV between it working and not working. I was on `master`. After it stopped working I tried `develop` branch.

Both of those files do exist in those directories.

**Comment by joelworsham** [comment] 2018-06-28 18:15
Just wanted to update you that xdebug is loading again.

I do **not** know what made it work again. This was a bizarre fluke... But it is loaded now.

**Comment by tomjn** [comment] 2018-06-28 18:31
hmmm that's a shame, did you `git pull` or a halt and up? I had the weird experience of mailcatcher suddenly starting to work while I was replacing it with the more reliable MailHog, like a "noo please don't replace me"

**Comment by joelworsham** [comment] 2018-06-28 19:49
Oh yeah... mailcatcher ALSO doesn't work all the sudden..... 😆 

The only thing that happened between yesterday and today is a computer restart (which I had already tried as a solution yesterday with no luck). I didn't git pull

**Comment by tomjn** [comment] 2018-06-28 20:50
Mailcatcher is gone, removed in the `develop` branch because it's unreliable. Behold the maintenance dream that is MailHog :)

**Comment by marcelo2605** [comment] 2018-06-29 21:13
Hey @tomjn I run `git pull origin develop` and then `vagrant up --provision`. In the middle of the proccess, appears this error:

> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by tomjn** [comment] 2018-06-29 22:11
Were you on the `develop` branch when you pulled? What was immediately before that error? That's Vagrant saying something happened while it ran a provisioner, but without context it's not possible to identify what that was, full log please

**Comment by marcelo2605** [comment] 2018-06-30 01:08
On the first time, no. Now, I run `git checkout develop`, `git pull` and `vagrant up --provision`. Here is the last lines before error:

>  default: /srv/database => M:/vagrant-local/database
> ==> default: Running provisioner: fix-no-tty (shell)...
>     default: Running: inline script
> ==> default: Running provisioner: default (shell)...
>     default: Running: C:/Users/marce/AppData/Local/Temp/vagrant-shell20180629-6128-128p0u2.sh
>     default: Network connection not detected. Unable to reach google.com...
>     default:
>     default: #################################################################
>     default:
>     default: Problem:
>     default: Provisioning needs a network connection but none was found.
>     default: VVV tried to ping google.com, and got no response.

**Comment by tomjn** [comment] 2018-06-30 10:32
I've opened #1573 which *might* correct that problem by forcing dpkg to answer the question in a certain way. It's very difficult to tell with only a partial log, so at best it's a guess, but your xdebug config was modified or changed and dpkg doesn't know what to do. So it errs on the side of caution and asks, then exits when it doesn't get a response

**Closed** 2018-06-30 10:51 UTC
Labels: question, support

**Comment by joelworsham** [comment] 2018-07-17 14:47
I don't know if I should open a new issue, but I am still having issues with this.

When I initially boot up the machine, xdebug is not loaded. I ssh into the machine and run `xdebug_on`, but it doesn't do anything. xdebug still does not load. Verified by visiting `vvv.test/phpinfo`.

If I then run `vagrant reload`, xdebug is on immediately and cannot be turned off with `xdebug_off`

**Comment by tomjn** [comment] 2018-07-17 17:22
@joelworsham is this replicable from a brand new VVV instance in a new folder on the `develop` branch? Confirming that no other local environment is running at the same time, be it a Docker/Node/Vagrant/VVV/etc? With no custom utilities? With the standard `vvv-custom.yml` out of the box?

If so, please post the entire provisioner log for the initial provision in a gist, along with the full output of every command given after initial provision to test things.

Right now the problem cannot be reproduced by anybody with a clean environment to my knowledge, if it cannot be reproduced then it's very likely to be a problem unique to your particular VVV instance.

Also, please be as verbose as you possibly can. No partial log output, no leaving things out because they had no output or it didn't seem relevant.

Finally, if it's still a problem, open `xdebug_on` and run each command manually to inspect the output, and post that too in a gist, complete with the commands themselves
