### ISSUE TITLE
No SSH client in Windows may be preventing first vagrant up.

### ISSUE THREAD

**Issue by lgedeon** [Varying-Vagrant-Vagrants/VVV#891] opened 2016-05-03 13:13 UTC
I am helping someone over the phone so I am a little blind, but he is trying to install VVV on his Windows 8 home edition which does not come with an ssh client. He installed PuTTY and verified that it is in the path.

He is getting stuck at a timeout waiting to connect via ssh both during the first vagrant up and all subsequent attempts.

We are going to try another destroy tonight, but in the mean-time I wanted to see if any one else is familiar with what it takes to get VVV working on Windows.

I am concerned that he skipped PuTTYtel because it was not part of the default package. Could that make a difference?

Can lack of an SSH client prevent vagrant up? I will record my journey here for posterity and welcome any feedback.

**Comment by lgedeon** [comment] 2016-05-03 13:18
This always happens to me. :) I have to open a ticket before I find the answer. I searched. I really did. Anyway this will make it easier for others to find.

We are going to try this tonight: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/887#issuecomment-216073284

I will let you know if it works.

**Comment by xicomatos** [comment] 2016-07-22 11:17
I'm having this error on my machine. Can anyone help me solving this? Thanks

An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

**Comment by jpmclaughlin** [comment] 2016-07-22 18:36
I get the exact same error as xicomatos (above).

**Comment by jeremyfelt** [comment] 2016-08-17 05:10
I'm going to close this in favor of #887, which appears to be the same thing.

**Closed by jeremyfelt** 2016-08-17 05:10 UTC
