### ISSUE TITLE
PHPUnit takes at least 30 seconds to run

### ISSUE THREAD

**Issue by kyletozer** [Varying-Vagrant-Vagrants/VVV#1653] opened 2018-10-18 23:44 UTC
## Expected Behavior
PHPUnit tests execute fairly quickly when run from inside of the VM.

## Current Behavior
PHPUnit tests, even on a freshly scaffolded plugin using `wp scaffold my-plugin plugin` take at least 30 seconds to run and on average take about 35-40 seconds to complete.

## Possible Solution
Not sure at this time. So far, I have tried a full reinstall of VVV on my system.

## Steps to Reproduce (for bugs)

1. scaffold a new plugin with unit tests, I followed this guide: https://make.wordpress.org/cli/handbook/plugin-unit-tests/
2. run phpunit and wait for tests to complete

I can provide a log upon request, just let me know which log might be useful in solving the issue

## Context

This issue has slowed down my workflow quite substantially.

## Your Environment

* VVV version: 2.3.0
* VVV Git Branch: master and develop
* Vagrant version: 2.2.0 
* VM Provider name: VirtualBox
* VM Provider version: 5.2.12
* Operating System and version: Ubuntu 18.04.1 LTS

**Comment by LoreleiAurora** [comment] 2018-10-18 23:48
How much memory/many cores are assigned to your vm?

The default is
```
vm_config:
  memory: 2048
  cores: 1
```
When changing this setting you must `vagrant reload`

**Comment by kyletozer** [comment] 2018-10-18 23:58
@LoreleiAurora Currently I have the same settings in my vvv-custom.yml file. I'm going to update my original post just to include that I have already tried doing a full wipe and reinstall of VVV to my knowledge.

**Comment by LoreleiAurora** [comment] 2018-10-19 00:03
Try bumping these as below as the defaults are bare minimums
```
vm_config:
  memory: 4096
  cores: 2
```

then `vagrant reload`

**Comment by kyletozer** [comment] 2018-10-19 00:30
Thanks for the suggestion @LoreleiAurora, however these changes did not seem to have an effect. Another little tidbit about what I am experiencing is that "Installing..." is displayed to me in the terminal when running phpunit tests for the majority of the execution. Hope that might help!

**Comment by fklein-lu** [comment] 2018-11-10 15:58
This is likely not a bug with VVV, but an undesired side effect of how the WordPress Unit Test Case base class handles existing media files in the `uploads` directory.

Try inserting this code snippet in your plugin's `bootstrap.php` file:
```php
tests_add_filter( 'upload_dir', function( $dir ) {
	array_walk( $dir, function( &$item ) {
		if ( is_string( $item ) ) {
			$item = str_replace( '/uploads', '/test-uploads', $item );
		}
	} );

	return $dir;
} );
```

This snippet must be placed before the `require_once $wp_tests_dir . '/includes/bootstrap.php';` line which loads the bootstrap file of the WordPress unit testing framework.

Let me know whether this fixes it.

**Comment by kyletozer** [comment] 2018-11-12 23:29
> This is likely not a bug with VVV, but an undesired side effect of how the WordPress Unit Test Case base class handles existing media files in the `uploads` directory.
> 
> Try inserting this code snippet in your plugin's `bootstrap.php` file:
> 
> ```
> tests_add_filter( 'upload_dir', function( $dir ) {
> 	array_walk( $dir, function( &$item ) {
> 		if ( is_string( $item ) ) {
> 			$item = str_replace( '/uploads', '/test-uploads', $item );
> 		}
> 	} );
> 
> 	return $dir;
> } );
> ```
> 
> This snippet must be placed before the `require_once $wp_tests_dir . '/includes/bootstrap.php';` line which loads the bootstrap file of the WordPress unit testing framework.
> 
> Let me know whether this fixes it.

Unfortunately, this did not fix it. I did however try the same thing on another Ubuntu computer of mine and I did not have the same delay issue when running tests, which completed in under 2 seconds. I will post the specs of that environment:

VVV version: 2.4.0
VVV Git Branch: master
Vagrant version: 2.2.0
VM Provider name: VirtualBox
VM Provider version: 5.2.12
Operating System and version: Ubuntu 18.04.1 LTS

Let me know if there is anything else that I can do or try to aid in diagnosing this issue. So far, I'm still having the issue on the original computer, but the same issue is not present on another computer using almost the exact same environment.

**Comment by Mte90** [comment] 2018-11-13 08:30
I think that is part of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1464

**Comment by tomjn** [comment] 2018-11-13 15:08
Can we have a comparison with non-VM speeds? It could just be that the tests are slow, not the VM

Indeed it is possible to simply run PHPUnit on the host

**Comment by tomjn** [comment] 2019-08-06 23:11
I'm closing this out, as I could not reproduce:

1. I created a plugin using `wp scaffold plugin test`
2. I ran `bash bin/install-wp-tests.sh wordpress_test root 'root' localhost latest` in the plugin folder
3. I ran `phpunit`

results:

```
vagrant@vvv:/srv/www/wordpress-one/public_html/wp-content/plugins/test$ phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.



Time: 2.77 seconds, Memory: 24.00MB

No tests executed!
```

2.77s is much better than ~30. It might be that moving to VVV 3 and using the new Ubuntu 18 box has greatly improved this, but eitherway I'm unconcerned with VVV 2.x issues as it's no longer supported

**Closed by tomjn** 2019-08-06 23:11 UTC
