### ISSUE TITLE
Stop all updates on new site provision or vagrant up

### ISSUE THREAD

**Issue by topdown** [Varying-Vagrant-Vagrants/VVV#952] opened 2016-08-03 20:34 UTC
First I want to say I believe in this project 100%.
But that is fading because every time I create a new site in VVV or do a vagrant up there is a days worth of debugging to get it working again.

The **biggest** issue is updates...
I want it to update when I tell it to, not on every vagrant up or provision. This breaks things every time. I have not restarted my Mac in a month because of this.

This is a huge problem since all of us using VVV use it for WP development, which is my job.
Having to fix VVV setup every time is not efficient.

So without reading through all of the code, I want to know how to setup VVV to not update anything ever, unless I tell it to. This would not only speed up the process of provisioning and vagrant up but would mean that I could deal with things breaking when I have time.

I got lucky this time, a new site created needed 2 vagrant ups and a vagrant reload to get it working agin. But a lot of the time its much worse.

EDIT: I was wrong, broke again.
Example: this is what my last 24 hours look like not counting vm commands and new boxes.
```
: 1470254037:0;cd ~/wp-vagrant
: 1470254053:0;vv create
: 1470255155:0;vagrant up
: 1470255314:0;vagrant reload
: 1470256638:0;vagrant halt
: 1470257069:0;vagrant up
: 1470263097:0;cd wp-vagrant
: 1470263103:0;vagrant up
: 1470265339:0;vagrant reload
: 1470283153:0;vagrant ssh
: 1470284860:0;vagrant up --provision
: 1470285369:0;vagrant reload
: 1470285423:0;vagrant up --provision
: 1470287548:0;vagrant up --provision >> log.txt
: 1470288672:0;vagrant ssh
: 1470289987:0;vagrant hault
: 1470289997:0;vagrant halt
: 1470290597:0;vagrant -v
: 1470290609:0;vagrant plugin install vagrant-hostsupdater
: 1470290682:0;vagrant plugin install vagrant-triggers
: 1470290704:0;vagrant plugin install vagrant-vbguest
: 1470290738:0;vagrant up
: 1470294186:0;vagrat up --provision
: 1470294197:0;vagrant up --provision
: 1470294289:0;vagrant halt
: 1470294365:0;vagrant plugin install vagrant-triggers
: 1470294390:0;vagrant up --provision
: 1470294539:0;vagrant provision
: 1470294559:0;vagrant up --provision
: 1470323132:0;git checkout master
: 1470323139:0;git pull origin master
: 1470323149:0;git status
: 1470323155:0;vagrant up --provision
: 1470323210:0;vagrant provision
: 1470325680:0;vagrant ssh
: 1470326071:0;vagrant provision
: 1470326610:0;vagrant ssh
: 1470327414:0;vagrant provision
: 1470327594:0;vagrant halt
: 1470327767:0;vagrant provision
: 1470328002:0;pwd
: 1470328012:0;git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git local-wp
: 1470328025:0;vagrant up
: 1470328060:0;cd local-wp
: 1470328180:0;vagrant provision
: 1470328261:0;vagrant ssh
: 1470328605:0;vagrant plugin install vagrant-hostsupdater
: 1470328629:0;vagrant plugin install vagrant-triggers
: 1470328652:0;vagrant plugin install vagrant-vbguest
: 1470328679:0;vagrant up
: 1470328939:0;cd wp-vagrant
: 1470329419:0;vagrant halt
: 1470330225:0;vagrant up
: 1470330974:0;vagrant provision
: 1470333942:0;vagrant halt
: 1470334003:0;vagrant up
: 1470334587:0;git clone git@github.com:topdown/VVV-Dashboard.git dashboard
: 1470334626:0;cp dashboard/dashboard-custom.php .
: 1470334877:0;vv create
: 1470335216:0;cd ../../../
: 1470335221:0;cd wp-vagrant
: 1470335226:0;vagrant halt
: 1470335318:0;cd ../local-wp
: 1470335323:0;vv --path
: 1470335333:0;vv --update
: 1470335454:0;pwd
: 1470335473:0;vv --path /Users/jeff/local-wp
: 1470335492:0;vv -p
: 1470335499:0;vv --path /Users/jeff/local-wp
: 1470335508:0;vv create
: 1470336277:0;cd wp-vagrant
: 1470336282:0;vagrant halt
: 1470336524:0;vv
: 1470336682:0;flip
: 1470336710:0;flip set quick
: 1470336718:0;vv create
```

So 2 days later I have a working VVV again all over creating a new site in VVV.
All updates should  be completely disabled and only done when using a flag to specifically update.

**Comment by jeremyfelt** [comment] 2016-08-05 16:36
Hi @topdown, thanks for opening an issue! I'm bummed things aren't working for you. It's helpful to see this kind of feedback.

After the initial `vagrant up`, the VM should not be updating anything unless `vagrant provision` or `vagrant up --provision` is run. Provisioning itself does update a handful of things by design in order to keep software up to date.

That said, there are a handful of things that update during provisioning that we may want to not update - default WordPress repos, etc... But any software packages should be included.

When running `vagrant up` or `vagrant reload`, only one small provisioning script runs to restart the mysql and nginx services. If running `vagrant up` after `vagrant halt`, there should be no additional provisioning.

Can you provide some more detail on what broke and what is updating during the process above? Also, what version of VVV are you using?

**Comment by topdown** [comment] 2016-08-05 19:24
Hello @jeremyfelt,
Thanks for the reply. I have been using VV for creating sites for some time.
I have not compared its provision script to the default one in VVV.
What I do know at this point is I have a running VVV again.
I had to delete the box and all the data folders, eg .vagrant stuff, which I have had to do before.
Then started fresh, which you can see in the last half of my command logs above.
I still had to run provision, halt, etc.. multiple times to get past the errors to get it to be fully setup.

After that I re-setup VV changing the paths to the new VVV location, then stripped its provision-custom.sh down to minimal required when creating a new site and running provision. It has no outside calls, no update checks or anything in it, including removing WordPress SVN.

https://gist.github.com/topdown/edae3d23a3944c484530fa56740f2482

I'm hoping that with this custom provision script I am using this all goes away and I can only update when I know I have time to deal with potential issues.

I couldn't possible list the issues I have has, since its pretty much most of them here in the issues list that I have read through and tried over the last year. You name it, grunt not found, mysql command does not exist, permission issues, etc...
The issues are inconsistent which is the biggest problem.
2 months ago when I was in a jam like this I did this to get back up and running.
https://gist.github.com/topdown/6ee7c237b300a0cda03717ccc69599cd

Which I found by fixing each issue to only get another and kept going until it was running.
Then copied my commands to that gist. I can work through the errors usually and get it running, but its frustrating when your on the job and trying to work.

Also and biggest fear that I have with VVV, are a lot of people less involved in tech/command-line/programming that walk away from VVV because of issues like this that was just to much for them.

If you are on a sketchy internet connection (out in the sticks) like me it can make things unstable for updates and procedural installing processes. IE. internet hickups while installing grunt or updating mysql, etc...

**Comment by jeremyfelt** [comment] 2016-08-06 02:42
Are you on the master or develop branch of VVV? (or tied to a specific version number)

I would like to get better error reporting and sequential provisions in at some point. This could even mean a move to a more proper provisioner. See #509, #320 for some discussion around that.

**Comment by topdown** [comment] 2016-08-06 03:34
Well long story short,
I was on the original repo, I think 10up before VVV became its own Org.
I know it was not this one. Then when you announced PHP7 I was confused as to why I could not see it and discovered that there was no redirect on the old repo which I thought was automatic.

Switching repos with the same box and everything blew up then, big time.
Once I got that sorted I was good for a while but still could not get the `develop` branch working here. So I was on `master` with PHP5.

Yesterday after replacing everything and starting over I am now on `develop` with PHP7.
But like I said, it took multiple provisions to get it working.

Today I did some reading through provision scripts and discovered that the updating issue is a shared one between VVV, VV and Flip. They all do it. `apt get update`

https://github.com/bradp/VVV-Provision-Flipper/blob/master/scripts/sample#L160  to 
https://github.com/bradp/VVV-Provision-Flipper/blob/master/scripts/sample#L164

The package_install function https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L212

And I think VV just uses the default provision script unless a custom one exists.

On top of these updates, which are terrible most of the time because of hangups or whatever there is the default WP install updates that happen every time which can break things if they hang and don't complete then the provision exits with errors.

I think the default setup for the provisioner should have more flags and functions.
Something like
```
# Absolute basics
vagrant provision
# System updates
vagrant provision --update
# Update default WP installs
vagrant provision --wp
# Run all for install
vagrant provision --install
```
This would give it separation and speed for daily stuff.
It would also make things less likely to break in a daily work flow, but still allow updating if a person decides they want to tackle any issues that may arise.

**Comment by jeremyfelt** [comment] 2016-08-21 01:41
I'm going to close this and focus on #753 to help speed up the process of adding custom sites. I may open another ticket or two to track some things that we can do to better clarify what types of provisioning run where.

Thanks very much for the feedback @topdown!

**Closed by jeremyfelt** 2016-08-21 01:41 UTC
Labels: reporter-feedback
