### ISSUE TITLE
Not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by shahrukhmlk** [Varying-Vagrant-Vagrants/VVV#1219] opened 2017-06-13 00:31 UTC
## Expected Behavior

I should be able to access any of the *.dev sites

## Current Behavior

Everything works fine vagrant up downloads the box and sets it up, but whenever I try to access any of the *.dev sites, it doesn't connect. Sometimes "Refused to connect" error is shown. When the internet is not connected it displays offline error. I have tried every possible troubleshooting steps like reinstalling, clearing cache and other things. it works absolutely fine on Ubuntu 16.04 and 16.10.

## Steps to Reproduce (for bugs)

1. Install Ubuntu 17.04l
2. Download and install Vagrant 1.9.5, Virtualbox 5.1.
3. Clone install VVV
4. Fire vagrant up
5. Try to access any *.dev sites

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1
* Operating System and version: Ubuntu 17.04

**Comment by rahulsprajapati** [comment] 2017-06-19 04:45
+1 
same issue.

**Comment by shahrukhmlk** [comment] 2017-06-20 23:49
Please help us out. We are stuck and not able to update Ubuntu due to this issue.

**Comment by tomjn** [comment] 2017-07-03 21:32
A few questions:

 - Does updating to Vagrant 1.9.6 fix the issue?
 - Can you SSH into the box via `vagrant ssh`?
 - If so can you confirm that the hosts entries are all present, and that there are no firewall issues?
 - Does it always indicate 'refused to connect? Or only sometimes?
 - Can the box be pinged?
 - Can you confirm it has a different network IP to the host machine?
 - Does connecting directly to that IP give a connection refused, or does it attempt to redirect to a .dev URL?
 - If you can SSH into the box, does restarting the nginx service inside the box correct the issue?

**Comment by Caseylyndesign** [comment] 2017-07-04 17:05
HI,

I too am having this issue. I had to completely reinstall my Vagrant, VirtualBox, and VVV on my MacOS, and after doing all the steps and creating a new site I cannot access any *.dev sites.

My setup is:
Vagrant - 1.9.6
VVV - 2.0
Ubuntu - 14.04.5

I get the following issue when trying to access any of my .dev sites:

"This site can’t be reached
This site on the company, organization or school intranet has the same URL as an external website.
Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION"

To answer your questions:

- I have 1.9.6
- Yes I can SSH
- looking at the host file, it appears that the site is available.

- I can ping localhost and that works but pinging *.dev does not work.
`Request timeout for icmp_seq 0`

- hosts file on the server is below.
```127.0.0.1       vvv     vvv
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
127.0.0.1 workwealthy.dev # vvv-auto
127.0.0.1 local.wordpress.dev # vvv-auto
127.0.0.1 local.wordpress.dev # vvv-auto
127.0.0.1 src.wordpress-develop.dev # vvv-auto
127.0.0.1 build.wordpress-develop.dev # vvv-auto
127.0.0.1 src.wordpress-develop.dev # vvv-auto
127.0.0.1 build.wordpress-develop.dev # vvv-auto```

- I am unsure about the IP address
- connecting to localhost & 127.0.0.1 works
- restarting the nginx service inside ssh does nothing.

**Comment by m-e-h** [comment] 2017-07-26 15:26
I'm running Ubuntu 16.04 (elementary os) and experiencing this as well.

**Comment by LoreleiAurora** [comment] 2017-07-26 15:31
Can you please try disabling dnsmasq
1. `sudo gedit /etc/NetworkManager/NetworkManager.conf`
1. Comment out the `dns=dnsmasq` line by putting a hash `#` in front it.
1. `sudo service network-manager restart`

**Comment by m-e-h** [comment] 2017-07-26 16:17
Unfortunately @LoreleiAurora it's still a no go.

**Comment by Caseylyndesign** [comment] 2017-07-26 16:44
same here @LoreleiAurora ... I have a mac...

**Comment by LoreleiAurora** [comment] 2017-07-26 17:43
@Caseylyndesign if you are having this issue on a mac please open a seperate issue as the OP is on Ubuntu.

**Comment by m-e-h** [comment] 2017-07-26 17:47
I'm using chrome but I've also tried with Firefox.

**Comment by Caseylyndesign** [comment] 2017-07-26 17:53
@LoreleiAurora I am sorry as I am new to this stuff... but I am using vagrant which is using my virtual box running ubuntu on the VM, while running VVV.

I am just trying to better understand what is wrong so that I can fix this issue and use my local machine again.

**Comment by LoreleiAurora** [comment] 2017-07-26 18:04
@m-e-h what ip does `ping local.wordpress.dev -c 3` return?

**Comment by m-e-h** [comment] 2017-07-26 18:08
```
▲ ~ ping local.wordpress.dev -c 3
PING local.wordpress.dev (192.168.50.4) 56(84) bytes of data.

--- local.wordpress.dev ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2031ms
```

**Comment by LoreleiAurora** [comment] 2017-07-26 18:12
Do you get the dashboard if you visit `192.168.50.4`?
what is the output of `vagrant status`

**Comment by m-e-h** [comment] 2017-07-26 18:18
No dashboard with that ip.
the `vagrant status`: `default     running (virtualbox)`

I'm looking through my `systemd` running processes now. I remember doing some weird stuff troubleshooting bluetooth a while ago that may be effecting something. I'll post here if I find something.

**Comment by LoreleiAurora** [comment] 2017-07-26 18:22
run `sysctl net.ipv4.ip_forward`
If it return 0 run `sudo sysctl -w net.ipv4.ip_forward=1`
If that solves the problem change this setting in /etc/sysctl.conf to persist it.

**Comment by m-e-h** [comment] 2017-07-26 18:58
That had no affect. Wonder if this is a clash with all Ubuntu desktops or just a certain setup? 
I've used VVV about every day until this started maybe a week or two ago (Just got back from time off this week so can't remember exactly). 
I'm guessing it was an Ubuntu update because I don't see anything too related in the VVV recent commits.

**Comment by LoreleiAurora** [comment] 2017-07-26 19:01
The issue is actually that the host machine can't route to the subnet where the virtual box IP resides. Personally I can't yet reproduce this.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by petemmason** [comment] 2017-07-27 15:53
I'm having exactly the same issues here on a fresh VVV 2 installation: Ubuntu 16.04.2, VirtualBox 5.1.24, Vagrant 1.9.7

I can't ping 192.168.50.4, or visit it in a browser. I can ssh into the box via `vagrant ssh`.

I *can* ping 192.168.50.1, and visiting it in my browser shows the root page of the host machine's web server.

I've tried the `dns=dnsmasq` and `sysctl net.ipv4.ip_forward` commands above, which had no effect.

**Comment by LoreleiAurora** [comment] 2017-07-27 16:08
Can you please post the output of `netstat -rn`

**Comment by petemmason** [comment] 2017-07-27 16:26
Sure, thanks...

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.1.254   0.0.0.0         UG        0 0          0 enp6s0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 enp6s0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 enp6s0
```

**Comment by LoreleiAurora** [comment] 2017-07-27 16:29
Can you please post the output of `ip link`

**Comment by petemmason** [comment] 2017-07-27 16:32
Here:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether bc:ae:c5:90:03:95 brd ff:ff:ff:ff:ff:ff
6: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
```

**Comment by m-e-h** [comment] 2017-07-27 16:34
@LoreleiAurora Are you asking to run these from the vagrant or from the host machine?

**Comment by LoreleiAurora** [comment] 2017-07-27 16:39
The host machine, but i now know what the issue is :)
# The issue
This is a Virtualbox issue in which it lacks permissions to set up `vboxnet0` properly.
# The temporary solution
Running `sudo ip link up vboxnet1` after vagrant up should fix this for now. ([Source](https://unix.stackexchange.com/a/261559))
# The permanent solution
This was fixed in Virtualbox [literally 5 minites ago](https://www.virtualbox.org/ticket/16911#comment:25).

**Comment by petemmason** [comment] 2017-07-27 18:14
Fantastic - that worked! Thanks, @LoreleiAurora :)

The syntax was slightly different: `sudo ip link set vboxnet0 up`
but I can now see the VVV dashboard at http://vvv.dev/ !

**Comment by m-e-h** [comment] 2017-07-27 18:14
@LoreleiAurora You're my hero! Thanks a ton for digging into this issue!
I think the guy in the Stack Exchange thread made a typo. `up` isn't an option at that place in the command. I used `sudo ip link set vboxnet0 up` and it did the trick.

**Comment by LoreleiAurora** [comment] 2017-07-27 18:15
@m-e-h Corrected :)

**Closed by LoreleiAurora** 2017-07-27 18:15 UTC
Labels: support
