### ISSUE TITLE
Some packages aren't installing

### ISSUE THREAD

**Issue by mattorourke** [Varying-Vagrant-Vagrants/VVV#2207] opened 2020-07-07 10:01 UTC
## What was The Command Used To Provision

```shell
vagrant up
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

Some packages have mismatched hashes and are not installing

[provisioner-main.log](https://gist.github.com/mattorourke/88650ae1dd2921ca3ed05e70aea60def#file-provisioner-main-log)

config.yaml

```yaml
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant reload --provision

# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://mysite.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #mysite:
  #  description: "My website"
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - mysite.test

  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team, .e.g WordCamps, .org, etc:
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

# Utilities https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- nvm # Node Version Manager
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73
    #- php74

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 2048
  # CPU cores:
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false

  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  provider: virtualbox
  # provider: hyperv
  # provider: parallels
  # provider: vmware_desktop

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

```

## Possible Solution

I've SSh-ed into the server and ran `sudo apt-get clean`, 'sudo apt-get update', `sudo apt-get upgrade` - no results
Tried on a different network - no results

## Steps to Reproduce (for bugs)

1. Clone develop branch
2. Run `vagrant up`

[Console output from `vagrant up`](https://gist.github.com/mattorourke/d12b1868869dbe97987264439c864a24)

## Your Environment

System setup:

macOS Catalina 10.15.5
VVV - v3.5.0-git::develop
Vagrant 2.2.9

**Comment by Mte90** [comment] 2020-07-07 10:08
Seems mainly an issue with ubuntu repo and we cannot do anything for that.
Did you tried again a vagrant up?

**Comment by tomjn** [comment] 2020-07-07 10:22
It's the mismatched hashes thing again.

The TLDR:

 1. Apt repo has packages at v1
 2. VVV user starts a provision
 3. Apt repo mantainers begin updating to v2
 4. VVV user triies to download packages
 5. repo maintainers finish updating to v2

Because the VM tried to download the packages in the middle of an update of the apt repo, it got caught in the middle of the update cycle, so what it got and what it expected didn't match

**Comment by tomjn** [comment] 2020-07-07 10:28
Closing this as a duplicate of #2208 

There are 2 fixes for this that both require manual intervention:

 1. SSH into the VM using `vagrant ssh` and run `sudo rm -rf /var/lib/apt/lists/*` then reprovision
 2. Or destroy the VM and recreate it using `vagrant destroy --force && vagrant up --provision`

**Closed by tomjn** 2020-07-07 10:28 UTC

**Comment by mattorourke** [comment] 2020-07-07 10:58
@tomjn So after running those commands, I'm still getting the same error. Is this a case of notifying whoever's hosting the packages?

**Comment by tomjn** [comment] 2020-07-07 10:59
No I don’t think there’s anything at their end.

Rerun the rm command then follow it up with sudo apt-get clean And
reprovision

**Comment by mattorourke** [comment] 2020-07-07 11:08
@tomjn Same error, it looks like it's failing at the same place.

[Most recent log](https://gist.github.com/mattorourke/d27547fe9b2c82ae16afe557077e517f)

**Comment by mattorourke** [comment] 2020-07-07 15:47
This was caused by using [Screen Time](https://support.apple.com/en-us/HT210387) on Catalina 10.15.5.

Disable this in System Preferences > Screen Time > Options > Turn Off

<img width="925" alt="System Preferences view on macOS Catalina 10.15.5 highlighting Screen Time" src="https://user-images.githubusercontent.com/17767884/86803497-f3a70900-c06d-11ea-96bb-41c43d3b88a1.png">

<img width="780" alt="System Preferences view on macOS Catalina 10.15.5 in the Screen Time options menu. Turn Off button is in the top right" src="https://user-images.githubusercontent.com/17767884/86804381-c73fbc80-c06e-11ea-8b2e-00b628f2f7d7.png">
