### ISSUE TITLE
How to make Microsoft Edge work with VVV sites

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/VVV#1523] opened 2018-05-24 17:23 UTC
Microsoft Edge has network problems, especially for unusual network stuff. It's impossible to see a VVV site in Edge. It's a known issue, just google for "Edge Hmmm... cannot reach this page" and you will find tons of reports and suggestions. 99% of them didn't work for me.

![screenshot 3](https://user-images.githubusercontent.com/1682452/40501201-7c383c7a-5f87-11e8-979d-00e0cf44e9df.png)

It's an Edge bug, nothing wrong with Virtualbox and VVV.

Eventually, I've found a solution but it requires to edit a Windows registry key, For people who need to test with all browsers, worth considering to document the fix. See this comment:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10142843/#comment-8
> You can workaround this issue by changing your VirtualBox Host-Only Ethernet Adapter’s "*NdisDeviceType" to 0 and rebooting. You can find the key in Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\00XX. The downside to this is that now you’ll have an “Unidentified Network” in your Network and Sharing Center. It’s also managed by Windows Firewall now and by default it is in the Public Profile and it can’t be really changed easily.

For me, the path to the registry key was slightly different and ended with `\0016`, I guess the commenter meant to search in any of the sub-folders that start with `00`. The key to edit is `*NdisDeviceType` (it really starts with an asterisk) and needs to be changed from 1 to 0.

Being a registry edit, people should really know what they're doing, so in any case a registry backup, or bookmarking the key to easily find it again and revert would be highly recommended.

What I'd suggest:
- ask other people to test if the fix works for them too
- make a decision if documenting the fix would be beneficial
- maybe provide a `.reg` file to change the key

**Comment by tomjn** [comment] 2018-05-24 18:38
What's the error message it gives under details? As an aside, the src
subsisting is going away due to changes in core development, you should use
build instead

**Comment by afercia** [comment] 2018-05-24 19:33
> What's the error message it gives under details

It's the very enlightening `INET_E_RESOURCE_NOT_FOUND`.

As said, this isn't a Virtualbox / Vagrant / VVV issue. All other browsers on Windows 10 work. Edge doesn't. I always had this problem also on another Windows machine. However, I really need to test on all browsers using different assistive technologies, and I guess other developers would like to test with Edge too. This fix is the only one that worked for me.

I'm aware of the changes in core related to the build step, thanks 🙂

**Comment by benlumia007** [comment] 2018-05-24 20:06
am i imagining this, i thought that edge worked before... if it didn't, no one actually tested Edge?

**Comment by dingo-d** [comment] 2018-05-25 07:58
I always recommend using [Browsersync](https://browsersync.io/) for cross-browser testing (`config.vm.network :public_network` uncommented ofc).

After a simple setup (example [here](https://github.com/infinum/wp-boilerplate/blob/master/webpack.config.js#L77)), just run `npm start` and work on any browser, mobile phone etc.

**Comment by afercia** [comment] 2018-05-25 08:06
@dingo-d thanks. As said, personally I need to test with all browsers using various assistive technologies (e.g. screen readers), and Browsersync doesn't help.

**Comment by dingo-d** [comment] 2018-05-25 08:17
Oh, yeah, in that case, this is a big issue.

**Comment by benlumia007** [comment] 2018-07-17 22:00
i did more test on this... because I usually install windows 10 on virtualbox and target 192.168.50.4/192.168.50.1 as a second adapter... It seems like if I were to install the SSL or non SSL and using Microsoft Edge, I can actually use it. 

see below

![image](https://user-images.githubusercontent.com/11844123/42847812-1627b60c-89d2-11e8-9b89-75a1110588e9.png)

so it got me curious. what's the difference.

**Comment by benlumia007** [comment] 2018-07-17 22:01
so the image above is under VirtualBox running Windows 10 Pro.

**Comment by benlumia007** [comment] 2018-07-17 22:13
![untitled](https://user-images.githubusercontent.com/11844123/42848308-e54464c0-89d3-11e8-856a-cbce39d3c872.png)

**Comment by tomjn** [comment] 2018-08-13 20:49
None, I don't know much about MS Edge

**Comment by Mte90** [comment] 2019-05-08 10:41
It is still happening? we have to consider that the new versions of edge now use chromium engine.

**Comment by afercia** [comment] 2019-05-08 11:00
We'll see 🙂It's not related to the rendering engine. It's a Microsoft network "feature".

**Comment by benlumia007** [comment] 2019-05-28 17:36
so i tested the new Edge, its the same thing.

**Comment by jimboobrien** [comment] 2019-07-11 17:51
What progress has been made on this? Is the provided workaround with editing the registry the only fix for now?

**Comment by benlumia007** [comment] 2019-07-11 23:37
i think the way to fix this is to edit the registry, can we document this in the documentations.

**Comment by tomjn** [comment] 2020-04-14 09:24
Is this still an issue? Edge for MacOS appears to run fine:

<img width="1440" alt="Screenshot 2020-04-14 at 10 21 56" src="https://user-images.githubusercontent.com/58855/79208611-2c9e5b80-7e3a-11ea-9f9f-04cf671d6bfc.png">

**Comment by afercia** [comment] 2020-04-14 13:57
> Is this still an issue? 

As mentioned previously, this isn't related to the browser's engine. It's a Microsoft network "feature" that "works" only with Edge. Not sure how the new Edge will behave.

**Comment by benlumia007** [comment] 2020-04-14 14:57
can we have people test the new Edge on Windows? I have tested on 3 different computers with Windows 10 Home/Pro and it works fine.

**Comment by afercia** [comment] 2020-04-15 06:44
Worth reminding WordPress supports the last 2 versions of major browsers, including the last 2 Edge versions.

https://github.com/WordPress/wordpress-develop/blob/72f54ba785949876c79836723c129c8757dec0f1/package.json#L15-L26

https://github.com/WordPress/packages/blob/5e4f4f4cd977c113eb219b63cc82283efb5c8514/packages/browserslist-config/index.js#L11

**Comment by benlumia007** [comment] 2020-04-15 18:02
I don't think that matters right now! The whole point right now is to have people test the new Microsoft Edge that is based on Chromium. If we can get people to test without problem on Edge even if there are some small issues, it can still display sites and which the whole point of this ticket.

@tomjn: I think we should just close this ticket because no one will use Edge as much as we should be doing testing on, but that's just me.

**Comment by tomjn** [comment] 2020-04-15 18:22
Ah I was hoping that the new Edge might have bypassed this issue being Chromium based. The worst that happens is we end up with a less suboptimal situation, a little more info doesn't hurt

**Comment by jimboobrien** [comment] 2020-04-15 18:28
I'll try testing this again at some point today hopefully.

**Comment by jimboobrien** [comment] 2020-04-15 23:07
I just upgraded an old VVV environment from 2.2.0 to 3.3.0 and `vagrant destroy` then `vagrant up` and still do not see vvv.test loading in Edge on Windows 10. It does load in chrome and IE. I guess I could try a whole new VVV environment.

**Comment by jimboobrien** [comment] 2020-04-15 23:32
It does not work with a fresh VVV 3.3.0 install on Edge on Windows 10, It does work in IE and chrome. Dang you windows. Dang you. This is why I use linux most of the time for development anyways. Please let me know if I can be more helpful in testing.

**Comment by benlumia007** [comment] 2020-04-16 01:11
@jimboobrien 
did you upgrade to the new Microsoft Edge (https://www.microsoft.com/en-us/edge/), if you didn't is not going to work. You need to update to the new Edge
![image](https://user-images.githubusercontent.com/11844123/79403678-6a87a680-7f44-11ea-857e-8468cde1b40b.png)

@tomjn: this is why I open a new ticket with the latest URL to download the new Edge. if we continue here. no one is gonna know to download the new Microsoft Edge.

**Comment by benlumia007** [comment] 2020-04-16 01:21
I am going to point out that when most of the people who are using Windows 10, you can download the new Microsoft Edge (https://www.microsoft.com/en-us/edge/), this update will replace the old Microsoft Edge that is the core of Windows 10. Please download and install the new Edge browser before making assumptions if it works or not. 

I have recently tested on 3 different Windows 10 systems and the new Microsoft Edge works without any configurations whatsoever.

**Comment by jimboobrien** [comment] 2020-04-16 01:33
Confirmed, once I upgraded Edge to newest version it does work in Edge now. I was on 44.1 I believe before I upgraded.

**Comment by Mte90** [comment] 2020-12-16 11:02
Now that edge is based on webkit this ticket maybe can be closed as a lot of things are changed?

**Comment by tomjn** [comment] 2020-12-16 12:41
@msaggiorato what do you think? I know you're on Windows at the moment

**Comment by tomjn** [comment] 2023-01-19 16:35
closing

**Closed by tomjn** 2023-01-19 16:35 UTC
Labels: type:bug, help-wanted, os:windows
