### ISSUE TITLE
Setting environment variables in php-fpm?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1533] opened 2018-05-30 08:02 UTC
I'm wondering how to add environment variables that will be available in my WP app to use with 

```php
getenv( 'MY_ENV_VAR' );
```

I was reading [this](https://stackoverflow.com/questions/47646012/how-to-set-an-environment-variable-in-vagrant-that-php-can-access?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) but that doesn't seem ideal (especially if I'll have duplicates on every provision) plus I think it's targeting apache, and VVV is running on nginx.

Can they be added in the `vvv-custom.yml`? 

Also one thing I noticed in the answer above is that the env variables added that way, are just added in the .bashrc. I'd like to add them to PHP_FPM, which probably means that I should change the `php-fpm.conf` file.

I also tried [this](https://stackoverflow.com/a/35708931/629127) way, and manually added 

```sh
; Env variables
clear_env = no
env[TEST] = 'test env var'
```

to my `/etc/php/7.2/fpm/php-fpm.conf` and I restarted the php-fpm with `sudo service php7.2-fpm restart` but no luck.

Any help is appreciated.

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: develop
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.12 r122591 (Qt5.6.3)
* Operating System and version: MacOS HighSierra 10.13.4 (17E202)

**Comment by dingo-d** [comment] 2018-05-30 10:15
So I've added

```sh
  config.vm.provision "shell", inline: <<-SHELL

  # Set environment variables...
  echo "export TEST_ENV=development" >> /etc/environment
  SHELL
```

Which works when I do `printenv`, but not when I do `getenv('TEST_ENV')`.

My guess is that the `/etc/php/7.2/fpm/php-fpm.conf` gets rewritten on provision and I'm losing the `clear_env = no` which makes it unavailable for `getenv()`.

**Comment by tomjn** [comment] 2018-05-30 13:11
Does `putenv` not work for you? PHP conf files get replaced on every provision by design, as they're managed by Utilities

Otherwise, Nginx is the route you should take, e.g.

https://stackoverflow.com/questions/8098927/nginx-variables-similar-to-setenv-in-apache#8331663

I'm going to close this for now though as it's a general Nginx question, nothing that needs VVV specific knowledge

**Closed by tomjn** 2018-05-30 13:11 UTC

**Comment by dingo-d** [comment] 2018-05-30 13:52
You mean put the variables in the `vvv-nginx.conf` via `location` parameters?

**Comment by tomjn** [comment] 2018-05-30 14:37
Yeah:

```
   fastcgi_param   APPLICATION_ENV  production;
   fastcgi_param   APPLICATION_CONFIG user;
```

**Comment by dingo-d** [comment] 2018-05-31 08:33
I'm getting errors when provisioning

> default: nginx: [emerg] invalid variable name in /etc/nginx/nginx.conf:126
default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I'm not using custom site template (old project) so I added in the `vvv-nginx.conf`

```sh
server {
    listen       80;
    listen       443 ssl;
    server_name  test-site.test;
    root         {vvv_path_to_site}/public_html;

    error_log    {vvv_path_to_site}/log/error.log;
    access_log   {vvv_path_to_site}/log/access.log;

    set          $upstream {upstream};

    include      /etc/nginx/nginx-wp-common.conf;

    location ~ \.php$ {
        fastcgi_param APP_ENV 'production';
        ... bunch of others
    }
}
```

**Comment by tomjn** [comment] 2018-05-31 20:17
hmmm if you didn't already have a `vvv-nginx.conf` file your old project should not have been able to load, it looks like you've made a mistake or a typo somewhere, and the config is no longer valid Nginx config syntax. I recommend the standard Nginx linting tactics such as `nginx -t`
