### ISSUE TITLE
Provisioning fails for MariaDB

### ISSUE THREAD

**Issue by 1bigidea** [Varying-Vagrant-Vagrants/VVV#1788] opened 2019-05-08 14:45 UTC
I appreciate that this has been a difficult week re: VVV. Once I discovered that the issues I have been chasing all weekend were being "known" - I have been trying to provision my setup (unsuccessfully).

## Expected Behavior
After Vagrant Destroy and git checkout develop & git pull with a vagrant up --provision - I should be able to see vvv.test

## Current Behavior
Provisioning fails with 
```
    default: Processing triggers for php7.2-fpm (7.2.18-1+ubuntu18.04.1+deb.sury.org+1) ...
 INFO interface: detail: Errors were encountered while processing:
 INFO interface: detail:     default: Errors were encountered while processing:
    default: Errors were encountered while processing:
 INFO interface: detail: 
 mariadb-server-10.3
 mariadb-server
 INFO interface: detail:     default: 
    default:  mariadb-server-10.3
    default:  mariadb-server
    default: 
    default:  mariadb-server-10.3
    default:  mariadb-server
DEBUG ssh: stderr: E
 INFO interface: detail: E
 INFO interface: detail:     default: E
    default: E
DEBUG ssh: stderr: : 
 INFO interface: detail: : 
 INFO interface: detail:     default: : 
    default: : 
DEBUG ssh: stderr: Sub-process /usr/bin/dpkg returned an error code (1)
 INFO interface: detail: Sub-process /usr/bin/dpkg returned an error code (1)
 INFO interface: detail:     default: Sub-process /usr/bin/dpkg returned an error code (1)
    default: Sub-process /usr/bin/dpkg returned an error code (1)
DEBUG ssh: stderr: 

 INFO interface: detail: Main packages check and install failed, halting provision
 INFO interface: detail:     default: Main packages check and install failed, halting provision
    default: Main packages check and install failed, halting provision
```

## Steps to Reproduce (for bugs)

```
vagrant destroy
git checkout develop
git pull
vagrant up --provision --debug
```

The full output of `vagrant up --provision --debug` is in this gist:
https://gist.github.com/1bigidea/17b068ffed12709bd2c8ef8c149b88b0

## Context

Trying to get my development system back up and running.

## Your Environment

* VVV version: v3.0.0-git::develop
* VVV Git Branch: Develop (as of this AM)
* Vagrant version: 2.2.4
* VM Provider name: Virtualbox
* VM Provider version: Version 5.2.28 r130011 (Qt5.6.3)
* Operating System and version:

**Comment by tomjn** [comment] 2019-05-08 14:50
Thanks for the provison log with the `--debug` parameter, this looks like the same issue as #1773 

The current theory is that overlapping shared/mounted folders causes problems ( inconsistently too ), and that's the cause behind this. I believe we've eliminated all but 1 overlap, which should be fixed in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1784, it's just pending further tests to verify that provisioning isn't broken by that PR

**Comment by tomjn** [comment] 2019-05-09 15:13
I'm closing this as a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1773 we can continue on that issue

**Closed by tomjn** 2019-05-09 15:13 UTC
Labels: bug, help wanted
