### ISSUE TITLE
MySQL with SSH tunnel results to fatal error

### ISSUE THREAD

**Issue by kmgalanakis** [Varying-Vagrant-Vagrants/VVV#1867] opened 2019-06-19 06:00 UTC
In my case the MySQL connection information provided [here](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Connecting-to-MySQL-MariaDB#ssh-tunnel) are no longer relevant.

I'm using HeidiSQL, which fails to connect to my VMs mariadb with an error message:

```
PLink exited unexpected. Command line was:
"c:\Program Files\PuTTY\plink.exe" -ssh vagrant@vvv.test -pw "vagrant" -N -L 3307:127.0.0.1:3306
```

When running this command from the command line, I get

```
"c:\Program Files\PuTTY\plink.exe" -ssh vagrant@vvv.test -pw "vagrant" -N -L 3307:127.0.0.1:3306
Using username "vagrant".
FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
```

Note that the exact same configuration was working properly with my previous VM.

**Comment by tomjn** [comment] 2019-06-19 07:39
None of the details are different, they should work the same assuming a
working VM

**Comment by kmgalanakis** [comment] 2019-06-19 09:01
Apparently it seems that the VM is not working properly and also I cannot figure out why. 

Anyway...

**Comment by tomjn** [comment] 2019-06-19 09:02
The VM is working fine, it's just full. At this point the standard Linux
process of figuring out what's taking up space applies

**Comment by kmgalanakis** [comment] 2019-06-19 09:06
I understand, but does it make sense for this disk to 3GB when the machine first boots and then, in 1-2 hours of usage to take all the space it has, reaching to 9.7GB?

I mean something is acting weird, right?

**Comment by tomjn** [comment] 2019-06-19 09:30
Without knowing what those extra GB are composed of I couldn't say

This might help:
https://askubuntu.com/questions/317338/how-can-i-increase-disk-size-on-a-vagrant-vm#318711

**Comment by Mte90** [comment] 2019-06-20 14:13
I think related with #1466 but we can close it now

**Comment by tomjn** [comment] 2019-06-20 14:24
@kmgalanakis now that we've a potential solution for the VM filling with data, does that mean that Heidi now connects ok? As an aside, is it possible to save a Heidi SQL configuration to a file? If so, and it works for you I'd like to see it :)

**Comment by kmgalanakis** [comment] 2019-06-21 09:29
OK, I did various tests and everything failed, MySQL connection through ssh tunnel is not working anymore.

Below I'm attaching the configuration file of HeidiSQL.

[heidisql_conf.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3313823/heidisql_conf.txt)

I think that this issues is similar to the one that I can no longer connect to my VVV machine using `ssh vagrant@vvv.test`. When executing this command, `vagrant@vvv.test: Permission denied (publickey).` while I was able to connect with that in the past.

**Comment by tomjn** [comment] 2019-06-21 09:34
That's not how you wouldn't normally SSH, vagrant ssh is how you'd do that.
Otherwise anything in your SSH config will be out of date after the VM is
recreated.

Additionally you provide no password in your SSH command, and the Heidi SQL
config implies the SSH password is 786369746370762 which is incorrect. The
SSH password should be vagrant IIRC, but if in doubt there are extremely
thorough sequel pro instructions on the doc site, all the same values
should work with Heidi SQL

**Comment by kmgalanakis** [comment] 2019-06-21 09:47
I know you wouldn't normally SSH to your vagrant VM like that. I'm just saying it used to work and now it's not and the reason is that an SSH authentication method with a password is not available.

```
FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
```

Now when HeidiSQL tries to connect using an SSH tunnel, it issues this command

```
"c:\Program Files\PuTTY\plink.exe" -ssh vagrant@vvv.test -pw "vagrant" -N -L 3307:127.0.0.1:3306
```

which apparently fails without any further explanation. (of course the password is hashed, so in my case I see `*******` and this is the reason you see `786369746370762` in the configuration file, but in the UI I clearly use `vagrant`)

So when I try to type this very same command in my command line, I get the exact same error

```
FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
```

**Comment by Mte90** [comment] 2019-06-22 10:04
So the issue is that you are using the psw to login with ssh and we disabled.
I think that is something that you can change as example with https://askubuntu.com/questions/204400/ssh-public-key-no-supported-authentication-methods-available-server-sent-publ so we can see if it is something that we need to fix or can be done manually (or adding an option).

**Comment by kmgalanakis** [comment] 2019-06-22 11:20
I know that if I add my public key in the VVV VM, it will work as it is in any linux machine, but this is not the case.

IMO this needs to be fixed in VVV because otherwise connecting to MySQL will be a feature that won't work out of the box and this is a problem of course.

**Closed** 2019-06-27 15:22 UTC
Labels: bug, mariadb

**Comment by kmgalanakis** [comment] 2019-06-27 19:12
Just confirming the fix. Thanks ❤️
