### ISSUE TITLE
hosts not updated through hostsupdater

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1459] opened 2018-04-04 00:34 UTC
Apparently for some reason the hostsupdater isn't doing its job on one of my computers. I have done the same steps as if i were to do a clean install of everything else.

1. vvv 2.2.0 (develop) master
2. virtualbox 5.2.8
3 vagrant 2.0.3

all of my computers are working great, just one of them isn't doing its job for some reason.  

I have ever or never seen this before until today.  Please see the following
![20180404_002848979_ios](https://user-images.githubusercontent.com/11844123/38282432-f0fc7cce-3764-11e8-9684-f5832f1b27c3.jpg)

This only happens when you vagrant up the system and trying to write hostsupdater automatically, but it doesn't.  i ahve install triggers and hostsupdater plugin as usual. 

strange, very strange.

**Comment by tomjn** [comment] 2018-04-04 00:36
Looks like you've updated to the very latest version of the hostsupdater plugin

Closing as a duplicate of #1458

**Closed by tomjn** 2018-04-04 00:36 UTC

**Comment by benlumia007** [comment] 2018-04-04 01:24
yup, i figured it out,, i just rolled back to the 1.0.2 for now. 

thanks.
