### ISSUE TITLE
Standard install doesn't work; results in "Server not found" errors

### ISSUE THREAD

**Issue by davidrhoderick** [Varying-Vagrant-Vagrants/VVV#1628] opened 2018-08-31 02:39 UTC
## Expected Behavior
I follow the installation at https://varyingvagrantvagrants.org including installing VirtualBox and Vagrant at correct version numbers, git clone the master branch, and vagrant up results in being able to visit vvv sites.

## Current Behavior
Installation goes without interruption (there are some MariaDB issues but we haven't even gotten that far yet).  I can include the installation log if that helps.

## Possible Solution
If there are dependencies that should be 

## Steps to Reproduce (for bugs)
See the steps at https://varyingvagrantvagrants.org/docs/en-US/installation/ for git installation.  I don't customize anything and just hit vagrant up and I don't see my sites.

I also tried to use the development branch but the SSH command responded with a non-zero exit status and aborts.

## Context
Trying to use VVV on my new Linux laptop.

## Your Environment
* VVV version: v2.2.1-git
* VVV Git Branch: master
* Vagrant version: 2.1.3
* VM Provider name: VirtualBox
* VM Provider version: 5.2.18
* Operating System and version: Pop!_OS 18.04 LTS (should be similar to Ubuntu)

**Comment by tomjn** [comment] 2018-08-31 02:40
Update to Vagrant 2.1.4 or downgrade to 2.1.2

**Comment by benlumia007** [comment] 2018-08-31 03:48
@davidrhoderick 
we had a ticket open is now closed, same situation, please update to Vagrant 2.1.4 or downgrade to Vagrant 2.1.2 

duplicate of #1626 and #1627

**Comment by tomjn** [comment] 2018-09-02 00:26
I'm going to close this out, it's a known problem with Vagrant 2.1.3, and only 2.1.3, due to a botched release by the vagrant team.

Update to Vagrant v2.1.4, or downgrade to v2.1.2

**Closed by tomjn** 2018-09-02 00:26 UTC
Labels: support
