### ISSUE TITLE
Trusty64 not found

### ISSUE THREAD

**Issue by curtismchale** [Varying-Vagrant-Vagrants/VVV#354] opened 2014-05-08 22:11 UTC
I just pulled from master and the latest change to the default ubuntu box isn't found when I type `vagrant up`.

I rolled it back manually to `precise32` and problems were resolved.

![screen shot 2014-05-08 at 3 06 22 pm](https://cloud.githubusercontent.com/assets/74561/2922135/58f51ac4-d6fd-11e3-90c9-0a4645489bea.png)

**Comment by firecentaur** [comment] 2016-02-08 05:27
I was using windows 7 and trying to get vagrant up to work - kept getting trusty not found, so finally I followed this https://stackoverflow.com/questions/34848146/vagrant-error-the-box-hashicorp-precise32-could-not-be-found-windows-10-d/34848147#34848147 and that solved the problem!

**Comment by mrosen** [comment] 2016-02-08 18:38
Ditto for firecentaur's note.  I'm also Win7/x64 / vagrant 1.8.1 and got the same vague error message about "'ubuntu/trusty64' could not be found."  For me it was resolved by installing the VC10 x86 runtimes:  https://www.microsoft.com/en-us/download/details.aspx?id=8328

**Comment by waqariz** [comment] 2016-07-11 06:52
Just installing [VC ++ 2010 x86](https://www.microsoft.com/en-us/download/details.aspx?id=8328)  has resolved my issue on win 8.1 with vagrant 1.8.4

**Comment by bside** [comment] 2016-08-04 21:42
@waqariz +1, you are goddamn right

**Comment by GhostofGoes** [comment] 2016-08-26 22:02
The solution @mrosen provided fixed this on Windows 10 x64 with Vagrant 1.8.5.

**Comment by knesbit** [comment] 2016-11-08 18:37
I'm using mac os v 10.12.1 - i removed the curl that was packaged with vagrant in /opt/vagrant/embedded/bin so that it would use the version installed by the os and it fixed the problem for me.

**Comment by alexander-marquardt** [comment] 2016-11-09 16:48
Usinx OSX 10.11.6, I had the same problem and followed the suggestion of @knesbit to remove the vagrant version of curl, which fixed the problem.

**Comment by imansyaefulloh** [comment] 2016-11-10 06:30
I had the same problem and @kensbit solution worked for me.

**Comment by romcheg** [comment] 2016-11-10 12:38
@knesbit's solution worked well for me.

**Comment by morfien101** [comment] 2016-11-10 23:06
@knesbit solution worked for me also. Well done on fixing that 👍

**Comment by Malu44** [comment] 2016-11-11 17:07
Same for me: @knesbit solution solves my problem 👍

**Comment by cfoellmann** [comment] 2016-11-11 21:23
Can anyone write this up for the wiki?

**Comment by pcleddy** [comment] 2016-11-11 22:58
Un. Believable.

**Comment by retailify** [comment] 2016-11-15 10:49
Same for me: @knesbit solution solves my problem 👍

**Comment by ihorvorotnov** [comment] 2016-11-15 12:36
As suggested by @knesbit, removing vagrant's curl fixes the issue on macOS Sierra (10.12.1). Thanks!

**Comment by sc0ttkclark** [comment] 2016-11-15 15:28
Yeah just ran into this issue, removing the Vagrant curl resolved it -- `sudo rm /opt/vagrant/embedded/bin/curl`

**Comment by Altonymous** [comment] 2016-11-15 17:40
I'm on El Capitan, and removing the embedded curl worked for me as well.

**Comment by jeremyfelt** [comment] 2016-11-15 17:48
It looks like there were a couple waves of possibilities on this ticket. I'm going to reopen as something that should be documented more officially as an FAQ.

**Comment by mkjonesuk** [comment] 2016-11-15 20:26
Same here, on OSX Yosamite 10.10.5 (14F2009) - deleting the curl file fixed the vagrant up step

**Comment by killua99** [comment] 2016-11-17 22:09
Confirm on macOS latest Sierra.

**Comment by joncoe** [comment] 2016-11-17 22:31
Confirming this issue exists and @knesbit solution works.

**Comment by nervewax** [comment] 2016-11-18 09:46
@mkjonesuk Just ran into this same issue this morning!
`sudo rm /opt/vagrant/embedded/bin/curl` fixed it for me too.

**Comment by skrenes** [comment] 2016-11-18 19:14
How is this an issue from May 8, 2014 and still not resolved? Brand new computer with MacOS Sierra and executing `sudo rm /opt/vagrant/embedded/bin/curl` fortunately worked for me too.

**Comment by pcleddy** [comment] 2016-11-18 19:31
Over-extended employees is my guess.

**Comment by sc0ttkclark** [comment] 2016-11-18 22:13
This issue is a Vagrant issue, it didn't have anything to do with VVV specifically for me (FYI)

**Comment by mkjonesuk** [comment] 2016-11-18 22:18
Agreed - this is nothing to do with vvv. I eventually downgraded to an older version of Vagrant and no longer have the problem.

**Comment by knowge** [comment] 2016-11-19 21:48
I am on El Capitan, `sudo rm /opt/vagrant/embedded/bin/curl` worked for me too. Thanks!

**Comment by denitto** [comment] 2016-11-21 16:12
Thanks @knesbit.  Is it possible someone committed this folder accidentally?

**Comment by needkane** [comment] 2016-11-22 11:49
sudo rm /opt/vagrant/embedded/bin/curl worked for me too.Thanks

**Comment by bhu08** [comment] 2016-11-23 12:24
Thanks @knesbit. Removing curl solved it for me!

**Comment by killua99** [comment] 2016-11-23 16:44
We should point this issue to vagrant project tho.

**Comment by skrenes** [comment] 2016-11-23 17:30
It looks like the Vagrant development team is aware of this issue but have been dragging their feet at releasing Vagrant 1.8.8:
https://github.com/mitchellh/vagrant/issues/7969

**Comment by Dayjo** [comment] 2016-11-24 09:38
Needed to run this today (`sudo rm /opt/vagrant/embedded/bin/curl`) on OSX on Vagrant 1.8.7

**Comment by f1gjam** [comment] 2016-11-24 11:42
Had to run 

sudo rm /opt/vagrant/embedded/bin/curl 

MacOS 10.12.1
Vagrant 1.8.7

**Comment by wallnerryan** [comment] 2016-11-29 20:01
+1 this is quite annoying but `sudo rm /opt/vagrant/embedded/bin/curl` works

**Comment by johnantoni** [comment] 2016-12-03 03:31
was getting the same:

```
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
```

but doing this as @wallnerryan commented fixed it for me,

    sudo rm /opt/vagrant/embedded/bin/curl

**Comment by andreyors** [comment] 2017-02-11 11:53
I had HTTP2 custom curl enabled for my dev environment,

sudo rm /opt/vagrant/embedded/bin/curl works

**Comment by tomjn** [comment] 2017-11-03 17:51
I'm going to close this one out now that a solution appears to have been found. If anybody encounters this on the newer VVV 2 and replicate on the `develop` branch, please open a new ticket

**Closed by tomjn** 2017-11-03 17:51 UTC
Labels: documentation, vvv.org

**Comment by Amyavow** [comment] 2018-02-09 13:40
I tried everything. I was on fresh install of Windows 10 and Vagrant 1.9, so I downloaded curl for windows. I also removed the curl in C:/Vagrant/embedded/ . And like @robvdl suggested, I made sure I was downloading the right box. It finally worked.
config.vm.box = "ubuntu/trusty64"
config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

**Comment by tomjn** [comment] 2018-02-09 14:39
Ah the current version of Vagrant at the moment is 2.0.2, you should uninstall 1.9 then do a clean upgrade to 2.0.2

**Comment by rajupydi** [comment] 2018-02-11 16:07
$ vagrant box add ubuntu/trusty64
==> box: Loading metadata for box 'ubuntu/trusty64'
    box: URL: https://vagrantcloud.com/ubuntu/trusty64
==> box: Adding box 'ubuntu/trusty64' (v20180201.0.1) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20180201.0.1/providers/virtualbox.box
==> box: Box download is resuming from prior download progress
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by rajupydi** [comment] 2018-02-11 16:07
how to fix it

**Comment by tomjn** [comment] 2018-02-12 01:39
@rajupydi did you use a USB drive on a contributor day to setup a VVV install, at any point on your machine, even if you then deleted everything?

If so, you need to remove the ubuntu/trusty64 box then try again.

If not, then I don't know, that's a generic Vagrant issue, not a VVV issue.

Again, make sure you are on the latest version of Vagrant, the current latest version is 2.0.2. If in doubt, uninstall Vagrant and install the latest version ( vagrantup.com )

**Comment by tomjn** [comment] 2018-02-12 01:40
Just to repeat:

**If anybody encounters this on the newer VVV 2 and replicate on the develop branch, please open a new ticket**

**Comment by Ayush97Didwaniya** [comment] 2018-05-04 07:39
it will fix your error.  
run command "vagrant destroy". 
use version 5.18 of virtual box.
then install version 1.9.2 of vagrant.
restart your computer.
now go to the directory you want to work in.
"vagrant init ubuntu/trusty64" run command.
"vagrant up" run command.
