### ISSUE TITLE
Network connection not detected when provisioning

### ISSUE THREAD

**Issue by salvatoredibenedetto** [Varying-Vagrant-Vagrants/VVV#1215] opened 2017-06-06 14:21 UTC
## Expected Behavior

Provisioning

## Current Behavior

I get the following output in my terminal:
https://gist.github.com/salvatoredibenedetto/8fc3b3dc1139d30d2d72748d1d8e6233

## Possible Solution

It looks like that the Vagrant Virtual Machine is not able to connect to my wifi network.

## Steps to Reproduce (for bugs)

1. Run from terminal vagrant up --provision
2. After getting the error described in the output pasted up, i run from the terminal  `network_detection` function who is declared in the `provision/provision.sh` and i get: `Network connection detected...`
3. Then run `vagrant ssh` and from the vagrant shell run again the function `network_detection` and this time i get `Network connection not detected. Unable to reach google.com...`
4.

## Context

Just trying to do the first provisioning

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.22 r115126 (Qt5.6.2)
* Operating System and version: HOST: Mac OS Sierra 10.12.5 - GUEST: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-119-generic x86_64)

**Comment by tomjn** [comment] 2017-06-06 22:01
@salvatoredibenedetto can you confirm the Virtual Machine has network adaptors in Virtual Boxes management interface, and can you confirm the IP it wants to use is not already in use?

**Comment by salvatoredibenedetto** [comment] 2017-06-07 07:06
@tomjn Here's a screenshot of the Virtual Box network management interface.
First tab: 
<img width="736" alt="schermata 2017-06-07 alle 08 59 29" src="https://user-images.githubusercontent.com/13942385/26866024-b09fa792-4b5f-11e7-8834-19f7eda4e85c.png">

Second tab:
<img width="730" alt="schermata 2017-06-07 alle 09 02 15" src="https://user-images.githubusercontent.com/13942385/26866123-18793bc6-4b60-11e7-82a1-6b5a8eacb071.png">

To be honest i don't know how to check the IP usage...
But if it can help i ran a `vagrant up --debug &> vagrant.log` and here's the output:
https://gist.github.com/salvatoredibenedetto/97f9af3483a56345bbcef9ba4754c8d8

**Comment by tomjn** [comment] 2017-06-07 11:25
@salvatoredibenedetto has this VM ever worked or is it a fresh first time run? Have you tried destroying the box and recreating it from scratch?

```
# make sure this is the latest VVV
git pull
# Turn off the machine
vagrant halt
# Destroy the machine
vagrant destroy
# Make sure we use the latest version of the base box§
vagrant box update
# Make sure the recommended vagrant plugins are installed
vagrant plugin install vagrant-triggers vagrant-vbguest vagrant-hostsupdater
# And that they're all up to date
vagrant plugin update
# Start VVV and create the VM from scratch
vagrant up --provision
```

I'm assuming you're running on the `master` branch?

**Comment by salvatoredibenedetto** [comment] 2017-06-07 12:37
@tomjn Yes the branch is master.
I followed your instructions but it didn't changed the problem.
Here's the output of my first `sudo vagrant up --provision` :
https://gist.github.com/salvatoredibenedetto/b1e908e0d871461dd0f37ece88f8283e

**Comment by jbarbaran** [comment] 2017-06-09 15:20
It is duplicated issue #1192

**Comment by MTset** [comment] 2017-06-27 00:13
Hi @tomjn, I was having very similar problems with SSH no longer working when trying to bring up a VB VM with Vagrant and I can confirm your solution posted above worked for me. Cheers!

**Comment by swashata** [comment] 2017-07-23 06:37
This has happened to me as well. Strangely when I use `vagrant up`, then ssh into the box and ping test, it works. Then while vagrant is running, I do `vagrant provision` and it works.

This happened to me when I was adding a site using Variable VVV.

**Comment by tomjn** [comment] 2017-07-23 11:06
@swashata I don't believe vv supports VVV 2 at the moment, you're best modifying `vvv-custom.yml` and re-provisioning instead, it's much cleaner/simpler

**Comment by swashata** [comment] 2017-07-23 13:19
@tomjn That could be. But when vagrant is not running and I do a `vagrant provision` or `vagrant up --provision` then it fails with Network unreachable. But when vagrant is running and I do a `vagrant provision` then it passes.

It is worth mentioning that I have the following networking configuration set:

```ruby
  config.vm.network "private_network", type: "dhcp", auto_config: true
  config.vm.network :public_network, type: "dhcp", auto_config: true
```

This gives the following output inside vagrant:

```text
eth0      Link encap:Ethernet  HWaddr 08:00:27:1f:d5:f2
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe1f:d5f2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:69657 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29818 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:59062722 (59.0 MB)  TX bytes:2881252 (2.8 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:49:d1:28
          inet addr:172.28.128.3  Bcast:172.28.128.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe49:d128/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:350394 errors:0 dropped:0 overruns:0 frame:0
          TX packets:286279 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:170928854 (170.9 MB)  TX bytes:146709162 (146.7 MB)

eth2      Link encap:Ethernet  HWaddr 08:00:27:00:38:e0
          inet addr:192.168.1.128  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fdd8:2445:4e60:0:a00:27ff:fe00:38e0/64 Scope:Global
          inet6 addr: fe80::a00:27ff:fe00:38e0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:40190 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5758 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8646611 (8.6 MB)  TX bytes:11677710 (11.6 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:128 errors:0 dropped:0 overruns:0 frame:0
          TX packets:128 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:70190 (70.1 KB)  TX bytes:70190 (70.1 KB)
```

Previously vagrant was unable to connect to internet so I had this script running

```ruby
 # default router
  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw 192.168.1.1 eth2 && ifconfig eth2 mtu 1480"
```

But for some reason, setting a default gateway now makes thing unreachable, so I have just removed them and everything works.

PS: I have the private network along with public network because of the following reasons:

I use [WinNFSd](https://github.com/winnfsd/winnfsd) along with [Vagrant::WinNFSd](https://github.com/winnfsd/vagrant-winnfsd) to have my sync folders through NFS.

```ruby
  # /srv/database/
  #
  # If a database directory exists in the same directory as your Vagrantfile,
  # a mapped directory inside the VM will be created that contains these files.
  # This directory is used to maintain default database scripts as well as backed
  # up MariaDB/MySQL dumps (SQL files) that are to be imported automatically on vagrant up
  # config.vm.synced_folder "database/", "/srv/database"
  config.vm.synced_folder "database/", "/srv/database", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1']

  # If the mysql_upgrade_info file from a previous persistent database mapping is detected,
  # we'll continue to map that directory as /var/lib/mysql inside the virtual machine. Once
  # this file is changed or removed, this mapping will no longer occur. A db_backup command
  # is now available inside the virtual machine to backup all databases for future use. This
  # command is automatically issued on halt, suspend, and destroy if the vagrant-triggers
  # plugin is installed.
  if File.exists?(File.join(vagrant_dir,'database/data/mysql_upgrade_info')) then
    if vagrant_version >= "1.3.0"
      # config.vm.synced_folder "database/data/", "/var/lib/mysql", :mount_options => [ "dmode=777", "fmode=777" ]
      config.vm.synced_folder "database/data/", "/var/lib/mysql", type: "nfs", mount_options: [ 'rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1' ]
    else
      config.vm.synced_folder "database/data/", "/var/lib/mysql", :extra => 'dmode=777,fmode=777'
    end

    # The Parallels Provider does not understand "dmode"/"fmode" in the "mount_options" as
    # those are specific to Virtualbox. The folder is therefore overridden with one that
    # uses corresponding Parallels mount options.
    config.vm.provider :parallels do |v, override|
      override.vm.synced_folder "database/data/", "/var/lib/mysql", :mount_options => []
    end
  end

  # /srv/config/
  #
  # If a server-conf directory exists in the same directory as your Vagrantfile,
  # a mapped directory inside the VM will be created that contains these files.
  # This directory is currently used to maintain various config files for php and
  # nginx as well as any pre-existing database files.
  # config.vm.synced_folder "config/", "/srv/config"
  config.vm.synced_folder "config/", "/srv/config", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1']

  # /srv/log/
  #
  # If a log directory exists in the same directory as your Vagrantfile, a mapped
  # directory inside the VM will be created for some generated log files.
  # config.vm.synced_folder "log/", "/srv/log", :owner => "www-data"
  config.vm.synced_folder "log/", "/srv/log", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1']

  # /srv/www/
  #
  # If a www directory exists in the same directory as your Vagrantfile, a mapped directory
  # inside the VM will be created that acts as the default location for nginx sites. Put all
  # of your project files here that you want to access through the web server
  if vagrant_version >= "1.3.0"
    #config.vm.synced_folder "www/", "/srv/www/", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
    config.vm.synced_folder "www/", "/srv/www/", type: "nfs", mount_options: [ 'rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1' ]
  else
    config.vm.synced_folder "www/", "/srv/www/", :owner => "www-data", :extra => 'dmode=775,fmode=774'
  end

  vvv_config['sites'].each do |site, args|
    if args['local_dir'] != File.join(vagrant_dir, 'www', site) then
      if vagrant_version >= "1.3.0"
        # config.vm.synced_folder args['local_dir'], args['vm_dir'], :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]
        config.vm.synced_folder args['local_dir'], args['vm_dir'], type: "nfs", mount_options: [ 'rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=1' ]
      else
        config.vm.synced_folder args['local_dir'], args['vm_dir'], :owner => "www-data", :extra => 'dmode=775,fmode=774'
      end
    end
  end
```

It works pretty good and I am able to have symlinks, write lock etc, which in turn doesn't break my `npm install` for my custom projects.

**Comment by swashata** [comment] 2017-07-24 16:23
Bdw, it is also worth noting that I have virtualbox promiscuous mode turned to always for this to work.

**Comment by simplysaru** [comment] 2017-09-02 14:56
Still experiencing the same issues on the master branch and the develop branch. every time I destroyed and recreated the box on both the branches. Here is the log as gist. https://gist.github.com/simplysaru/79f405c7845ebe8ace9ce5b1a7b1d1c0

I am experiencing this issue on MacOS High sierra if that helps with the debug.

**Comment by georgestephanis** [comment] 2017-09-25 15:29
Possibly related: https://github.com/hashicorp/vagrant/issues/8788 ?

**Comment by tomjn** [comment] 2017-11-03 17:30
@simplysaru does this still happen with the latest VVV, Vagrant 2.0, and the latest version of Virtualbox?

**Comment by simplysaru** [comment] 2017-11-05 17:52
@tomjn Nope, it doesn't happen any more with the latest VVV and Latest version of the Virtualbox. Thanks for all the help

**Comment by tomjn** [comment] 2017-11-05 20:24
Awesome :) I'm going to close this one out then

**Closed by tomjn** 2017-11-05 20:24 UTC
Labels: support
