### ISSUE TITLE
 BUG: ntpdate[584]: Can't adjust the time of day: Operation not permitted

### ISSUE THREAD

**Issue by abder** [Varying-Vagrant-Vagrants/VVV#2649] opened 2023-01-03 11:18 UTC
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV or an existing VVV that used to work?

Existing, worked but now broken

### Whats the problem?

I keep getting the following error when creating the VM using `vagrant up` 

ntpdate[584]: Can't adjust the time of day: Operation not permitted

I tried to run the command with `sudo` and that didn't work either 

I have also fixed the date and time in the virtual machine manually following this tutorial, and that didn't work either. 

Any ideas? 

http://blog.peschla.net/2011/09/trouble-with-ntpdate/

### How do we reproduce it?

Just try to setup vvv in mac M1 

### VVV Status screen

```shell
ntpdate[584]: Can't adjust the time of day: Operation not permitted
```

### Which Operating System are you using?

Apple MacOS (Arm/Apple Silicon)

### Which provider are you using?

Parallels (Apple Silicon/Arm)

**Comment by tomjn** [comment] 2023-01-03 11:24
Hello!

I see you didn’t include the VVV status screen and you heavily censored the
terminal output to a single line removing all the context. Can you edit
your issue to contain the information it asked for in full?

**Comment by tomjn** [comment] 2023-01-03 14:06
> http://blog.peschla.net/2011/09/trouble-with-ntpdate/

did you try any of these commands? There are multiple places with the `ntpupdate` command and it's not possible to tell where it happened with such limited output.

I also can't confirm which version of VVV you're on as you didn't share the VVV splash with the commit hash or the version number, and all the other debug data

<blockquote><div><strong><a href="http://blog.peschla.net/2011/09/trouble-with-ntpdate/">Jonas' weblog – Trouble with ntpdate: „Can’t adjust the time of day“</a></strong></div></blockquote>

**Comment by tomjn** [comment] 2023-01-03 14:17
Also you said you were using an existing VM that used to work but is now broken, but then said that you were trying to create a VM, did you skip most of the questions in the issue template?

**Comment by tomjn** [comment] 2023-01-04 15:46
@douara I've checked all the places we use `ntpdate` and they all have checks that print messages if they fail then continue with provisioning.

So this should not be breaking provisioning, we need more information!

They all take this form:

```shell
if [ -x "$(command -v ntpdate)" ]; then
	echo " * Syncing clocks"
	if sudo ntpdate -u ntp.ubuntu.com; then
		echo " * clocks synced"
	else
		vvv_warn " - clock synchronisation failed"
	fi
else
	echo " - skipping ntpdate clock sync, not installed yet"
fi
```

Are you sure this is the actual problem? Or is this just something you saw during provisioning that you're reporting? Or the last thing that popped up in the terminal before the actual problem occurred?

**Comment by tomjn** [comment] 2023-01-04 15:48
Tests here suggest the check is working fine too:

```
❯ if sudo ntpdate -u ntp.ubuntu.com; then echo "yes"; else echo "nay"; fi
Password:
sudo: ntpdate: command not found
nay
```

That was run on MacOS so `ntpdate` isn't present, so the use of `sudo` isn't throwing it off

**Comment by tomjn** [comment] 2023-01-19 16:29
Closing as the reporter has not responded and I can't reproduce the error without downgrading VVV to an older version

**Closed as completed by tomjn** 2023-01-19 16:29 UTC
Labels: type:bug, os:mac, provider:parallels
