### ISSUE TITLE
Modified vvv-nginx.conf.tmpl files get overwritten on reprovision

### ISSUE THREAD

**Issue by h4r1m4u** [Varying-Vagrant-Vagrants/VVV#1842] opened 2019-06-05 18:56 UTC
## Expected Behavior
Reprovisioning should add new site, etc., but it should not revert any changes made to the `vvv-nginx.conf.tmpl` file in existing and already provisioned sites based on the custom site template. 

## Current Behavior
On `vagrant reload --provision`, sites that use the custom site template and that had already been added and provisioned before lose any custom changes made to the `vvv-nginx.conf.tmpl` file. It looks like the custom site template repo gets cloned into the local site folder overwriting the existing files in it. 

## Context
I have a setup that stores my sites outside the main VVV folder. My `vvv-custom.yml` looks like this: 
```
  mysite:
    skip_provisioning: false    
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    vm_dir: /srv/www/mysite
    local_dir: D:/h4r1m4u/Documents/Sites/MySite
    hosts:
      - mysite.test
```
Then instead of the default `public_html` web root, I use a custom one and serve my site from a `repo` folder that I've created inside the `mysite` folder after the initial provision. So the structure of the `mysite` folder looks like this:
```
MySite
  - log
  - provision
  - public_html
  - repo
  README.md
  wp-cli.yml
```
I achieve this by changing the web root folder inside the `provision/vvv-nginx.conf.tmpl` file: `root         {vvv_path_to_site}/repo;`. Once I reprovision, everything should be working and my site should be served from the `repo` folder. 

The issue is that after switching to VVV 3, the changes to the `vvv-nginx.conf.tmpl` file are not persistent and get reset every time I reprovision. I ran the same exact setup in VVV 2.4 and this didn't use to happen. 

The only way I found around this is to comment out the custom site template line in the `vvv-custom.yml` file after the initial provision, so that the template is not used on consequent provisions.  I can live with this, but since the docs specifically advise to modify the `vvv-nginx.conf.tmpl` file and not `vvv-nginx.conf` as the latter gets replaced on next provision, it seems like a bug. 

I did find https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1723 where the same is discussed and I guess the suggested solution to fork the custom template would work, but it seems to defeat the purpose of the `vvv-nginx.conf.tmpl` file. Additionally, having to create and maintain a new fork every time I'd like to use a different name for the custom web root folder seems like an overkill. 

## Your Environment
* VVV version: 3.0
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8
* Operating System and version: Windows 8.1

**Comment by tomjn** [comment] 2019-06-05 19:07
The purpose of `vvv-nginx.conf.tmpl` is so that the provisioner can search replace and generate the actual `vvv-nginx.conf`. Since then the variables it adds for TLS certificates are in the core VVV provisioner. Now that we're on v3 we can probably abandon the `.tmpl` file entirely and remove that code. It was never intended to make human lives easier, but as a technical step.

As an aside, have you considered just eliminating `public_html` then cloning into that folder, instead of a `repo` subfolder? It seems like a lot of effort to go to just to clone a repository, and I'd be highly suspicious of any code that depends on the naming of that folder.

```sh
rm -rf public_html
git clone ..... public_html
```

Otherwise, the best solution is to fork the template, or better yet, put a set of provisioners inside your git repo that you clone, so you can put it directly in `vvv-custom.yml`. The whole point of provisioners is to automate things so that every VVV user doesn't have to download and install WP manually, so why do the steps manually then faff around with Nginx?

**Comment by tomjn** [comment] 2019-06-05 19:12
Specifically https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L124, without this fixes and updates don't get applied. E.g. when SSL support got added nobody would have been able to use it unless it was a new site without this line.

If anybody needs to customise a provisioner, they should use a custom provisioner. I'm going to close this out as it's the intended behaviour

**Closed by tomjn** 2019-06-05 19:12 UTC

**Comment by h4r1m4u** [comment] 2019-06-05 19:26
Thanks for the super fast response, Tom, I really appreciate it.  

> As an aside, have you considered just eliminating public_html then cloning into that folder, instead of a repo subfolder?

I have and I actually tried it. I would love this solution, but the problem with that was that every time I'd run a provision, the `public_html` folder contents would get wiped and replaced with the WP files from the custom template too. 

> Otherwise, the best solution is to fork the template, or better yet, put a set of provisioners inside your git repo that you clone, so you can put it directly in vvv-custom.yml. 

I'm not particularly familiar with the provisioning scripts, so writing my own is unfortunately not feasible for me at the moment. 

> The whole point of provisioners is to automate things so that every VVV user doesn't have to download and install WP manually, so why do the steps manually then faff around with Nginx?

This was the easiest set up that I was able to figure out that let me use VVV with existing client repositories that don't necessarily use VVV and that I can't easily restructure using a fork of the custom site template. Perhaps I need to rethink how I'm doing things and find a better way.

**Comment by tomjn** [comment] 2019-06-05 19:34
> I'm not particularly familiar with the provisioning scripts, so writing my own is unfortunately not feasible for me at the moment.

At the end of `vvv-init.sh` put the commands you'd normally run afterwards. The main difference with a fork is that your changes would be a part of the git history, rather than an uncommitted change to be discarded. Copy pasting the `provision` folder also works

**Comment by h4r1m4u** [comment] 2019-06-05 19:37
Thank you, I appreciate the advice. I'll give it a shot and see what I can figure out.
