### ISSUE TITLE
GZip backups

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2342] opened 2021-01-26 15:30 UTC
The ability to use compressed `.sql.gz` backups instead, e.g.

```yaml
general:
  db_backup:
    # Compress using gzip, db.sql becomes db.sql.gz when true
    gzip: true
```

`db_backup` and the  restore  script will need adjusting

Related to #2225

**Comment by Mte90** [comment] 2021-01-27 14:12
It isn't a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2156?
Or the other one can be closed for this?

**Comment by evertiro** [comment] 2021-05-26 12:53
This was completed two weeks ago and is merged into `develop`; closing.

**Closed by evertiro** 2021-05-26 12:53 UTC
Labels: help-wanted, provisioner:config.yml, provisioner:core, type:feature
