### ISSUE TITLE
Missing support for new vmware_desktop provider, and associated install issues

### ISSUE THREAD

**Issue by nelga** [Varying-Vagrant-Vagrants/VVV#1614] opened 2018-08-20 06:53 UTC
## Expected Behavior
After installation, should be able to launch VVV via the command `vagrant up --provider vmware_desktop`

## Current Behavior
Receiving errors `An error occurred while executing vmrun` when it attempts to enable and configure shared folders. Then receiving `Trigger run failed` errors when attempting to re-up or destroy.

## Steps to Reproduce (for bugs)
1. Install Vagrant (2.1.2), Vagrant VMWare Utility (1.0.2), and the plugin vagrant-vmware-desktop (1.0.4) along with license. 
2. Reboot, and install VVV into sites/vagrant-local via git.
3. Use command vagrant up --provider vmware_desktop and it will attempt to install ubuntu/trusty64, but give the error `The box you're attempting to add doesn't support the provider you requested.`
4. Attempt to use older `vagrant up --provider vmware_fusion` command and everything looks to be working until it reaches `Enabling and configuring shared folders... ` to which it provides the error: 

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/Users/glenmcpherson/Sites/vagrant-local/.vagrant/machines/default/vmware_fusion/06b682e2-eb46-4dcd-90a3-5e592c277ec8/ubuntu-14.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr: 
```
5. Trying to rerun the up command gives the output and error:

```
default: Running triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: /vagrant/config/homebin/vagrant_up: No such file or directory
==> default: Trigger run failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Context
Unable to launch VVV, hostnames do not resolve. I am also unable to seemingly destroy the box, and receive the following:
```
==> default: Running triggers before destroy ...
==> default: Running trigger: VVV Pre-Destroy...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: /vagrant/config/homebin/vagrant_destroy: No such file or directory
==> default: Trigger run failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Your Environment
* VVV version: 2.2.1
* VVV Git Branch: Master, but have also tried dev without any difference in results
* Vagrant version: 2.1.2
* VM Provider name: vmware_desktop (and have also tried vmware_fusion)
* VM Provider version: vagrant-vmware-desktop 1.0.4, Vagrant VMWare Utility 1.0.2
* Operating System and version: Mac OS X 10.13.5
* VMWare Fusion: 10.1.3 (9472307)

## Full console output
I've pasted the full terminal output here: https://pastebin.com/mjCYjNkG

**Comment by tomjn** [comment] 2018-08-20 13:05
Sorry to hear, in the meantime i'd recommend using VirtualBox. VMWare support was added  along time ago, and isn't proactively maintained. We rely on users who have a VMWare license to help support and direct the project in how to fix issues.

VirtualBox is the best supported given that it's free and available on all platforms, with the biggest userbase. You might have luck with parallels using the `develop` branch. HyperV will probably work, but other providers are an unknown

**Comment by tomjn** [comment] 2018-08-20 13:18
So the vagrant file references `vmware_fusion` and `vmware_workstation`, but as I mentioned in #1615, there are no resources for maintaining or supporting VMWare based providers. At this moment in time you yourself are the most knowledgeable VMWare person in the project.

I'm going to close this as `wontfix`, nobody knows what the problem is or how to fix it, and nobody is available to test or maintain this. VMWare support is legacy historic code, and I'm inclined to deprecate or remove it until somebody with VMWare expertise offers to maintain and support it

**Comment by tomjn** [comment] 2018-08-20 13:18
As an aside, if you figure out a fix, PR's are still welcome

**Closed by tomjn** 2018-08-20 13:18 UTC
Labels: provisioner:vagrantfile, support

**Comment by tomjn** [comment] 2018-08-25 22:12
@nelga can you try this but using the `tomjn-hyperv` branch in https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1619 ? There are some changes that might impact this too
