### ISSUE TITLE
Bug: On provision remove and reinstall mariadb

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2585] opened 2022-03-08 18:02 UTC
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV or an existing VVV that used to work?

Don't know

### Whats the problem?

```
 default: Reading state information...
    default: The following packages were automatically installed and are no longer required:
    default:   galera-4 libdbi-perl socat
    default: Use 'sudo apt autoremove' to remove them.
    default: The following packages will be REMOVED:
    default:   libmariadb3 mariadb-client-10.5 mariadb-client-core-10.5 mariadb-common
    default:   mariadb-server mariadb-server-10.5 mariadb-server-core-10.5 mysql-common
    default: 0 upgraded, 0 newly installed, 8 to remove and 5 not upgraded.
    default: After this operation, 150 MB disk space will be freed.
(Reading database ... 59119 files and directories currently installed.)
    default: Removing mariadb-server (1:10.5.15+maria~focal) ...
    default: Removing mariadb-server-10.5 (1:10.5.15+maria~focal) ...
    default: Removing mariadb-client-10.5 (1:10.5.15+maria~focal) ...
    default: Removing mariadb-client-core-10.5 (1:10.5.15+maria~focal) ...
    default: Removing libmariadb3:amd64 (1:10.5.15+maria~focal) ...
    default: Removing mariadb-server-core-10.5 (1:10.5.15+maria~focal) ...
    default: Removing mariadb-common (1:10.5.15+maria~focal) ...
    default: Removing mysql-common (1:10.5.15+maria~focal) ...
    default: Processing triggers for man-db (2.9.1-1) ...
    default: Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
    default:  * Removing unnecessary apt packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: The following packages will be REMOVED:
    default:   galera-4 libdbi-perl socat
    default: 0 upgraded, 0 newly installed, 3 to remove and 5 not upgraded.
    default: After this operation, 70.4 MB disk space will be freed.
(Reading database ... 58786 files and directories currently installed.)
    default: Removing galera-4 (26.4.11-focal) ...
    default: Removing libdbi-perl:amd64 (1.643-1ubuntu0.1) ...
    default: Removing socat (1.7.3.3-2) ...
    default: Processing triggers for man-db (2.9.1-1) ...
    default:  * Cleaning apt caches...
    default:  * Checking for apt packages to install.
    default:  * Cleaning up dpkg lock file
    default:  * Updating apt keys
    default: gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
    default: gpg: key 3B4FE6ACC0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
    default: gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
    default: gpg: key D94AA3F0EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" not changed
    default: gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
    default: gpg: key 871920D1991BC93C: "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" not changed
    default: gpg: Total number processed: 3
    default: gpg:              unchanged: 3
    default:  * Running apt-get update...
    default: Get:1 http://deb.nodesource.com/node_14.x focal InRelease [4,583 B]
    default: Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
    default: Get:3 https://nginx.org/packages/mainline/ubuntu focal InRelease [3,596 B]
    default: Get:4 http://deb.nodesource.com/node_14.x focal/main amd64 Packages [773 B]
    default: Fetched 31.6 MB in 8s (3,949 kB/s)
    default: Reading package lists...
    default:  * Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: The following additional packages will be installed:
    default:   galera-4 libdbi-perl libmariadb3 mariadb-client-10.5
    default:   mariadb-client-core-10.5 mariadb-common mariadb-server-10.5
    default:   mariadb-server-core-10.5 mysql-common socat
    default: Suggested packages:
    default:   libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl mailx
    default:   mariadb-test
    default: Recommended packages:
    default:   libdbd-mariadb-perl | libdbd-mysql-perl libhtml-template-perl
    default: The following NEW packages will be installed:
    default:   galera-4 libdbi-perl libmariadb3 mariadb-client-10.5
    default:   mariadb-client-core-10.5 mariadb-common mariadb-server mariadb-server-10.5
    default:   mariadb-server-core-10.5 mysql-common socat
    default: 0 upgraded, 11 newly installed, 0 to remove and 5 not upgraded.
    default: Need to get 27.8 MB of archives.
    default: After this operation, 220 MB of additional disk space will be used.
    default: Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdbi-perl amd64 1.643-1ubuntu0.1 [730 kB]
```

### How do we reproduce it?

Just run a vagrant provision.
My guess is that there are some issues with the package, some dependence are removed and reinstalled again.
Maybe we can switch to mariadb from ubuntu to avoid this issue?

### VVV Status screen

```shell
__ __ __ __
\ V\ V\ V / v3.9.0 Path:"/home/www/VVV"
 \_/\_/\_/  git::php-provision-site(d7666eb)

Platform: linux-gnu shell:/bin/bash systemd  vagrant-goodhosts CaseSensitiveFS shared_db_folder_disabled
Vagrant: v2.2.19, virtualbox: v6.1.32
```

### Which Operating System are you using?

Linux

### Which provider are you using?

VirtualBox

**Comment by Mte90** [comment] 2022-03-10 18:31
So ubuntu 20.04 has mariadb 10.3 https://packages.ubuntu.com/focal/mariadb-server, we can evaluate to switch 22.04 that will have mariadb 10.5.

**Comment by tomjn** [comment] 2022-03-11 13:54
This is a duplicate of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2525

If an older MariaDB is installed and we update, then we can no longer update the old packages because it can't find them, so we need to remove and reinstall MariaDB or something to that effect.

Does not affect new installs

**Closed by tomjn** 2022-03-11 13:54 UTC
Labels: type:bug
