### ISSUE TITLE
Warning: Connection timeout. Retrying...

### ISSUE THREAD

**Issue by jaakkolehtonen** [Varying-Vagrant-Vagrants/VVV#745] opened 2015-09-16 15:06 UTC
![cpbbns2wuaa5bdl png-large](https://cloud.githubusercontent.com/assets/6592690/9908700/815ff534-5c9d-11e5-9fa2-d809099ea525.png)

This happens to me all the time and i've tried everything, is there simple solution to fix this? I even reinstalled the whole OS!

**Comment by TheAggressive** [comment] 2015-09-18 18:31
<code>sudo vagrant up</code>?

**Comment by TheAggressive** [comment] 2015-09-18 19:15
I'm on a windows machine but the same thing would happen to me if I do not run the Git Bash in Administrative Rights Mode.

**Comment by jaakkolehtonen** [comment] 2015-09-19 10:08
Whoah i said ive tried everyting but..... :D I did `sudo vagrant up`and now its up and running! There were something with the ssh keypairs. Thanks a lot!

![nayttokuva 2015-09-19 kello 13 06 02](https://cloud.githubusercontent.com/assets/6592690/9975726/735962f2-5ecf-11e5-9e3c-05a3236e33aa.png)

**Comment by TheAggressive** [comment] 2015-09-19 13:32
Glad it worked for you!

**Comment by jaakkolehtonen** [comment] 2015-09-19 13:40
One more question :) Now i have to do `sudo`on every vagrant command, why is that?

**Comment by jaakkolehtonen** [comment] 2015-09-19 13:43
And i don't know is it normal but vm's aren't showing up in vb's gui!

**Comment by TheAggressive** [comment] 2015-09-19 14:06
sudo is a program for Unix-like computer operating systems that allows users to run programs with the security privileges of another user, by default the superuser. The name is a contraction of "do as su" where "su" is an abbreviation for "super user."

I'm not sure if you have to do it with every vagrant command but if it doesn't work with normal vagrant command throw sudo in there and it should work.

If you open virtualbox using sudo it would show in the GUI. Not on a Mac so not sure how you would do this. Probably a search will show how to sudo open an app.

**Comment by jaakkolehtonen** [comment] 2015-09-19 14:35
It's just bad for plugins because they dont include `sudo`, for example [Variable VVV](https://github.com/bradp/vv).

**Comment by TheAggressive** [comment] 2015-09-19 15:59
They should probably include in there documentation as well as for window users to run as administrator.

**Comment by breadadams** [comment] 2015-09-29 12:15
I'm having a similar issue, was about to start a new thread and noticed this one. I started out with Vagrant and VVV yesterday, and all was working fine. I later turned MBP off and back on again at night, and have been getting the same error since then.

I just now tried removing everything and running through the install again, but same results.

![screen shot 2015-09-29 at 14 02 39](https://cloud.githubusercontent.com/assets/5795227/10163408/18d29920-66b3-11e5-9522-8019e1d36d71.png)

I attempted with `sudo` and get the error that it's not the same user that first created the VM.

I did some reading before posting this and tried a bunch of things, for example disabling wifi returns different results but same outcome, none of the domains are _working_.

Any ideas? :smile_cat:

**Comment by jeremyfelt** [comment] 2015-10-06 03:07
Hey everyone, I'm going to close this as a duplicate of #375. There is quite a bit on that ticket to troubleshoot with. Please feel free to add more there. I think this is more of a Vagrant specific issue, though it's helpful to have conversations like this here as well.

**Closed by jeremyfelt** 2015-10-06 03:07 UTC
