### ISSUE TITLE
Unexpected error when running 'vagrant up' command

### ISSUE THREAD

**Issue by emgk** [Varying-Vagrant-Vagrants/VVV#1207] opened 2017-05-31 20:13 UTC
I am getting error when running 'vagrant up' command, sometime it's works fine sometime not, 

![untitled](https://cloud.githubusercontent.com/assets/14994452/26651466/65b87910-466a-11e7-8ef3-c10f553b5319.png)

I don't know, if this error is coming from VVV, vagrant or VirtualBox. I am posting this issue here, because i didn't find any helpful article or solution on google. 

-------------------------------------
**OS:** Windows 10 ( 64 bit )
**Terminal:** PowerShell (Administrator)
**Vagrant Version:** 1.9.5
**Virtual box:** 5.1.22

## What I have tried:
1. Restarted System.
2. Reinstalled Vagrant & Virtualbox 
3. Re-cloned https://github.com/Varying-Vagrant-Vagrants/VVV/ 

any help would be greatly appreciated ! 👍

**Comment by tomjn** [comment] 2017-11-08 19:38
@emgk does this still happen with VVV 2.1, Vagrant 2.0 and the latest Virtualbox? Make sure you uninstall Vagrant completely before upgrading and reboot, and confirmed virtualisation is turned on in your machines BIOS

**Comment by emgk** [comment] 2017-11-09 05:27
@tomjn I will check it and will let you know ASAP! :)

**Comment by tomjn** [comment] 2017-11-24 23:51
@emgk did you get a chance to test?

**Comment by tomjn** [comment] 2018-01-20 22:23
I'm going to close this issue, if the problem is still there and you can test or reproduce with the latest Windows and develop branch, let us know and we can reopen

**Closed by tomjn** 2018-01-20 22:23 UTC
Labels: support
