### ISSUE TITLE
Unable to use vagrant halt

### ISSUE THREAD

**Issue by tannerchung** [Varying-Vagrant-Vagrants/VVV#1617] opened 2018-08-24 03:23 UTC
## Expected Behavior

`vagrant halt` should shut down vagrant

## Current Behavior

```
$ vagrant halt
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.1-git::master

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

==> default: Running triggers before halt ...
==> default: Running trigger: VVV Pre-Halt...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: /vagrant/config/homebin/vagrant_halt: No such file or directory
==> default: Trigger run failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
## Steps to Reproduce (for bugs)

1. `vagrant halt`

## Context

Trying to halt the server so I can delete it and restart it.

## Your Environment

* VVV version: git
* VVV Git Branch: master
* Vagrant version: 2.1.2
* VM Provider name: Hyper-V
* VM Provider version:
* Operating System and version: Windows 10

**Comment by tomjn** [comment] 2018-08-24 05:47
Did you try it with the develop branch? Always try it with the develop
branch, there's a very high chance this issue has already been fixed

**Comment by tannerchung** [comment] 2018-08-25 00:08
Okay I'll try it

**Comment by tannerchung** [comment] 2018-08-25 00:17
@tomjn I'm getting this now :\

```
$ vagrant up
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.2-develop-git::develop

Platform:   mingw32 HyperV-Admin HasWinAdminPriv
Vagrant:    2.1.2
VirtualBox:

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

Net::SSH::ConnectionTimeout
```
`vagrant halt` gets stuck
```
$ vagrant halt
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.2-develop-git::develop

Platform:   mingw32 HyperV-Admin HasWinAdminPriv
Vagrant:    2.1.2
VirtualBox:

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

==> default: Running triggers before halt ...
==> default: Running trigger: VVV Pre-Halt...
==> default: Trigger run failed
==> default: An error occurred in the underlying SSH library that Vagrant uses.
==> default: The error message is shown below. In many cases, errors from this
==> default: library are caused by ssh-agent issues. Try disabling your SSH
==> default: agent or removing some keys and try again.
==> default:
==> default: If the problem persists, please report a bug to the net-ssh project.
==> default:
==> default: Net::SSH::ConnectionTimeout
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
==> default: Stopping the machine...
```

I'm not sure how to clean out everything and restart the process since I can't get it to halt or destroy it. If I went directly into Hyper-V's management to remove the VM would it cause any issues?

**Comment by tomjn** [comment] 2018-08-25 00:25
Removing it from hyper V's management should work, I'm unsure of the SSH agent error, I'm not a Windows user so I can only advise on what's been raised in issues and equivalent steps in virtualbox

**Comment by tannerchung** [comment] 2018-08-25 00:33
Okay I finally got it to halt.. after waiting like 10 minutes. Then `vagrant destroy worked. I'm going to try and do another vagrant up!

**Comment by tannerchung** [comment] 2018-08-25 03:19
Tried `vagrant up` again after removing everything:

```
$ vagrant up
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.2.2-develop-git::develop

Platform:   mingw32 HyperV-Admin HasWinAdminPriv
Vagrant:    2.1.2
VirtualBox:

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
    default: Successfully imported VM
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Wireless
    default: 2) DockerNAT
    default: 3) Default Switch
    default:
    default: What switch would you like to use? 1
    default: Configuring the VM...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
    default: IP: 192.168.1.75
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.1.75:22
    default: SSH username: vagrant
    default: SSH auth method: password
==> default: Machine booted and ready!
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: account.
    default:
    default: Username: vagrant
    default: Password (will be hidden):

Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.

==> default: Setting hostname...
==> default: Mounting SMB shared folders...
    default: D:/Users/tanner/Projects/vagrant-local/www => /srv/www
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-6d515bff8e846185d50ab8eea3f67808-327f087fac3c82b47d8eca185e95a27e,uid=33,gid=1000,dir_mode=0775,file_mode=0774,forceuid,noperm,nobrl,mfsymlinks //192.168.1.7/vgt-6d515bff8e846185d50ab8eea3f67808-327f087fac3c82b47d8eca185e95a27e /srv/www

The error output from the last command was:

mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

**Comment by tomjn** [comment] 2018-08-25 05:27
And it looks like you have admin priviledges in an escalated shell too, what kind of shell though? Have you tried via the linux subsystem for windows? or an admin power shell?

At this point I'm not sure what else I can suggest

**Comment by benlumia007** [comment] 2018-08-25 18:10
WIndows has a strict policy of keeping stuff with permissions, the sharing part is what I have problems with, I can't figure out what username and password is it for. you can try your windows 10 username and password. 

Is it really easy to create your own box. i really wanna learn too.

**Comment by tomjn** [comment] 2018-08-25 18:14
I had a thought after going on a walk, this block of code in the vagrant file changes the filesystem mounts over from normal vagrant shares to SMB shares:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L436-L453

I doubt the non-SMB style share has been tested in a long time, but it might be worth looking into and testing this with [these lines commented out](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L447-L452)

**Comment by tomjn** [comment] 2018-08-25 21:04
@tannerchung the vbox fs error is almost certainly related to SMB shares, it could even be that SMB shares are turned off on your Windows instance.

For the VM side of things, the vb-guest vagrant plugin has been shown to help in some cases

**Comment by tannerchung** [comment] 2018-08-31 09:01
@tomjn sorry for the late response, for some reason Github is not sending me notifications whenever there's a new comment on thread I'm subscribed to.

I'll try the Linux subsystem on Windows and commenting out the lines suggested. I'm using ConEmu

@benlumia007 Are you talking about the bottom of the log that is using vagrant as the username?

**Comment by benlumia007** [comment] 2018-08-31 14:46
@tannerchung 
yeah,  when is about to mount the shared folder, it tells you to enter an username and  a password.

**Comment by benlumia007** [comment] 2019-05-23 16:14
@tannerchung 

not sure if you have fix the privilege issue, so i found out that if you are trying to mount the file sharing.   if you are using a Microsoft account, you have to use your email address and password, if you are using a local computer username, then that would your username and password.

**Comment by tomjn** [comment] 2019-06-20 14:50
I'm going to close this out, as it's a very old ticket with a very old version of VVV. If it can be reproduced with VVV 3.1+ though, feel free to reopen with a new provision log :)

**Closed by tomjn** 2019-06-20 14:50 UTC
Labels: Windows, provisioner:vagrantfile
