### ISSUE TITLE
VVV Provisioned with Node but without NPM

### ISSUE THREAD

**Issue by Gen-fr** [Varying-Vagrant-Vagrants/VVV#2349] opened 2021-02-03 18:05 UTC
Unable to provisioning with error: ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 105 seconds. The SSH command responded with a non-zero exit status...

## What was The Command Used To Provision

```
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

 - [ubuntu-bionic-18.04-cloudimg-console.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5920537/ubuntu-bionic-18.04-cloudimg-console.log)
 - [provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5920539/provisioner-main.log)

terminal output:

```
    default: /srv/provision/core/grunt/provision.sh: line 16: /usr/bin/npm: No such file or directory
    default:  ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 105 seconds.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
---

```yaml
sites:

  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test


  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

 
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client


vm_config:
  
  memory: 2048
  cores: 2


general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false

vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin
```

## Steps to Reproduce (for bugs)

1. Fresh install
2. It works with  "vagrant up"
3. When I try "vagrant up --provision" got the log above
4.

## Your Environment

host - Debian 10
```
 V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.0-git::develop

Platform: platform-linux-gnu shell:/bin/bash systemd  vagrant-goodhosts vagrant-vbguest CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/home/gen/VVV

Vagrant: v2.2.14, VirtualBox: v6.1.18r142142
```

**Comment by tomjn** [comment] 2021-02-03 18:51
@Gen-fr did you update VVV recently? If I had to guess I might expect this might happen  if you had upgraded VVV but jumped multiple major versions, e.g. 2.0 -> 3.6, or if you  had removed a utility that messed with Node?

Also, what made you reprovision? I don't see anything in your `config.yml` file that would warrant a reprovision, e.g. a new site added.

Are you sure that this was the log from the provision that broke? Not just a follow up provision?

**Comment by Gen-fr** [comment] 2021-02-03 19:19
@tomjn This is very first install, didn't use it before. I caught the error when I tried to add a new site. Then I did destroy and up new environment, I just tried provisioning right away without any changing with config.
Here is one more log
![Screenshot_2021-02-03_22-18-22](https://user-images.githubusercontent.com/78485088/106797545-cce59b00-666d-11eb-97ec-815fbc371ff3.png)

[provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5920889/provisioner-main.log)

**Comment by tomjn** [comment] 2021-02-03 19:47
I've done a fresh `git clone` and provisioned as you did in a fresh folder with these commands:

```
git clone git@github.com:Varying-Vagrant-Vagrants/VVV.git freshvvv
cd freshvvv
vagrant up --provision
```

The result:

```
...
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default:  * Restarting Nginx
    default:  * Restarting MariaDB
    default:  * Syncing clocks
    default:  3 Feb 19:37:45 ntpdate[4304]: adjust time server 91.189.89.199 offset -0.000211 sec
    default: 
    default:   ✧ ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄ ✧  Thanks for  __ __ __ __
    default:    ✧█▒▒░░░░░░░░░▒▒█    using       \ V\ V\ V /
    default:  ✧   █░░█░░░░░█░░█ ✧                \_/\_/\_/
    default:   ▄▄  █░░░▀█▀░░░█  ▄▄✧ 
    default:  █░░█ ▀▄░░░░░░░▄▀ █░░█ Vagrant Up has finished! Visit http://vvv.test
    default: ──────────────────────────────────────────────────────────────────────
~/dev/freshvvv ᚴ:develop 
❯ 
```

Are you sure that your VVV git checkout is intact?

I ask because:

```
/srv/provision/core/nodejs/provision.sh: line 34: npm: command not found
```

and

```
default: /srv/provision/core/grunt/provision.sh: line 16: /usr/bin/npm: No such file or directory
```

Means that Node is not installed, **but** clearly that is not true, the `provisioner-main.log` clearly states that NodeJS is already installed:

```
nodejs is already the newest version (14.15.4-1nodesource1).
```

> I caught the error when I tried to add a new site. 

So this was not an initial `vagrant up --provision`? I'm confused, you said this was a brand new install, and your `config.yml` only contains the default values.

---

To continue, I'm going to need a clear unambiguous timeline:

 - was this provision a fresh brand new install, or an existing install
    - a `vagrant destroy` followed by a reprovision is not a brand new install, I need to know the difference
  - if you were adding a site, or utility, I need to know the exact details
     - utilities install software, there is no uninstallation once they are added 
  - I need to know about any modifications to files in the `config` or `provision` folders other than `config.yml`
    - especially any vagrant related changes such as custom files or modifications to the vagrantfile itself
  - had you installed/added/used any utilities, even if you then removed them from `config.yml`?
  - does a brand new install in a brand new folder that has a different name also fail?

Right now the instructions provided for reproducing the fault result in a working VVV instance

**Comment by Gen-fr** [comment] 2021-02-03 20:41
> Are you sure that your VVV git checkout is intact?

Should be intact:
remote: Enumerating objects: 252, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 14022 (delta 166), reused 118 (delta 81), pack-reused 13770
Receiving objects: 100% (14022/14022), 8.46 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (7153/7153), done.

> So this was not an initial vagrant up --provision? I'm confused, you said this was a brand new install, and your config.yml only contains the default values. 

> was this provision a fresh brand new install, or an existing install 

This log from fresh VVV from the new directory

> if you were adding a site or utility, I need to know the exact details 

Didn't use any utility

> I need to know about any modifications to files in the config or provision folders other than config.yml

On the previous install I've used minimal config from docs: 

example:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - example.test
      
and copied the same site conf of wordpress-two:

 mywordpress:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - mywordpress.test

> does a brand new install in a brand new folder that has a different name also fail?

Yep, have the same output
Should I do reinsstall vagrant?

> Right now the instructions provided for reproducing the fault result in a working VVV instance

It works with "vagrant up"

**Comment by tomjn** [comment] 2021-02-03 21:33
> Should I do reinsstall vagrant?

No, Vagrant is just system software, it isn't VVV.

> This log from fresh VVV from the new directory

Are you _sure_? I did the same thing and did not get the results you did, and did not get that result.

The only reference I can find is if you installed `nodejs` on Debian, which has a separate `npm` package. But VVV does not use Debian, it uses Ubuntu, and we don't use the Ubuntu/Debian packages, and we use Nodesource for the Node apt package. `npm` should be present.

If you SSH into the VM and run these commands, what is the output:

```sh
which node
node --version
which npm
npm --version
sudo apt-get install npm
which npm
npm --version
```

**Comment by Gen-fr** [comment] 2021-02-04 07:45
I used those plugs also: 
vagrant-goodhosts --local (couple times)
vagrant-hostupdate
![Screenshot_2021-02-04_10-38-13](https://user-images.githubusercontent.com/78485088/106860891-0fdb5900-66d6-11eb-87a6-a9894568391b.png)
r
vagrant-vbguest

**Comment by Mte90** [comment] 2021-02-04 11:15
goodhosts and hostsupdater goes in conflict, is better to have just goodhosts plugin.
Did you try a `vagrant destroy` and `vagrant up`?

**Comment by Gen-fr** [comment] 2021-02-04 11:45
@Mte90 I didn`t install anything with the last vagrant up. And now when I try to uninstall plugs by

>~/vv$  vagrant plugin uninstall vagrant-hostsupdater
The plugin 'vagrant-hostsupdater' is not currently installed.
~/vv$ vagrant plugin uninstall hostsupdater
The plugin 'hostsupdater' is not currently installed.


 Vagrant up went well but I can't do provision.

**Comment by Mte90** [comment] 2021-02-04 11:47
Ok so you need to try on destroy and restart the vagrant machine so it will start again, if the error persist we need to investigate somehow.
```
vagrant destroy
vagrant up
```

**Comment by tomjn** [comment] 2021-02-04 12:06
> And now when I try to uninstall plugs by

They may be local installs rather than global installls, requiring `--local`, but that should have no relation to the problems provisioning.

Out of curiosity, does `sudo apt-get install npm` improve things?

**Comment by tomjn** [comment] 2021-02-04 12:08
Also, if you SSH into the VM and run `apt-cache show nodejs` what does it say?

Mine starts like this:

```
vagrant@vvv:~$ apt-cache show nodejs
Package: nodejs
Version: 10.23.2-1nodesource1
Architecture: amd64
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 78620
Depends: libc6 (>= 2.9), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.4.0), python-minimal, ca-certificates
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Provides: nodejs-dev, nodejs-legacy, npm
```

**Comment by tomjn** [comment] 2021-02-04 12:18
My working theory is that your machine does not have a route to nodesource, and apt is falling back to the stock debian/ubuntu Node packages that don't contain NPM

If I'm correct, then provisioning with #2350 will cause provisioning to fail during network checks for you

**Comment by tomjn** [comment] 2021-02-04 12:25
Likewise I suspect if you run `apt-cache policy nodejs` you will see that the package was installed from a Debian mirror rather than nodesource ( if you can get us the output of that command too? )

**Comment by tomjn** [comment] 2021-02-04 12:43
I also suspect that this command may resolve the problem by forcing nodesource:

```sh
sudo apt-get install -t "bionic" nodejs
```

**Comment by tomjn** [comment] 2021-02-04 15:13
It also looks like the github action now has this, so we have a way to reproduce this. #2351 may help here

**Comment by Gen-fr** [comment] 2021-02-04 15:18
@tomjn I guess all this configuration I have to try on VM, am I right? 
So, outputs:


sudo apt-get install npm
> vagrant@vvv:~$ sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

apt-cache policy nodejs
> vagrant@vvv
apt-cache policy nodejs
nodejs:
  Installed: 14.15.4-1nodesource1
  Candidate: 14.15.4-1nodesource1
  Version table:
 *** 14.15.4-1nodesource1 500
        500 https://deb.nodesource.com/node_14.x bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     8.10.0~dfsg-2ubuntu0.4 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
     8.10.0~dfsg-2ubuntu0.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     8.10.0~dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

        
        
apt-get install -t "bionic" nodejs
> vagrant@vvv:~$ sudo apt-get install -t "bionic" nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (14.15.4-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.


and cache nodejs 

> vagrant@vvv:~$ apt-cache show nodejs
Package: nodejs
Version: 14.15.4-1nodesource1
Architecture: amd64
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 116648
Depends: libc6 (>= 2.17), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.8), python-minimal, ca-certificates
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Provides: nodejs-dev, nodejs-legacy, npm
Homepage: https://nodejs.org
Priority: optional
Section: web
Filename: pool/main/n/nodejs/nodejs_14.15.4-1nodesource1_amd64.deb

FUll cache nodejs in attachment file:
[cache_show_nodejs.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5926654/cache_show_nodejs.txt)

**Comment by tomjn** [comment] 2021-02-04 16:29
hmmm so it installed the package from the right source and yet `npm` is missing for you but not for me

**Comment by tomjn** [comment] 2021-02-04 16:50
so now it's happening for me :/ no closer to identifying the cause, I'm going to check that the package actually contains npm

**Comment by tomjn** [comment] 2021-02-04 17:12
I used these commands to retrieve and extract the package to look at its innards:

```
apt-get download nodejs
ar x nodejs_14.15.4-1nodesource1_amd64.deb
```

Then extracted the two  tarballs it  gave me, they have `npm` and `npx`  but  I'm unsure why neither are present on the system after package installation

**Comment by Gen-fr** [comment] 2021-02-04 17:35
@tomjn Are these packages for VM? Where do I have to put them? Does the solution work?

**Comment by tomjn** [comment] 2021-02-04 17:38
Yes, this is all inside the VM, I have not found a solution, and I haven't identified the cause

The summary of the  issue so far seems that installing `nodejs`  14 via NodeSource should install `node` `npx` and `npm`, but only `node` is installed. We do not know why. Judging from the package, this was not intentional as the package still contains npm and  npx files.

**Comment by tomjn** [comment] 2021-02-04 17:43
```
sudo apt-get remove nodejs
sudo apt-get install nodejs
```

With this I now have Node back with npm and npx 🤔  I'm not sure why

**Comment by tomjn** [comment] 2021-02-04 17:56
And a brand new provision in a new folder runs fine without issues

**Comment by tomjn** [comment] 2021-02-04 17:58
GitHub actions are running again now 🤔

**Comment by tomjn** [comment] 2021-02-05 00:34
#2354 and #2353 attempt to resolve this

**Comment by Gen-fr** [comment] 2021-02-05 10:23
Sorry, doesn't work for me
[provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5931760/provisioner-main.log)

**Comment by tomjn** [comment] 2021-02-05 12:38
@Gen-fr are those provisioner logs for each PR? Or `develop`? Or `develop` ran twice? 🤔 

I ask because they both contain this line:

```
[0m[39m[2m * Installing/updating npm and npm-check-updates[21m[0m
```

Which was removed in the fix, you've been testing pre-fix code

**Comment by Gen-fr** [comment] 2021-02-05 14:13
@tomjn I only have modified provision.sh how it says in #2354 and #2353 for my VVV. Did I do wrong?

**Comment by tomjn** [comment] 2021-02-05 14:37
@Gen-fr you mustn't have applied all the changes, both PR's and others were merged so pull down the latest `develop` branch and try again

**Comment by Gen-fr** [comment] 2021-02-05 15:39
@tomjn I got it, works fine. Thank you, Tom! You do a great job! Have a nice day)

**Comment by tomjn** [comment] 2021-02-05 15:57
Awesome :) I'm going to close this now, that was a tough one to figure out

**Closed by tomjn** 2021-02-05 15:57 UTC
Labels: bug, help wanted, provisioner:core
