### ISSUE TITLE
Host key verification failed during site provisioning

### ISSUE THREAD

**Issue by CdrMarks** [Varying-Vagrant-Vagrants/VVV#1242] opened 2017-08-02 15:25 UTC
I have setup in my vvv-custom.yml file the following site:
```
sites:
  lpcms:
    repo: git@bitbucket.org:randallreilly/vvv-lpcms.git
    nginx_upstream: php71
    hosts:
     - lpcms.dev
```

## Expected Behavior

I hoped to see the Bitbucket repository cloned into /srv/www/lpcms.

## Current Behavior

The following lines are what I see in the output when I'm running `vagrant up` or `vagrant --reload provision`:
```
==> default: Running provisioner: site-lpcms (shell)...
    default: Running: C:/Users/rmarks/AppData/Local/Temp/vagrant-shell20170801-12212-1nia5g.sh
==> default: Downloading lpcms, see git@bitbucket.org:randallreilly/vvv-lpcms.git
==> default: Cloning into '/srv/www/lpcms'...
==> default: Host key verification failed.
==> default: fatal: Could not read from remote repository.
```

## Possible Solution

I thought about copying my hosts' `~/.ssh/known_hosts` file into the guest at `/root/.ssh/known_hosts` by putting some statements in my Vagrantfile.  That didn't work.

## Steps to Reproduce (for bugs)

See above

## Context

I'd like to use a private repository on bitbucket.org to provision a site in VVV2.

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.7
* VM Provider name: VirtualBox
* VM Provider version: 5.1.26
* Operating System and version: Windows 10 Pro, 64-bit

**Comment by LoreleiAurora** [comment] 2017-08-02 15:30
Add `trusted-hosts` to the utilities section of your vvv-custom.yml file to test the solution for this coming in the next release.

It will import the following host keys:
GitHub
BitBucket
GitLab

**Comment by CdrMarks** [comment] 2017-08-02 16:20
Hi @LoreleiAurora, I had already added `trusted-hosts`.  Sorry I didn't mention that.

Is there something else I can implement in my VVV to get those host keys in place that isn't in my current release?

**Comment by LoreleiAurora** [comment] 2017-08-03 01:30
Can you please post the full output of a provision in a gist

**Comment by CdrMarks** [comment] 2017-08-03 02:15
Here is the gist: https://gist.github.com/CdrMarks/553f5040784886f29eaaf17f3159665d

**Comment by rmurillo21** [comment] 2017-09-16 22:24
@CdrMarks Have you been able to resolve this?  I am having the same issue.

**Comment by rmurillo21** [comment] 2017-09-16 23:38
I seem to have resolved it for me.  The issue is basic ssh authentication so that VVV can clone your repo. The problem is your local git does not know where to locate the keys.

The ssh authentication issue is happening on the host (Windows) and not on the guest (Ubuntu).  This means you need to config your Windows ssh client correctly, rather than on the guest OS. So `trusted-hosts` did not seem to be the correct solution, as that is a guest side utility.

In my case I am using a Github private repo, combined with Deploy Keys for read only access to the repo. I generated a keypair, and configured them at Githhub and locally in ~/.ssh

Then, I ran the git command to clone my repo manually to confirm its operation

I do not believe this is a VVV issue, as much as how to configure git locally to use the correct ssh configuration for your host. 

When git is correctly configured for your host/key, then accessing a private repo with a custom VVV site can work without issue.

**Comment by rmurillo21** [comment] 2017-09-17 03:35
Tracked it down: Its the git/ssh key configuration on your Windows host. The "Host key verification failed." message is a git error when it can't find the matching private key in your local environment.
If you run the  `git clone` on the command line the same error will be shown.  Review all ~/.ssh keys and GIT<->SSH configuration. When you can clone on the command link with errors or password prompts, then Vagrant will run without this error.

**Comment by rmurillo21** [comment] 2017-09-17 03:37
IMHO its an issue with the users personal computers settings only. It is not a project level bug.

**Comment by rmurillo21** [comment] 2017-09-17 15:33
The problem is the provisioning of the private key. It needs to be added to the provision phase, before git is called to clone. See https://stackoverflow.com/questions/30075461/how-do-i-add-my-own-public-key-to-vagrant-vm

**Comment by rmurillo21** [comment] 2017-09-17 15:59
The normal solution is to use ssh agent forwarding.   This is enabled in the Vagrant file. However, there are/were issues with ssh agent forwarding on Windows. See https://github.com/hashicorp/vagrant/issues/1735

**Comment by rmurillo21** [comment] 2017-09-18 18:43
This worked for me:  provision the private key for the target repo  (Github in my case) during the provision phase, to get the key from the host to the guest:

1. Provision the ssh key for your repo:
```
  ssh_key = ENV['USERPROFILE'] +  "\\.ssh\\id_rsa"
  config.vm.provision "file", source: ssh_key, destination: "/home/vagrant/.ssh/id_rsa"
```
Note this is Windows specific. It expects a key file in the users .ssh folder 

2. Update known hosts on the guest. I added this to my custom provision_site.sh script:

> read -r -d '' ssh_known_host <<'EOF'
> |1|bo/v7A6iW0ByMbOBDowPnNW800Y=|9lK0/LfvJbW4x+ojzIJs5jR3K1k= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
> |1|rxsDR39Vhe0mHO3kn1BGjZFAv0g=|n247Nv81AqpFtIeG/6d9IBYQt3w= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
> EOF
> echo $ssh_known_host > /home/vagrant/.ssh/known_hosts
> echo $ssh_known_host > /root/.ssh/known_hosts
> chmod 600 /home/vagrant/.ssh/id_rsa
> 

There is a good discussion of how to securely manage known_hosts below.  I generated/valdiated the keys manually, then coded them statically as above.

https://serverfault.com/questions/447028/non-interactive-git-clone-ssh-fingerprint-prompt

Using these two snippets, I could get VVV to properly clone my private Gihub on repo during the provision phase.  This was tested on Windows 10, with Vagrant 1.9.8 and VVV 2.0.0

**Comment by tomjn** [comment] 2017-11-03 17:33
I'm closing this out as it's been several months since the OP was last seen or responded, and the issue needs reproducing on the latest version as others have done elsewhere

**Closed by tomjn** 2017-11-03 17:33 UTC
Labels: support
