### ISSUE TITLE
5.2.1 update breaks WordPress installations

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1819] opened 2019-05-22 15:12 UTC
## Expected Behavior
Minor update shouldn't break anything

## Current Behavior
When I update the WP from 5.2 to 5.2.1 (I tried downgrading but that didn't help) I am getting 

> Parse error: syntax error, unexpected '}', expecting end of file in /srv/www/personal/wordpress-test/public_html/wp-includes/general-template.php on line 4569

I started digging and the issue happens in `feed.php` on line where `$feed->init()` is (770).

So my guess is something with new vvv version and `SimplePie()` is clashing maybe?

I deleted my db in order to run a clean install, but no go.

## Steps to Reproduce (for bugs)
1. Have VVV3
2. Try to update WP to 5.2.1 version
3. Panic because you need to test the code for production
4. Set up temporary docker to see if it will work until this issue is solved ¯\_(ツ)_/¯

## Your Environment

* VVV version: 3
* VVV Git Branch: develop
* Vagrant version: Vagrant 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: Version 6.0.4 r128413 (Qt5.6.3)
* Operating System and version: MacOS 10.14.4

**Comment by tomjn** [comment] 2019-05-22 15:20
I doubt that's the case, my personal site runs on Digital Ocean and has near identical specs to VVV yet doesn't encounter this issue. I did see this issue myself during testing but reprovisioning a fresh install fixed the problem. Looking at the files themselves didn't reveal the issue as the missing characters were present when checked, resaving resolved the problem for that file

Do you encounter this error upgrading from any other WP install?

**Comment by dingo-d** [comment] 2019-05-22 16:09
I asked a colleague to update (he's not using VVV) and it worked fine on his mac. I've set up my docker and no problems here either.

I tried using wpcli to clear transients, flush cache but I got the same error. I'll try to reprovision the VVV and see if this will work.

**Comment by tomjn** [comment] 2019-05-22 16:14
Because of the nature of this, WP never gets to run, so transients etc are all irrelevant. The problem is the files themselves and how they're updated

**Comment by Mte90** [comment] 2019-05-22 17:20
I had the same issues, a vagrant halt and up fixed the problem (after the update).
I was thinking that was me but I think that is something on VVV from caching side.

**Comment by rodrigoprimo** [comment] 2019-05-22 19:51
I'm experiencing the same problem. In my case, it started when I updated to WP 5.2.0. I had this both when updating via wp-admin and wp-cli.

**Comment by dingo-d** [comment] 2019-05-23 07:25
I can confirm that solution @Mte90 suggested worked. I had to `vagrant halt` then `vagrant up` after WP update. All seems to be working now.

**Comment by desrosj** [comment] 2019-05-23 12:10
I have been experiencing this as well. I usually fix it with a `vagrant reload`. Over the last 2 weeks it has happened to me a number of times, most notably when I upgrade WordPress using WP CLI. The errors that are reported are always different, and don't exist in the files.

**Comment by tomjn** [comment] 2019-05-23 15:20
As an aside, VBox 6.0.8 was released a little while ago with shared folder related fixes, updating may help

**Comment by bzkn** [comment] 2019-05-23 15:37
I had the same issue when I was trying to update to 5.2.1, had no issues with updating to 5.2. I had just updated to VVV 3.0 (master branch).  I run VirtualBox 5.2.3 and Vagrant 2.2.4 on MacOS 10.12.6 (Sierra).

I noticed other problems popping up prior to any updates in the last couple of weeks, where all sites became inaccessible (all I saw was the KACE login screen, even on vvv.test) after turning my laptop back on from sleep mode. This seems to still be the case as of this morning. I'm gonna try to see if switching to VVV develop branch and updating VirtualBox to 6.x will help.

I have been getting around both issues by restarting and reprovisioning.

**Comment by bzkn** [comment] 2019-05-23 19:17
I updated to the VirtualBox 6.0.8 and switched to the develop branch of VVV and reprovisioned. Still having an error when updating to WP to 5.2.1 and after waking up the laptop I still get the KACE login screen on every site, including vvv.test. I'm not sure if the KACE screen has any relation to this issue though..

![image](https://user-images.githubusercontent.com/22645042/58279993-b9957d80-7d6d-11e9-85d2-a23d113f66f8.png)

**Comment by tomjn** [comment] 2019-05-23 22:29
I don't know what KACE is but it's not a part of VVV and we don't interact
with it in any way, not intentionally. I'm going to have to do some
research to find that out what KACE is and how its related. Is it a plugin?

**Comment by dingo-d** [comment] 2019-05-24 07:01
> As an aside, VBox 6.0.8 was released a little while ago with shared folder related fixes, updating may help

I have 6.0.8 on my mac and it didn't help unfortunately

**Comment by Mte90** [comment] 2019-05-24 10:30
I am doing tests about it, seems is not memcache the problem, also restart nginx doesn't fix the problem.

**Comment by bzkn** [comment] 2019-05-24 13:30
So it looks like KACE is an OS deployment appliance we use at my workplace but I still have no clue how it comes up. Basically, after a resuming from sleep mode, every valid *.test URL I try gets redirected to a *.test/login and that takes me to KACE login.

**Comment by tomjn** [comment] 2019-05-24 13:32
Does KACE run a local web server? Are you able to contact KACE support or
disable it temporarily?

**Comment by bzkn** [comment] 2019-05-24 13:35
I don't know how our deployments are managed, it's a pretty big university. I'll touch base with our IT folks and see what's up.

**Comment by kloon** [comment] 2019-05-27 07:48
I have the same issue, not specifically related to 5.2.1 for me though. I run nightly builds and every time I update either via wp-admin or via wp-cli I get this error. To resolve I have to halt and up the vagrant box before it is resolved.

Vagrant 2.2.4
Virtual Box 5.2.30 r130521

**Comment by sbrody** [comment] 2019-05-29 13:40
I had this issue too. I went to the two files mentioned general-template.php and feed.php and found a trailing white space, which I deleted and everything worked fine

**Comment by tomjn** [comment] 2019-05-29 18:35
If I `vagrant ssh` into the guest VM, and flush the page cache, all syntax issues disappear:

```
vagrant@vvv:~$ sudo su
root@vvv:/home/vagrant# echo 1 > /proc/sys/vm/drop_caches
```

**Comment by sbrody** [comment] 2019-05-30 11:08
Ok thanks - that's useful to know

**Comment by Mte90** [comment] 2019-05-30 14:34
I am trying to understand if ti is possible to set the chace size but this depends on the ram.
So on internet seems that everyone is suggesting to do a cron that clean up https://unix.stackexchange.com/a/254984 but can be expensive for the memory.
With https://github.com/hoytech/vmtouch is possible to clean up the ram for a specific folder.

**Comment by tomjn** [comment] 2019-06-12 12:31
Of note, I tested this with a new VM using the `ubuntu/bionic64` box and the issue did not occur. I haven't found anything in the VVV box build script to explain why this happens, but I think a switch to the `ubuntu/bionic64` is the best short term solution

You can test this by setting the box via `vvv-custom.yml` in the `develop` branch:

```yaml
vm_config:
  box: ubuntu/bionic64
```

Note that it doesn't currently work with shared database folders though. I've some work to do to that will make that more robust by handling the user/group IDs better

**Comment by tomjn** [comment] 2019-06-20 14:18
I'm going to close this out now that we're on the official box again in the `develop` branch. I've tried reproducing the problem on that box but haven't been able to, and it reliably breaks if I switch back to the box we built.

We still need to solve the problem with our box builder script, but it shouldn't impact users from now on

**Closed by tomjn** 2019-06-20 14:18 UTC

**Comment by victor-lava** [comment] 2019-08-07 15:54
> I doubt that's the case, my personal site runs on Digital Ocean and has near identical specs to VVV yet doesn't encounter this issue. I did see this issue myself during testing but reprovisioning a fresh install fixed the problem. Looking at the files themselves didn't reveal the issue as the missing characters were present when checked, resaving resolved the problem for that file
> 
> Do you encounter this error upgrading from any other WP install? Is there an associated WP Trac ticket? ( if not can you raise one? My suspicion is character encoding issues but I haven't much to go off of )
> 
> Also have you tried WP CLI based updating?

I had a similar issue after updating to 5.2.2. However re-saving file helped to fix that. Very odd!

**Comment by tomjn** [comment] 2019-08-07 15:56
This issue is due to a kernel bug in a box we used to use. The latest
version uses a newer box that doesn’t have this issue.

Back up your database, update VVV, destroy and recreate the VM.
