### ISSUE TITLE
grunt not installed correctly after box creation/provisioning

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1887] opened 2019-06-27 23:06 UTC
grunt is not installed correctly after box creation/provisioning. Possibly the same as/related to #1885.

## Expected Behavior
grunt is installed

## Current Behavior
```
Command 'grunt' not found, but can be installed with:

apt install node-grunt-cli

Please: command not found
```

## Steps to Reproduce (for bugs)
1. vagrant up --provision
2. vagrant ssh

## Workaround
```
sudo npm install -g grunt-cli grunt
```

## Your Environment
* VVV version: git
* VVV Git Branch: develop
* Vagrant version: 2.2.5
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8
* Operating System and version: macOS 10.14.5

**Comment by Mte90** [comment] 2019-06-28 10:10
this should fix the issue https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1889

**Comment by paulschreiber** [comment] 2019-08-01 17:19
This does not appear to be fixed in 3.1.0.

**Comment by Mte90** [comment] 2019-08-02 11:09
did you updated to develop branch? did a `vagrant destroy`?

**Comment by paulschreiber** [comment] 2019-08-02 11:37
Yes, I updated to 3.1.0 (`git co 3.1.0`), and then ran `vagrant destroy and vagrant up --provision`.

**Comment by Mte90** [comment] 2019-08-02 12:16
I cannot replicate the issue anymore, what kind of error you get?

**Comment by paulschreiber** [comment] 2019-08-02 12:18
See `current behaviour` in the description above. Upon login (`vagrant ssh`) that message is printed.

Was `3.1.0` tagged incorrectly? Did this commit not make it in?

**Comment by tomjn** [comment] 2019-08-02 12:25
I have no idea what the current state of this is, and googling on how to properly install things has been super unhelpful. There are some unanswered questions:

 - Why does it work on a fresh provision for me and @Mte90 but not for others
 - The current behaviour in the first note of this issue has no context, it isn't clear what command generated it, be it using `grunt` in a terminal, opening a new SSH session, or trying to use `npm`
 - Should we use `sudo` or not to install grunt? Googling gives many, many answers that all contradict eachother
 - `npm install -g grunt` won't work as the vagrant user because the node modules etc folders are all owned by the system, which suggests that `sudo` is required for it to work, but previous attempts to resolve this have only lead to the problem temporarily being fixed, be it in a singular folder, or for that individual SSH session, not a true fix. I don't know why
 - When we made some changes and asked if the problem was fixed, we got no response and were unable to reproduce the problem, so the issue was closed

**Comment by tomjn** [comment] 2019-08-02 12:28
> Was 3.1.0 tagged incorrectly? Did this commit not make it in?

3.1.0 is basically the latest commit to `master`, I believe the only new things in `develop` are typo fixes in the readme at the moment. Eitherway I haven't been able to reproduce this issue on my personal machines for several months now

**Comment by tomjn** [comment] 2019-08-06 23:44
Closing this out thanks to the changes in #1916

**Closed by tomjn** 2019-08-06 23:44 UTC
Labels: bug
