### ISSUE TITLE
Error on re-provision:  chmod on /srv/www/my_site/.git/config.lock failed

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1764] opened 2019-04-25 05:49 UTC
## Expected Behavior

I am trying to add a new site to VVV.

## Current Behavior
To add my new site, I first added the following entry to vvv-custom.yml:

```
  feedxl:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - feedxl.test
```
I then executed `vagrant up --provision`.  During that process, when it came time to bring up my new site, it failed with the error:

```
    default: Downloading feedxl, see https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default: error: chmod on /srv/www/feedxl/.git/config.lock failed: Operation not permitted
    default: fatal: could not set 'core.filemode' to 'false'
    default: Error: The /srv/www/feedxl folder does not exist, and no repo was specified in the config file, there is nothing to provision for this site!

```

## Possible Solution
I tried inspecting my VVV root directory.  Inside that directory, the `www` folder was marked 'read only.'  So I removed that designation.  But the error still remained.

## Steps to Reproduce (for bugs)

1.  Add new site code to vvv-custom.yml.
2.  Run vagrant up --provision.

[Here is a link](https://pastebin.com/HKtdXehH) to more lines of the output.  FYI it is not the full output.  I can link that if you want.

## Your Environment

* VVV version:   2.6.0-4-g678d59b
* VVV Git Branch:   develop
* Vagrant version:  2.2.4
* VM Provider name:  VirtualBox
* VM Provider version:  Version 6.0.6 r130049 (Qt5.6.2)
* Operating System and version:  Win 10, x64

**Comment by benlumia007** [comment] 2019-04-25 07:34
have u tried using `vagrant reload --provision` instead of `vagrant up --provision`. when u reload, it shutdowns the vm and restarts so that it can properly create the site of your choosing.

**Comment by cagross** [comment] 2019-04-25 07:41
@benlumia007 Yes, I have tried that as well--resulting in the same error. Sorry for not including that in my ticket.

**Comment by tomjn** [comment] 2019-04-25 10:06
Those errors are from `git`, failing to write/modify the filesystem, and this is the first step where it encounters that problem:

>  default: error: chmod on /srv/www/feedxl/.git/config.lock failed: Operation not permitted

That's the root issue, **i don't know how your VVV folder became read only, but you might want to double check the permissions of the subfolders and files,** setting the VVV folders permissions doesn't mean the `www` folder is writable etc.

**Comment by cagross** [comment] 2019-04-25 10:31
@tomjn OK thanks for the reply.  But can you clarify how I can/should go about troubleshooting this?

I checked a few of my existing sites in my `vvv/www` directory.  Each of those is of course in its own folder.  Each of those seems to be set to 'read only' ([screenshots](https://imgur.com/a/hzsHfMc)).  

> setting the VVV folders permissions doesn't mean the www folder is writable etc.

As a test, in the `vvv/www` directory, I manually created a new folder. This folder was also created as 'read only' ([screenshot](https://i.imgur.com/Th2z4Xt.jpg), but also seemed to have full read/write permissions ([screenshot](https://i.imgur.com/DxEZhM1.jpg)).

Thoughts?

**Comment by tomjn** [comment] 2019-04-25 10:45
There's nothing in VVV that would do this, so I have no clues as to why all those folders are read only, just that they must not be read only. This will be caused by an external factor, something on your machine, or a setting changed by yourself or other software. This isn't something that can be fixed by configuring VVV or changing VVV

**Comment by tomjn** [comment] 2019-04-25 10:51
This PR tries to improve the messaging by detecting when `git clone` fails:

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1765

It won't fix your problem, it just makes it clearer what's happened

**Comment by cagross** [comment] 2019-04-25 10:59
> There's nothing in VVV that would do this, so I have no clues as to why all those folders are read only, 

Right.  But are these folders *actually* read-only?  I ask because from the error message, it looks like VVV is able to successfully create a folder (`feedxl`), then another folder inside (`.git`).  It then fails to chmod on a file within that folder (`config.lock`).

Furthermore, in the www folder, I can manually create the `feedxl` folder. Then I can run a `git init` to successfully create a `.git` folder ([screenshots](https://imgur.com/a/K2gPyMU)).  If these folders were actually read-only, would I be able to do this?  

In the .git folder is a file:  `conifg`  This file appears to be fully writeable ([screenshots](https://imgur.com/a/XpRFOAm)).  I realize that's not the same file referenced in the error message.

> This PR tries to improve the messaging by detecting when git clone fails:
> It won't fix your problem, it just makes it clearer what's happened

OK thanks.  So how would I implement this new messaging feature on my local machine?  Would I simply `git pull`, then `vagrant up --provision`?

**Comment by tomjn** [comment] 2019-04-25 11:14
It wouldn't tell you anything we don't already know, but you would have to
switch branch from develop, I wouldn't recommend it as that branch is
interested and doesn't change VVVs behaviour

Are you sure fit actually creates the folder? Just because you the active
logged in user can create a folder manually doesn't mean the user virtual
box is running under can do it. Fundamentally all I can do is make VVV
detect this situation and tell you about it, but it wouldn't tell you
anything more than what I've said here.

There's only so much that can be done from the guest VM, the solution to
your issue is on the host machine in Windows. Perhaps the ownership of
those files has changed? I don't know. What would be perfect for you now to
debug this is a Windows IT Administrator

**Comment by cagross** [comment] 2019-04-25 11:25
> Just because you the active logged in user can create a folder manually doesn't mean the user virtual
box is running under can do it. 

OK right, I get that.  So in light of that, how can I ensure the virtual box can create folders?

> the solution to your issue is on the host machine in Windows.

OK I understand that.  But my issue is with troubleshooting.  I don't know what I'm looking for, nor do I know what to change once I find what I'm looking for :-/

> Perhaps the ownership of those files has changed? 

OK.  I know how to check the ownership of a file in Windows.  But which file(s) should I check?  And which owner does each file need to have?

**Comment by tomjn** [comment] 2019-04-25 11:33
At this point my knowledge of Windows is stretched thin, Id expect you to
be the owner and the folders to have similar ownership and group stats as
things in your my documents folder.

As for unchecking read only on all subfolders and files, I don't know, I
found this on how to do it with the command prompt
https://superuser.com/questions/653951/how-to-remove-read-only-attribute-recursively-on-windows-7

There is one longshot, does doing it from within the VM work? A vagrant SSH
and a chmod command on a folder? If so that would be great news :) chmod
777 folder name

Any ideas how those folders became set to read only in the first place?

**Comment by cagross** [comment] 2019-04-25 11:35
Also, I this may be of note.  I installed Local by Flywheel, and was able to create a new WordPress site without issue.  I believe it is also using the same VirtualBox software.  The Local by Flywheel site was *not* created in the same `www` folder we have been discussing.  The folder used by Local by Flywheel is also marked 'Read Only' by Windows, but also, appears to have full read/write permissions (just as the `vvv/www` folder. Not sure if that means much, but just thought I'd throw it out there.

**Comment by cagross** [comment] 2019-04-25 11:38
> As for unchecking read only on all subfolders and files, I don't know, I
found this on how to do it with the command prompt
https://superuser.com/questions/653951/how-to-remove-read-only-attribute-recursively-on-windows-7

I tried unchecking 'read only' for the `www` folder.  It processed that request for a few minutes.  When it reached 100%, it seemed to complete without issue.  But when I then checked the folder properties again, it was still marked as 'read only.'  I tried that twice, with the same result.

> There is one longshot, does doing it from within the VM work? A vagrant SSH
and a chmod command on a folder? If so that would be great news :) chmod
777 folder name

Stand by while I check.

> Any ideas how those folders became set to read only in the first place?

No idea.  But even though Windows marks them as 'read only,' are they?  What exactly does 'read only' mean?  If I can write new files to the folder, is it still 'read only?'

**Comment by cagross** [comment] 2019-04-25 11:50
> There is one longshot, does doing it from within the VM work? A vagrant SSH
and a chmod command on a folder? If so that would be great news :) chmod
777 folder name

OK I tried that.  As expected, it returned:

`chmod: changing permissions of ‘test’: Operation not permitted`

That's good--at least we can easily re-create/test the issue now.

**Comment by tomjn** [comment] 2019-04-25 12:16
hmmm looking back at your first screenshot, the read only box isn't checked, it's a square in a square so it's indeterminate. I wonder if that means some but not all is read only, or if there's more to it than that?

I've done a bit more digging based on that, and it seems in VirtualBox you can't `chmod` something in a mounted folder. Which makes me wonder why `git` feels the need to do it in the first place. This is the first time we've encountered this

As for Local by FlyWheel, I did a little more digging, and yes/no. It uses VirtualBox, but the VM is Boot2Docker, with docker containers internally. It also doesn't use Vagrant, so it's communicating directly with VirtualBox to do its work. I also found a handy snippet that would help with our root certificates in a shell script in Locals app bundle `security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$*"`.

I haven't figured out how mounted folders work in Local, but my guess would be it does it via `rsync`. We have that option as well, but it has tradeoffs, particularly since it means there would be 2 copies of every file, one inside the VM and one on the host

**Comment by tomjn** [comment] 2019-04-25 12:21
@cagross I don't know if this will help, but can you run `git config --global core.fileMode false` inside the VM then try to add a new site and see if this helps?

**Comment by cagross** [comment] 2019-04-25 12:25
> hmmm looking back at your first screenshot, the read only box isn't checked, it's a square in a square so it's indeterminate. 

OK good catch--you're correct on that.  It's not a full fledged check mark.

> I've done a bit more digging based on that, and it seems in VirtualBox you can't chmod something in a mounted folder. Which makes me wonder why git feels the need to do it in the first place. This is the first time we've encountered this

I can say that I successfully created a new VVV site as recently as ~3 weeks ago. At that time, there were no issues. I can also say that just prior to today's attempt, I updated the VirtualBox software--can't remember the previous version :-/  I also updated VVV to the latest version (also can't remember the previous version I was running).  Not sure if that matters.

> I don't know if this will help, but can you run git config --global core.fileMode false inside the VM

OK.  To be clear, I would `vagrant ssh` then run this command?  Do I need to ensure I run it from any particular directory?

> then try to add a new site and see if this helps?

To be clear, I should execute a `vagrant reload --provision`, just as I've been trying so far?

**Comment by tomjn** [comment] 2019-04-25 12:28
> OK. To be clear, I would vagrant ssh then run this command? Do I need to ensure I run it from any particular directory?

That's right, `vagrant ssh`, run the command, and exit, then `vagrant reload --provision`. It shouldn't matter where you run it inside the VM as it's got `--global`

**Comment by cagross** [comment] 2019-04-25 12:41
OK I did so.  The git command completed without any output.  The `vagrant reload --provision` again failed at the same step, but this time with more output:

```
==> default: Running provisioner: site-feedxl (shell)...
    default: Running: C:/Users/snarl/AppData/Local/Temp/vagrant-shell20190425-9480-ctl93d.sh
    default: Updating feedxl...
    default: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
    default: Use '--' to separate paths from revisions, like this:
    default: 'git <command> [<revision>...] -- [<file>...]'
    default: fatal: 'origin' does not appear to be a git repository
    default: fatal: Could not read from remote repository.
    default:
    default: Please make sure you have the correct access rights
    default: and the repository exists.
    default: error: pathspec 'master' did not match any file(s) known to git
    default: Warning: A site provisioner was not found at .vvv/vvv-init.conf provision/vvv-init.conf or vvv-init.conf, searching 3 folders down, please be patient...
    default: Warning: No site provisioner was found, VVV could not perform any scripted setup that might install software for this site
    default: Warning: An nginx config was not found at .vvv/vvv-nginx.conf provision/vvv-nginx.conf or vvv-nginx.conf, searching 3 folders down, please be patient...
    default: Warning: No nginx config was found, VVV will not know how to serve this site
    default: Adding domains to the virtual machine's /etc/hosts file...
    default: Adding hosts from the VVV config entry
    default:  * Added feedxl.test from /vagrant/vvv-custom.yml
    default:  * Restarting nginx nginx
    default:    ...done.
```

**Comment by jjsanderson** [comment] 2019-04-25 12:52
I'm trying to get VVV set up from a clean start, on current OS X. With no changes to `vvv-config.yml` I'm seeing similar errors and no directories are being created in /www in the provision process. I realise much of this thread is now Windows-specific, but the error logs I'm seeing echo those in the original post:

```
default: Downloading wordpress-one, see https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
default: error: chmod on /srv/www/wordpress-one/.git/config.lock failed: Operation not permitted
default: fatal: could not set 'core.filemode' to 'false'
default: Error: The /srv/www/wordpress-one folder does not exist, and no repo was specified in the config file, there is nothing to provision for this site!
```

**Comment by tomjn** [comment] 2019-04-25 13:11
I would remove the `feedxl` folder before reprovisioning as it has an incomplete checkout, it doesn't surprise me that it failed to provision

**Comment by cagross** [comment] 2019-04-25 13:14
@tomjn Right, of course--my mistake. I'll need a couple hours to re-test.

**Comment by cagross** [comment] 2019-04-25 13:56
@tomjn OK I removed the existing `feedxl` folder and tried the reprovision.  But encountered the exact same error :-/

**Comment by davidwolfpaw** [comment] 2019-04-25 16:59
Just a +1 that I'm having the same issue on a fresh VVV install on OSX setting up a new laptop.

**Comment by benlumia007** [comment] 2019-04-25 21:56
what if maybe, is a git version issue.  if the box has an newer version, and u may ahve an older version of git.  im just thinkin out out.

**Comment by jjsanderson** [comment] 2019-04-26 08:22
Ooh, interesting thought…

OK, I've updated git to 2.21 (from 2.20): provisioning still fails with directory creation. Updated the vagrant box to yesterday's release: same issue.

The first 'No such file or directory' error I'm seeing is in the Tideways install sequence, then when provisioning `site-wordpress-one` and `site-wordpress-two`.

**Comment by tomjn** [comment] 2019-04-26 08:24
I think my next step is trying to reproduce on a clean install, Ive just
updated Virtual box locally

Thanks for running through steps with us @cagross it's much appreciated,
we've made a lot of messaging and robustness tweaks the last few months
thanks to some of your issues that have improved things, glad to see you're
still on board :)

**Comment by jjsanderson** [comment] 2019-04-26 08:55
Thanks, @tomjn. Let me know if I can help diagnose and/or test.

**Comment by cagross** [comment] 2019-04-26 09:00
@tomjn  Thanks for the help.  Keep us posted.

**Comment by tomjn** [comment] 2019-04-26 15:32
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1765 has been tested and merged, when this issue happens I would expect it to abort provisioning and be a little clearer about it rather than attempting to continue provisioning the site

**Comment by tomjn** [comment] 2019-04-26 15:34
@jjsanderson can you get me a copy of your provision output? A gist of the entire output from when you provisioned would be super handy. Also are you on Windows? The info in the VVV splash would be handy

**Comment by tomjn** [comment] 2019-04-26 15:35
Also, can you both confirm you have more than 8GB of RAM, and sufficient free disk space?

**Comment by tomjn** [comment] 2019-04-26 15:37
Also, when a `git clone` fails, it aborts provisioning, in your opinion, should it also try to remove the folder if it exists? After all it only clones if no folder exists, therefore any folder that does exist must be a broken or partial git checkout /cc @Mte90

**Comment by jjsanderson** [comment] 2019-04-26 15:39
@tomjin: hurray for scrollback buffers… https://gist.github.com/jjsanderson/4436933e79c04c024414aebf9c129abc

I'm on OS X (10.14.3), 32Gb RAM iMac, >100Gb available disk space.

**Comment by benlumia007** [comment] 2019-04-26 16:24
so what was the issue? im confused.

**Comment by benlumia007** [comment] 2019-04-26 16:40
i think its the new box, i think try downgrade to the previous box for trusty64.

**Comment by benlumia007** [comment] 2019-04-26 16:58
so after doing some test, if  you vagrant ssh to the sites folder to the new creted folder which a provision folder should be there,  no mater what kind of repo it is. it will keep saying that  could not set core.filemode to false. but if you do it on the host machine and get lcone, tis fine.

**Comment by tomjn** [comment] 2019-04-26 17:04
A box update and a reprovision didn't replicate the problem here

@benlumia007 the problem is that when you add a new site, the core provisioner it fails to clone the site template when `git` tries to `chmod` a file

**Comment by tomjn** [comment] 2019-04-26 17:06
Possible cause: https://stackoverflow.com/questions/50108363/git-init-fatal-could-not-set-core-filemode-to-false

Doesn't seem likely though

**Comment by benlumia007** [comment] 2019-04-26 17:09
this is a strange one because,  i ahve vvv and my own custom build, when i use my old box, everything is fine, but if i use my new box, i get the same thing. both projects have their own box so is separate.

**Comment by tomjn** [comment] 2019-04-26 17:11
@cagross @jjsanderson some debugging steps:

1. switch to the `develop` branch
2. SSH into the VM with `vagrant ssh`
3. Run 2 git clones, I want to know the result of each:
  a. Clone into a VM folder `git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /tmp/test`
  b. Clone into a network share folder `git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /srv/www/test`

Do both work? Bonus points for the output. You should be able to run those in any folder as the paths are all absolute

**Comment by benlumia007** [comment] 2019-04-26 18:22
@cagross and @jjsanderson 

are you guys both on Windows 10.

**Comment by tomjn** [comment] 2019-04-26 18:23
JJSAnderson is on MacOS, they haven't confirmed if they are or aren't running antivirus though

**Comment by benlumia007** [comment] 2019-04-26 18:28
my first thought is .vagrant.d and .virtualbox in the home directory. i wonder if u delete this and  it should reconfigure everything, no sure if that will help.

**Comment by jjsanderson** [comment] 2019-04-26 19:28
Apologies - end of the working week in my timezone, and a hungry 3 year-old to wrangle. 

I don't have access to my work system over the weekend, so I've just tried to recreate the problem on my personal laptop. That is: clean clone of 

...aaaaaand provisioning succeeds, everything seems to work.

Same versions of VirtualBox, Vagrant, ubuntu/trusty64 20190424.0.0, and so on. The only disparity I can spot: my work iMac is stuck on OS X 10.14.3 (thanks IT admins!), home MacBook is on 10.14.4. 

I'm stuck as to how to help until Monday. If I can't even replicate my own issue…

(somebody asked about antivirus? The system with the problem is indeed running the ghastly Microsoft SCEP package. It doesn't seem to have caused any problems with VVV specifically for the last four years. Home system has no anti-virus installed.)

**Comment by cagross** [comment] 2019-04-27 13:07
@tomjn 

> Also, can you both confirm you have more than 8GB of RAM, and sufficient free disk space?

I don't have more than 8GB of RAM--I have 8 GB on the nose.  On this particular hard drive, I have ~25 GB free out of ~125 GB.

I tried to clone the two repos.  The first succeeded, and the second failed with the same error. Full output of both [here](https://pastebin.com/T91FZVkQ).

> they haven't confirmed if they are or aren't running antivirus though

I am running Windows Defender for antivirus.  I have not tried disabling it yet.

**Comment by tomjn** [comment] 2019-04-27 13:10
So the git clone to /tmp succeeded? What happens if you try to move that
git clone into a mounted/shared folder? Does that work? If so does a git
pull also work?

**Comment by cagross** [comment] 2019-04-27 13:13
> What happens if you try to move that git clone into a mounted/shared folder? Does that work?

I can try that--but how?  How do I access the /tmp folder, then copy/move the git clone?

**Comment by tomjn** [comment] 2019-04-27 13:15
Inside the VM:

mv from to

I'm on a mobile so my ability to give instructions is super constrained but
a quick Google should tell you how

**Comment by tomjn** [comment] 2019-04-27 13:16
Basically take the folder git created in the tmp folder, and move it to
/srv/www which is a mounted shared folder

**Comment by cagross** [comment] 2019-04-27 13:26
OK I believe I did it.  The full output from my `mv test /srv/www` is [here](https://pastebin.com/HJihMvWC).  Despite those errors, the directory--and the files within--appear to have moved to the expected location ([screenshot](https://i.imgur.com/zZLyGp3.jpg)).  Did I do that correctly?

**Comment by tomjn** [comment] 2019-04-27 13:28
Can you embed those screenshots directly rather than via Imgur and use
gist? Paste bin is under heavy load and won't show the output, and Imgur
tries to optimise for mobile making the text unreadable

**Comment by cagross** [comment] 2019-04-27 13:30
OK [here is the gist](https://gist.github.com/cagross/1ec5bb361941432a43c707d7d52ed62c), and I'll attach the screenshot now.

**Comment by cagross** [comment] 2019-04-27 13:30
![oh-vvv-move](https://user-images.githubusercontent.com/10165488/56850320-4134cb80-692b-11e9-9cb6-f73bd205146c.jpg)

**Comment by tomjn** [comment] 2019-04-27 14:49
Hmm so you can't change any permissions at all

If you move it to the place it tried to do the feed site that failed, does
it provision?

I'm trying to figure out if we can git clone to a non mounted folder then
move it into place

Also does disabling Windows defender fix the original issue? Best to rule
out the antivirus theory

**Comment by tomjn** [comment] 2019-04-27 16:09
@cagross can you switch try this PR:

https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1766


```
git fetch
git checkout tomjn/modify/forcev3networkshares
vagrant halt && vagrant up --provision
```

It adds the default fmode and dmode for `/srv/www`

**Comment by cagross** [comment] 2019-04-27 16:28
> If you move it to the place it tried to do the feed site that failed, does
it provision?

Well now, I can clone the same repo to the VM, just as before.  But when I try to move it, I cannot. It fails with:

```
vagrant@vvv:/tmp$ mv test /srv/www
mv: inter-device move failed: ‘test’ to ‘/srv/www/test’; unable to remove target: Is a directory
```
I'm a bit baffled by that right now.  The same thing just worked a couple hours ago.

> Also does disabling Windows defender fix the original issue? Best to rule
out the antivirus theory

Just tried that, but no change--same provision error.

> can you switch try this PR:
> #1766

OK I executed the three commands you specified--the first two completed without issue.  The `provision` step though still indicated the same error, but more verbose:

```
    default: Downloading feedxl, git cloning from https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default: error: chmod on /srv/www/feedxl/.git/config.lock failed: Operation not permitted
    default: fatal: could not set 'core.filemode' to 'false'
    default: Git failed to clone the site template for feedxl. It tried to clone the master of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git into /srv/www/feedxl
    default: VVV won't be able to provision feedxl without the template. Check that you have permission to access the repo, and that the filesystem is writable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The full output is [here](https://gist.github.com/cagross/6cd80d463ab6ed4ca676ce14bcfc3197).

**Comment by tomjn** [comment] 2019-04-27 16:42
as a stopgap, you can git clone on the host using a git client, then reprovision. I'm inclined to merge #1766 for consistency purposes

**Comment by tomjn** [comment] 2019-04-28 15:24
> mv: inter-device move failed: ‘test’ to ‘/srv/www/test’; unable to remove target: Is a directory

Was there already a `test` folder in `/srv/www`? If so that would explain the issue.

Try again but:

 - `vagrant up`
 - add a site called `cagrosstest` with the custom site template to `vvv-custom.yml`
 - run `vagrant ssh`
 - `git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /tmp/cagrosstest`
 - `mv /tmp/cagrosstest /srv/www`
 - `exit`
 - `vagrant provision`

Do those comments work, and does it provision the site as expected?

Finally, you can remove the `cagrosstest` folder to cleanup for any other tests we do

**Comment by cagross** [comment] 2019-04-28 16:54
> Was there already a test folder in /srv/www? If so that would explain the issue.

OK right, good catch.  I removed it manually, then re-added the `test` folder to /srv/www, then tried to provision, but same error.

> Do those comments work, and does it provision the site as expected?

Your latest suggestion seems to have worked--the `cagrosstest` site provisioned without error [full output here](https://gist.github.com/cagross/4c7027ed26fb73c5d28ed77d4dcb859f), and I can open the front-end in my browser.

> Finally, you can remove the cagrosstest folder to cleanup for any other tests we do via rm -r /tmp/cagrosstest and rm -r /srv/www/cagrosstest

Right O, thanks.

**Comment by tomjn** [comment] 2019-04-28 17:04
That's awesome news, can you do a little more stuff and check the site
continues to work as expected? My other thought was to test rsync based
shared folders but I think cloning and moving into place is the trick.

My other concern is using git commands. Can you do this again but with a
personal git repo? I'm not so interested in testing provisioner a so you
might not need them at all, but rather the ability to git pull and commit

**Comment by jjsanderson** [comment] 2019-04-29 08:11
Back at my desk.

> 1. switch to the `develop` branch

```
git checkout develop
git pull
vagrant up --provision
```

Fails with:

```
[...]
default: Downloading wordpress-one, git cloning from https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default: error: chmod on /srv/www/wordpress-one/.git/config.lock failed: Operation not permitted
    default: fatal: could not set 'core.filemode' to 'false'
    default: Git failed to clone the site template for wordpress-one. It tried to clone the master of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git into /srv/www/wordpress-one
    default: VVV won't be able to provision wordpress-one without the template. Check that you have permission to access the repo, and that the filesystem is writable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

> 2. SSH into the VM with `vagrant ssh`
> 3. Run 2 git clones, I want to know the result of each:
>    a. Clone into a VM folder `git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /tmp/test`

```
$ git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /tmp/test
Cloning into '/tmp/test'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 108 (delta 2), reused 9 (delta 2), pack-reused 99
Receiving objects: 100% (108/108), 25.51 KiB | 967.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
```

>    b. Clone into a network share folder `git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /srv/www/test`

```
$ git clone https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git /srv/www/test
Cloning into '/srv/www/test'...
error: chmod on /srv/www/test/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'
```

> What happens if you try to move [the first] git clone into a mounted/shared folder? Does that work?  If so does a git pull also work?

```
vagrant@vvv:~$ cp -r /tmp/test /srv/www/test
vagrant@vvv:~$ cd /srv/www/test
vagrant@vvv:/srv/www/test$ ll
total 12
drwxrwxr-x 1 www-data vagrant  224 Apr 29 08:08 ./
drwxrwxr-x 1 www-data vagrant  128 Apr 29 08:08 ../
drwxrwxr-x 1 www-data vagrant  416 Apr 29 08:08 .git/
-rwxrwxr-- 1 www-data vagrant   46 Apr 29 08:08 .gitignore*
drwxrwxr-x 1 www-data vagrant  128 Apr 29 08:08 provision/
-rwxrwxr-- 1 www-data vagrant 2878 Apr 29 08:08 README.md*
-rwxrwxr-- 1 www-data vagrant   17 Apr 29 08:08 wp-cli.yml*
vagrant@vvv:/srv/www/test$ git pull
Already up to date.
```

So... that works. Huh. Continuing to work through thread...

**Comment by jjsanderson** [comment] 2019-04-29 08:25
OK, so manually pulling in the `custom-site-template` and moving it across to `/srv/www`, then (on host) `vagrant provision`, *does* seem to work for me. I had to do this for `wordpress-one` and `wordpress-two`, or the provisioner errored out on the former.

**Comment by cagross** [comment] 2019-04-29 11:10
@tomjn I'll need a few days to continue testing.  Some things came up on my end.

**Comment by benlumia007** [comment] 2019-04-29 15:10
question is the box that you are using is from 20190424.0.0

**Comment by tomjn** [comment] 2019-04-29 15:12
I've tested with that box locally and not been able to reproduce the problem

**Comment by benlumia007** [comment] 2019-04-29 15:17
So i have tested the following
OS: Windows 10, MacOS, and Linux
VirtualBox: 6.0.6r130049
Vagrant: 2.2.4

I couldn't replicate the problem anymore, i had one computer had this problem but somehow when i did some vagrant commands and it just worked again.  This is a weird case.

**Comment by jjsanderson** [comment] 2019-04-29 15:38
> question is the box that you are using is from 20190424.0.0

Yes, that's the box I'm using.

> So i have tested the following
> OS: Windows 10, MacOS, and Linux
> VirtualBox: 6.0.6r130049
> Vagrant: 2.2.4
> 
> I couldn't replicate the problem anymore, i had one computer had this problem but somehow when i did some vagrant commands and it just worked again. This is a weird case.

Quite. I only have OS X systems available for testing, but my laptop with apparently-identical software doesn't exhibit the same response. I'm glad I'm not the only one who's see the issue.

**Comment by benlumia007** [comment] 2019-04-29 17:14
@jjsanderson 
did you had any issues before when this started.

**Comment by jjsanderson** [comment] 2019-04-29 18:20
@benlumia007 no problems prior to this, in several years’ use. However, I’d been away from the affected iMac for an extended period, and it had a bunch of updates pending to the system, apps, brewed packages, and so on. I can’t for certain say which updates, if any, caused the issue. No apparent disk problem, either.

**Comment by jjsanderson** [comment] 2019-05-01 13:03
In a previous comment, I wrote:

> vagrant@vvv:~$ cp -r /tmp/test /srv/www/test

However, if I `mv` the directory I get a slew of 'Operation not permitted' errors on 'preserving times' and 'preserving permissions', for each file. So the permissions issue really isn't limited to git operations.

**Comment by tomjn** [comment] 2019-05-01 13:43
Do you have the VB Guest extensions updated inside the VM? Try the `vagrant plugin install vagrant-vbguest` plugin, and open virtualbox and check the extension pack matches your current version

My understanding is that on a Virtualbox shared folder, we can set the permissions on mount, but can't change them, yet this hasn't been a problem for 99.999% of VVV users, it's odd that 2 cases of it would show up out of the blue, and on systems that were previously working

**Comment by tomjn** [comment] 2019-05-01 13:46
As an additional note, on Windows I'd advise using VirtualBox 5.x branch. 6 might work but if Hyper-V or any portion of the Windows hypervisor is enabled ( it can be enabled even when Hyper-V is turned off if the WLS is active, or virtualmachine services, etc ), then VBox attempts to use the Windows Hyper Visor, giving a big performance hit, and enabling not so well tested VBox code

**Comment by jjsanderson** [comment] 2019-05-14 14:51
Apologies for my absence.

I don't think I have an even vaguely-working install on which to test, at this point; my main install is now in a borked state somewhere between VVV 2 and 3; downgrading to 2 fails with unretrievable PHP packages (which I think is as expected, currently?).

A clean install of the develop branch, as of this morning, threw the same errors I was seeing with v2.6. When I have chance I'll try with the vbguest plugin.

However, we should probably park this issue and revisit post-VVV 3 release?

**Comment by tomjn** [comment] 2019-05-14 15:02
> I don't think I have an even vaguely-working install on which to test, at this point; my main install is now in a borked state somewhere between VVV 2 and 3; downgrading to 2 fails with unretrievable PHP packages (which I think is as expected, currently?).

VVV 2 is broken, with no plans to fix it, the steps needed to rebuild all the necessary packages would take infrastructure and time that simply aren't available, with the end result being people split across 2 major forks of VVV

> A clean install of the develop branch, as of this morning, threw the same errors I was seeing with v2.6. When I have chance I'll try with the vbguest plugin.

I actually encountered the issue when testing VVV 3, and made a change to the vagrantfile that fixed it for myself

**Comment by jjsanderson** [comment] 2019-05-14 15:08
> VVV 2 is broken, with no plans to fix it, the steps needed to rebuild all the necessary packages would take infrastructure and time that simply aren't available, with the end result being people split across 2 major forks of VVV

Understood, and appreciated. Is it worth a banner on the repo. README to warn any newcomers of the current status?

> I actually encountered the issue when testing VVV 3, and made a change to the vagrantfile that fixed it for myself

Hah! Is that #1686 ? 

Thanks for your continued efforts; fingers crossed for a smooth VVV 3 process.

**Comment by tomjn** [comment] 2019-05-14 15:20
> Hah! Is that #1686 ?

Nope, it was owner/group/fmode/dmode changes

---

Having said that, I've a theory I'd like you to test:

 1. switch back to VVV 3
 2. eliminate the folder if it's got a partial git clone
 3. Adjust `provision/provision-site.sh` by removing the `noroot` on the git commands, specifically those around line 105 where it clones the repo
 4. reprovision and check if it makes a difference

**Comment by jjsanderson** [comment] 2019-05-14 15:26
OK, will try to do this tomorrow morning (UK time) and will report back.

**Comment by tomjn** [comment] 2019-05-14 15:59
> OK, will try to do this tomorrow morning (UK time) and will report back.

Thanks! I know it's close to end of day here ( Manchester here )

@cagross same goes for you, removing the `noroot` fixed the same issue but for cloning utilities during provisioning. I'm still not sure why it fixes it, or what causes it, but it seems the next logical step

**Comment by tomjn** [comment] 2019-05-14 16:50
@cagross @jjsanderson that change got merged into `develop`, so a pull down and reprovision should be all that's necessary to test

**Comment by cagross** [comment] 2019-05-15 05:24
@tomjn OK I'm back, sorry for the delay.

> so a pull down and reprovision should be all that's necessary to test

OK I can give this a shot.  But to be clear, this is what I will do:

1. Ensure my VVV directory is free of any test sites previously created during this exercise.

2.  From my VVV directory, run a `git pull`

3.   Ensure vvv-custom.yml contains an entry for a new VVV site.

4.  From my VVV directory, run a `vagrant up --provision`

Is that correct?

**Comment by tomjn** [comment] 2019-05-15 09:01
Thats right, if you haven't updated to VVV 3 you'll also need to destroy
your existing VM to recreate it on Ubuntu 18

**Comment by jjsanderson** [comment] 2019-05-15 11:18
:-(

Fresh clone of develop branch, `vagrant up --provision` fails (initially quite early on, with adding hosts), then a second attempt fails in the same way as previously.

I've tried with fresh pulls and boxes, both before and after installing the `vagrant-vbguest` plugin.

`provision-site.sh` does not have `noroot` directives in the site provision clone (line 105).

Drat.

**Comment by cagross** [comment] 2019-05-15 11:22
@tomjn OK.  I need to first update to VVV 3.  Let me carefully do that, then revisit this test.

**Comment by jjsanderson** [comment] 2019-05-15 14:40
I just updated to the new VirtualBox 6.0.8 release: there are several lines in the [release notes](https://www.virtualbox.org/wiki/Changelog-6.0#v8) about shared folders and permissions (albeit for Windows hosts, not Mac OS). Working in my VVV3 `develop` pull from this morning:

    vagrant destroy
    vagrant up --provision

...completes without error. Wordpress-one and -two are provisioned, `vvv.test` is working, `one.wordpress.test` is working, everything smells of roses.

**Comment by tomjn** [comment] 2019-05-15 14:43
yikes, how did I miss a vbox maintenance release, @cagross can you update to VirtualBox 6.0.8?

**Comment by jjsanderson** [comment] 2019-05-15 14:51
The vbox update was on Monday (though it didn't show up for me until today).

I've just added sites to `vvv-custom.yml`, and they've provisioned correctly too. This text box is too small to contain my jubilation.

**Comment by cagross** [comment] 2019-05-15 15:20
> @cagross can you update to VirtualBox 6.0.8?

I can.  But I'm still struggling to update to VVV 3 (over in the the VVV 3 issue).

**Comment by Mte90** [comment] 2019-06-20 14:33
Can you check with the latest version on develop branch?

**Comment by benlumia007** [comment] 2019-06-20 14:36
this is due to permissions, I was having issues with permissions like this, I had to use `:owner` and `:group` a with mount_options to fixed the permissions for the shared folder on my of my laptops

**Comment by Mte90** [comment] 2019-06-20 14:38
I know but in the meantime we changed a lot of things and fixed permissions in few part of the provisioner so a new check with the latest release is helpful to understand if it is still an issue or not.

**Comment by cagross** [comment] 2019-06-20 15:37
@Mte90 Sorry I won't be able to carry out any more testing at this point.  Due to the issues during VVV update, I had to switch to a different local development platform.  I'll probably stick with it for at least the near future.

**Comment by tomjn** [comment] 2019-08-06 18:07
I'm closing this out, we've changed our box, provisioners, and moved from Ubuntu 14 to 18. If anybody gets this again please feel free to reopen

**Closed by tomjn** 2019-08-06 18:07 UTC
Labels: support
