### ISSUE TITLE
Parallels - WordPress Permission Denied

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#2440] opened 2021-04-19 23:11 UTC
## Expected Behavior

When working with WordPress, we should be able to delete and add plugins and themes using the dashboard.
## Current Behavior

At this moment, parallels mount_options are set to `mount_options: []`, i have verified this is the case below.
![wordpress-asking-for-ftp-credentials](https://user-images.githubusercontent.com/11844123/115314252-ae9a2200-a129-11eb-8507-5a51521e26aa.png)

## Possible Solution

we need to change it to  `mount_options: [ 'share' ]`

we need to change from
```
override.vm.synced_folder 'www/', '/srv/www', owner: 'vagrant', group: 'www-data', mount_options: []
```
to
```
override.vm.synced_folder 'www/', '/srv/www', owner: 'vagrant', group: 'www-data', mount_options: [ 'share' ]
```

**Comment by evertiro** [comment] 2021-04-19 23:18
Duplicate of #2398

**Comment by benlumia007** [comment] 2021-04-19 23:19
I'm linking this reference here: https://github.com/Parallels/vagrant-parallels/issues/135

**Comment by evertiro** [comment] 2021-04-19 23:45
I've confirmed that this is the same issue as #2398, and added the mount option to my existing PR. Closing this issue as a duplicate, HUGE thanks for figuring this one out.

**Closed by evertiro** 2021-04-19 23:45 UTC
Labels: bug
