### ISSUE TITLE
How do I change back to ver 2.1. of VVV. I currently have v2.2.1

### ISSUE THREAD

**Issue by eno812** [Varying-Vagrant-Vagrants/VVV#1510] opened 2018-05-15 06:44 UTC
## Current Behavior

WARNING: Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

  vagrant plugin uninstall vagrant-triggers

Note that the community plugin `vagrant-triggers` and the core trigger feature
in Vagrant do not have compatible syntax.

To disable this warning, set the environment variable `VAGRANT_USE_VAGRANT_TRIGGERS`.
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostsupdater (= 1.0.2)'

## Steps to Reproduce (for bugs)

1. vagrant up
2.
3.
4.

## Your Environment

* VVV version: 
* VVV Git Branch: 
* Vagrant version:
* VM Provider name: 
* VM Provider version:
* Operating System and version:

**Comment by eno812** [comment] 2018-05-15 07:55
I'm going to do a clean install. To confirm, I should install VVV2.2.1 and Vagrant 2.1 ?

Do I still install install vagrant-hostsupdater vagrant-vbguest ?

**Comment by benlumia007** [comment] 2018-05-15 07:57
you will need to still install vagrant plugin install vagrant-hostsupdater

**Comment by eno812** [comment] 2018-05-15 08:54
Ok, thanks.

**Comment by benlumia007** [comment] 2018-05-15 08:57
I'm just confirming if the latest develop branch as issue, I was having issues for some reason after i killed the virtual machine, but I'll let you know 

maybe i'm to tired thinkin of it haha

**Comment by eno812** [comment] 2018-05-15 09:06
Ok. Yes forget it for the moment and start fresh tomorrow.

**Comment by Mte90** [comment] 2018-05-15 13:12
Yes the develop or new future version don't require anymore that plugin and is enough to uninstall as written in the error reported :-)

**Comment by tomjn** [comment] 2018-05-15 13:19
Looks like `    default: Unable to locate package language-pack-UTF-8` is the culprit

**Comment by benlumia007** [comment] 2018-05-15 23:28
@eno812 
after the merge of #1512, everything is fine now, so doing a kill vm and doing a fresh provision seems to be flawless.

**Comment by eno812** [comment] 2018-05-15 23:38
@benlumia007 Good to hear. I'm just about to do the same.

**Comment by tomjn** [comment] 2018-05-16 12:10
@eno812 are things working well for you now? I'm holding off making any changes, and hoping to release v2.2.1 to `master` today or tomorrow once it's been confirmed by several people

@benlumia007 thanks for the testing and checks on multiple machines, you've been a real help :)

**Comment by benlumia007** [comment] 2018-05-16 14:48
@tomjn 
hey man, no problem, seems like everything works, on Windows, Mac, and of course I also tested Ubuntu 16.04 LTS, i haven't test 18.04 LTS yet. but eventually I will be getting that sooner or later.

**Comment by eno812** [comment] 2018-05-16 21:37
I'm still struggling to get up. I removed everything and tried a clean install but now I get this message on vagrant up --provision

A VirtualBox machine with the name 'Vagrant-Local_3264764ca27' already exists.
Please use another name or delete the machine with the existing
name, and try again.

**Comment by benlumia007** [comment] 2018-05-16 21:40
@eno812 you need to go to open virtualbox and delete the machine from there.

**Comment by eno812** [comment] 2018-05-16 21:59
Ok, thanks @benlumia007

**Comment by eno812** [comment] 2018-05-16 22:53
That did the trick thanks @benlumia007

**Comment by tomjn** [comment] 2018-05-16 23:51
Awesome, closing the issue

**Closed by tomjn** 2018-05-16 23:51 UTC
