### ISSUE TITLE
SSH connection refused, timeout while waiting to boot...

### ISSUE THREAD

**Issue by trevorberman** [Varying-Vagrant-Vagrants/VVV#600] opened 2015-03-25 21:19 UTC
This is my first go at trying to set up a WP development environment.
Windows 7 x64 (virtualization enabled in BIOS)
Vagrant 1.7.2 and fresh VVV clone

Seems like everything installed as expected but "vagrant up" keeps ending with a timeout after the SSH connection is continually refused.

![vagrantup_connectionrefused](https://cloud.githubusercontent.com/assets/8570863/6835363/31df0d98-d308-11e4-9bf3-3601fd54d347.JPG)

Thought this looked similar to what was happening in issue #375 and tried all the troubleshooting there to no avail. Additionally, I enabled the GUI through the Vagrantfile. It showed me when the command-line hits the first "connection refused" the machine prompts for user/pass through the GUI. I don't understand that, since it's supposed to be connecting through SSH. So, thought it might be the cause or at least a solid clue. However, not sure how to proceed fixing from here. Any help would be very much appreciated.

**Comment by jeremyfelt** [comment] 2015-04-12 02:52
Hi @trevorberman, thanks for opening an issue here. I'm going to close this as a duplicate of #375 as I think it's the same general problem. This is more of an issue with Vagrant than VVV, but that thread has been a helpful discussion area.

There has to be some missing piece in all of this. I'm hoping to bring up a Windows machine at some point to try and duplicate the issue myself.

**Closed by jeremyfelt** 2015-04-12 02:52 UTC
