### ISSUE TITLE
http://vvv.dev/database-admin/ loads dashboard

### ISSUE THREAD

**Issue by alexmoss** [Varying-Vagrant-Vagrants/VVV#772] opened 2015-10-24 08:59 UTC
Hi guys,

First time installing VVV from MAMP. All installed fine, but I can't access phpMyAdmin. I can navigate to http://vvv.dev/database-admin/ but only shows me the dashboard again. If I click phpmyadmin again it takes me to http://vvv.dev/database-admin/database-admin/ where the subfolder adds itself again (and can go on forever) but loads the dashboard.

What am I doing wrong here? I assume this is some kind of permissions issue but there's not a lot on the web from my research...

Thanks

**Comment by jeremyfelt** [comment] 2015-10-25 19:50
Hi @alexmoss, thanks for the report.

I'm not able to reproduce this locally. `vvv.dev/database-admin/` works fine for me. Are you able to access other default sites through vvv.dev?

One option may be to delete the `{vvv-dir}/www/default/database-admin/` directory and then run `vagrant provision` again to see if it populates correctly.

**Comment by alexmoss** [comment] 2015-10-26 14:26
Very odd. That folder doesn't exist. I have done destroy, up and provision - none of which generate the folder.

**Comment by RajeebTheGreat** [comment] 2015-11-24 11:59
I'm facing the same issue.

**Comment by polykrom** [comment] 2015-12-02 11:54
I have exactly the same issue...

Any help please ?

thanks

**Comment by polykrom** [comment] 2015-12-02 16:48
Ok, Find the solution to this issue...

In my first install of VVV i used the zip released of VVV , i've just installed the git version and it works simply nice with it !

seems the stable .zip release it outdated ....

:)

**Comment by jeremyfelt** [comment] 2016-02-21 20:52
I'm going to close this out now that 1.3.0 has been released. The provided stable release should now be better.

**Closed by jeremyfelt** 2016-02-21 20:52 UTC
Labels: bug
